### ISSUE TITLE
[Feature Request] Per-word deletion when swiping on backspace instead of per-letter

### ISSUE THREAD

**Issue by FlynnD273** [futo-org/android-keyboard#100]
Should replicate GBoard's behaviour of deleting whole words instead of individual characters when you swipe on the backspace key.

**Comment by needlesslygrim** [comment]
It would be nice if this was actually made configurable, since I actually prefer the per key deletion.

**Comment by pearcebasmanm** [comment]
An option that might be nontrivial to implement but be the most useful to me would for backspace-swipe to select words when swiping quickly and select letters when swiping slowly, similarly to touchpad acceleration. At the moment I find it impossible to delete what I want with a single swipe, but retaining fine-grained control would be fantastic.

**Comment by vsalvino** [comment]
Similarly, the Microsoft SwiftKey keyboard has a feature where press and hold the backspace key does whole word deletion (with chaotic feedback). Love that feature.

Overall this is a fantastic open source keyboard, thank you for your efforts!

**Comment by kjkrum** [comment]
See #20.

**Comment by abb128** [comment]
An option for this will be included in the next release
