### ISSUE TITLE
Tap-position based suggestions

### ISSUE THREAD

**Issue by nh2** [futo-org/android-keyboard#101]
Forwarding from https://news.ycombinator.com/threads?id=nh2#40835226:

SwiftKey is clever in that it corrects depending on where you press in the key:

If I type "Akk" it corrects it to "All" only if I pressed the "k" on its right side (near the "L" key); if I pressed it further left, it keeps "Akk".

That works really well.

Does/could FUTO do that too?

**Comment by abb128** [comment]
The correction algorithms already use sub-key positioning data, although "akk" is still likely to correct to "all" no matter how you tap currently because it's not a word
