### ISSUE TITLE
[Bug] Unclear Language in Setup

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#104]
In step 3 of 3 of the current keyboard setup, there is this text and two buttons (represented with '`<>`') below it

> Choose whether you want to use built-in voice input, or the system voice input. `<Use built-in (mic permission needed)>` `<Use system>` 

Is 'built-in' referring to the FUTO keyboard itself and 'system' to whatever your device's default is? If so, wouldn't something like this be much clearer?

> Choose voice input `<FUTO Keyboard>` `<Device Default>`

**Comment by abb128** [comment]
This will be updated in the next release

**Comment by abb128** [comment]
@issuant What do you find unclear about the text?
