### ISSUE TITLE
[Bug] Gap Row in Symbols View

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#105]
In the second symbols view, there is a weird gap row in the keyboard. Comparing it with Swiftkey, the reason is because there are simply not enough characters to 'fill out' the missing row in the keyboard. 

Swiftkey, which has my preferred layout and aesthetic, handles this by simply shortening the keyboard when you enter symbols view, both symbols views, eliminating the gap row in the process.

**Comment by DavidBevi** [comment]
ℹ️ Futo v0.1.22-playstore: ![Screenshot_20240704-153834](https://github.com/futo-org/android-keyboard/assets/61429850/4cb4636d-71dc-46e7-916f-ec952e43730f)

👍 Please, copy Heliboard:
![Screenshot_20240704-154859](https://github.com/futo-org/android-keyboard/assets/61429850/dda3104a-3931-47a3-be84-d81800916b66)

👎 Please DON'T copy Gboard:
![Screenshot_20240704-155158](https://github.com/futo-org/android-keyboard/assets/61429850/5cdef036-d506-4af9-a1bc-b6dc40fa548b)
Please DON'T drop a row of symbols.
Please DON'T hide Slash in symbols-2.

**Comment by swishkin** [comment]
Possibly related to #95.

**Comment by abb128** [comment]
More symbols will be shown in the next version similar to Heliboard
![image](https://github.com/futo-org/android-keyboard/assets/65567823/5ce73d12-1a00-44eb-9e2b-95ce90729dc1)

**Comment by DavidBevi** [comment]
The 'weird' gap derives from the QWERTY layout, as the ASDF row has 9 keys.

Then, 9 or 10 keys is a matter of tastes, I prefer having the same layout across layers but I get that it can be limiting.
