### ISSUE TITLE
[Feature request] Add dynamic themes that will follow system ones

### ISSUE THREAD

**Issue by GNUser224** [futo-org/android-keyboard#109]
It would be useful, because my dark/white theme switch is scheduled, and it's a bit annoying to constantly going into keyboard's settings and changing theme manually

**Comment by abb128** [comment]
This is what Dynamic Auto is supposed to be, does it not switch automatically for you?

**Comment by GNUser224** [comment]
> This is what Dynamic Auto is supposed to be, does it not switch automatically for you?


If you mean dynamic theme for keyboard, I cannot find anywhere that option
