### ISSUE TITLE
Improved visibility for keyboard size settings

### ISSUE THREAD

**Issue by nutpantz** [futo-org/android-keyboard#11]
While phone's are getting bigger the displayed keyboard is also getting bigger but not everyone needs a half screen keyboard on a 7 inch screen
(Or even a 2.5 inch on a 5 inch screen)

Adjustable keyboard height or extra small, small,medium, large, options error be nice

**Comment by DanGLES3** [comment]
> While phone's are getting bigger the displayed keyboard is also getting bigger but not everyone needs a half screen keyboard on a 7 inch screen (Or even a 2.5 inch on a 5 inch screen)
> 
> Adjustable keyboard height or extra small, small,medium, large, options error be nice

The option for it is already in the theme options

**Comment by nutpantz** [comment]
Then you definitely need to put it at the top. Themes suggest colors only, I think few will scroll down

**Comment by pe1uca** [comment]
Oh, wow, that's confusing in deed. I didn't touch that menu since I wasn't interesting on checking a different theme.  

Also `Show symbol hints` it's hidden in here.  
Maybe `Appearance` would be a better name with `Theme` being a subsection inside.

**Comment by zlehnherr1** [comment]
> Oh, wow, that's confusing in deed. I didn't touch that menu since I wasn't interesting on checking a different theme.  
> 
> Also `Show symbol hints` it's hidden in here.  
> Maybe `Appearance` would be a better name with `Theme` being a subsection inside.  

Show symbol hints should be moved to preferences as well

**Comment by akirby83** [comment]
> Oh, wow, that's confusing in deed. I didn't touch that menu since I wasn't interesting on checking a different theme.
> 
> Also `Show symbol hints` it's hidden in here. Maybe `Appearance` would be a better name with `Theme` being a subsection inside.

I'm so glad I found this comment.  I didn't like that there were no symbols above the keys and just assumed this functionality wasn't implemented.  Being hidden away in something called Themes is very unintuitive IMO.

**Comment by Spiderfffun** [comment]
I suggest a similar thing like AOSP keyboard, having a `Properties` setting and a `Themes` setting that are seperate. But what @pe1uca said could work too, for appearance. I just hate it when there are nested menus but the options aren't all on the same level, so you can change some options and go one layer further on the same screen. That just confuses me.

**Comment by abb128** [comment]
After 0.1.32 the option should be more clearly visible in Keyboard & Typing > Resize Keyboard
