### ISSUE TITLE
Alternative Functions for Spacebar Double-Tap

### ISSUE THREAD

**Issue by NagBoard** [futo-org/android-keyboard#110]
We already have a function to put a dot when double-tapping, but adding some other features would be great, like double tap to change the language (alternate if 2 languages, forward if 3+ languages).

Might be useful for other cases, but mainly as an alternative to #52

**Comment by NagBoard** [comment]
Might be implemented as a time window. If, within given time, you press spacebar two times, the first one produces a space character, and the second one triggers the macro.

**Comment by dean-futo** [comment]
To change the language, all you need to do is hold down the spacebar. Please reopen this ticket if you have any other requests.
