### ISSUE TITLE
[Feature Request] Allow using Spacebar to move Cursor position 

### ISSUE THREAD

**Issue by BlackUdon** [futo-org/android-keyboard#112]
Currently, holding down spacebar allows changing language and keyboard. Can there be a toggle to allow moving the cursor position when the spacebar is held and then moving left or right. This similar to what other keyboards allow, e.g. Swift.

**Comment by Progaros** [comment]
this already exists 
you might have to enable "swipe typing"

**Comment by BlackUdon** [comment]
Thank you @Progaros

**Comment by suderman** [comment]
On that note, I'd prefer if holding the spacebar did NOT bring up the language switcher. Or at least a toggle to disable this popup I never mean to trigger.

**Comment by peter-vasut** [comment]
> On that note, I'd prefer if holding the spacebar did NOT bring up the language switcher. Or at least a toggle to disable this popup I never mean to trigger.

Maybe it would make sense to allow disabling it in the future. Complete removal is bad idea unless there is some substitute:

* It's pretty standard behavior, Gboard behaves similarly (although it takes bit more time for the menu to pop-up and the menu is more cluttered).
* It's quite essential feature for us who communicate in multiple languages, at least until there is some support for multi-lingual input.

**Comment by suderman** [comment]
Agreed. For reference, [Heliboard](https://github.com/Helium314/HeliBoard) currently has this toggle:

![image](https://github.com/futo-org/android-keyboard/assets/12491/9e97ad8e-71eb-4ea6-b884-46ab4e12a31c)

**Comment by NagBoard** [comment]
> Agreed. For reference, [Heliboard](https://github.com/Helium314/HeliBoard) currently has this toggle:
> 
> ![image](https://github.com/futo-org/android-keyboard/assets/12491/9e97ad8e-71eb-4ea6-b884-46ab4e12a31c)
> 

Related to #45

**Comment by mtalexan** [comment]
On Gboard, Swift keyboard, and most other keyboards, you hold spacebar and then can move the cursor, while you swipe sideways on the spacebar to change languages. This is exactly the opposite FUTO, which is pretty annoying when I switch between keyboards (I use different keyboard apps for different language).

**Comment by abb128** [comment]
Closing as this is already implemented
