### ISSUE TITLE
No forward slash on english keyboard in accent characters or "." long press options

### ISSUE THREAD

**Issue by brycebba** [futo-org/android-keyboard#116]
I noticed that the most useful slash for standard typing is missing from the english keyboard unless you go into the "?123" menu but the backslash is available as the long press character on "w" as well as in the "." long press menu but backslashes are rarely used outside of technical reasons like an IDE or file paths, etc. Could we get the forward slash in the "." menu or make that area configurable? That would be even better! I will take any solution you can give though! Thank you!

**Comment by FaridZelli** [comment]
It's not missing, you can long press **m** and slide to the right.

**Comment by abb128** [comment]
In 0.1.23.2 the period long-press was updated to a more standard layout including forward slash
