### ISSUE TITLE
[Feature Request] Swipe shortcuts for common actions - eg. change word case, select all, cut, copy, paste, switch numpad, change language

### ISSUE THREAD

**Issue by just-simon** [futo-org/android-keyboard#117]
Love the keyboard so far!
It would be a huge quality of life improvement to have quick and easy swipe shortcuts to perform actions.
My simplistic thought is swiping from the keyboard button:

| Swipe to key | Action performed |
| --- | --- |
| Shift | Provides options to change to all upper case, all lower case, and title case, for the word where the cursor is |
| A | Select all |
| X | Cut selected text |
| C | Copy selected text |
| V | Paste clipboard |
| N | Switch to numpad |
| Space | Change language |

Probably not needed, but I spent 30 seconds in Gimp, so why not:

![image](https://github.com/futo-org/android-keyboard/assets/76638357/c180d4cf-88e6-4eb6-8362-aee20fabfdfe)

**Comment by Progaros** [comment]
Nice Idea!

additions:
Z | Undo
Y | Re-Do
E | Switch to Text Editor (?)

**Comment by just-simon** [comment]
Thank you for your input!
I was hesitant to suggest too many shortcuts, but happy someone else sees the value of this idea and builds on it.

When you say 'Switch to Text Editor', do you mean whatever the default text app is?
tbh, I don't use a text editor on my phone.  What do you use?

**Comment by NagBoard** [comment]
Wow, that would be neat!

**Comment by PPTRanger** [comment]
Shortcuts are a major missing feature.

**Comment by MulverineX** [comment]
The latest update has a creative solution for this, might be satisfactory for y'all

**Comment by abb128** [comment]
Closing this as the morekey shortcuts are similar to what was requested

**Comment by just-simon** [comment]
I can't find how to get the prerelease, is it restricted access?

**Comment by abb128** [comment]
@just-simon This feature has been released for about 2 months now, it's available in the latest release of v0.1.23.2

**Comment by just-simon** [comment]
Ahh ok, gotcha.
@MulverineX 's explanation didn't make sense to my simpleton brain.

For anyone stumbling onto this thread and doesn't know how it works, the long press keys correspond to to the Ctrl + in Windows and Linux.

| Long press key | Shortcut | Icon |
| :---: | --- | --- |
| C | Copy | ![image](https://github.com/user-attachments/assets/91922c2b-09e0-408d-9218-fabcdd953b35) |
| X | Cut | ![image](https://github.com/user-attachments/assets/0fa54326-dd4d-42f1-932e-f61a36a47d1f) |
| V | Paste | ![image](https://github.com/user-attachments/assets/71bff134-6f2c-408f-a6e1-cf8b101d65ac) |
| A | Select all | ![image](https://github.com/user-attachments/assets/da0c691a-676d-4243-9c17-8fcf33c300b7) |
| Z | Undo | ![image](https://github.com/user-attachments/assets/2352dc62-1157-4ee7-a75b-dc7d79b92f35) |
| Y | Redo | ![image](https://github.com/user-attachments/assets/518e0fa5-ed95-4b24-9c75-826f70322b2d) |
