### ISSUE TITLE
Move animal emojis from food to animals tab

### ISSUE THREAD

**Issue by rskinner-pn** [futo-org/android-keyboard#118]
currently shrimp, lobster, crab, and oyster emojis are under the food tab, but i think it would make more sense to put under the animals/nature tab

**Comment by abb128** [comment]
Shrimp and the others seem to be officially food emojis: https://www.unicode.org/L2/L2015/15267r3-food-emoji.pdf

The keyboard uses the [gemoji database](https://github.com/github/gemoji/blob/master/db/emoji.json) which lists these all as food
