### ISSUE TITLE
Expanded Clipboard Manager Settings

### ISSUE THREAD

**Issue by maxleirbag** [futo-org/android-keyboard#119]
I noticed the clipboard of this Keyboard is limited to the last copied content. It would be awesome for the keyboard to allow configuration, such as: 
- the maximum length of items stored in the clipboard;
- A feature capable of resetting the clipboard history, automatically, through a scheduled time or a countdown timer (daily for example);
- A shortcut to the full list of items stored.

**Comment by NickPfeiffer** [comment]
There is a clipboard history/manager. Just turn it on in the settings category _Typing Preferences_

**Comment by itsordinaryperson** [comment]
Add option to turn on/off confirmation while clearing unpinned items in clipboard history manually.

**Comment by dean-futo** [comment]
Duplicate of #225 - merging this request into that one.
