### ISSUE TITLE
Adjustable Vibration Strength on Keypress

### ISSUE THREAD

**Issue by laundmo** [futo-org/android-keyboard#124]
i'm coming from FlorisBoard where i have the vibration set to 1ms and strength to 100% which causes a very tactile snapping feeling.

i'm have the same feeling haptics set up from system settings.

sadly, in FUTO keyboard it doesnt seem like this is possible, with the vibration still feeling a bit too long/weak at the shortest duration of 1ms.

Also, i'd love vibration feedback when swiping the backspace to delete, or swiping the spacebar to move cursor, but thats just nitpicking at this point.

**Comment by Progaros** [comment]
I'd also like to see the vibration feedback

**Comment by FetchFast** [comment]
I think what you're saying is that vibration duration is useful, but you want a strength setting as well?

**Comment by laundmo** [comment]
> I think what you're saying is that vibration duration is useful, but you want a strength setting as well?

yes, i thought i made myself clear but thats a very concise way of putting it

**Comment by dean-futo** [comment]
@laundmo we have implemented this. In settings, go to **Keyboard & Typing** and scroll all the way down to adjust vibration strength.
