### ISSUE TITLE
Backup and Sync Feature for Settings and Dictionary

### ISSUE THREAD

**Issue by vgamesx1** [futo-org/android-keyboard#125]
Not as if there's an excessive number of options (currenly) but an obvious addition that doesn't seem to be on the roadmap is a simple data import\export, cloud options would be unnecessary but nice.

Thank you

**Comment by Exp-01** [comment]
Do you mean "Show symbol hints"? its in theme settings at the bottom

**Comment by vgamesx1** [comment]
Oh... Yes that's what I wanted, what a strange place to put it, I looked at a few themes then backed out because I thought it looked fine as is.

**Comment by BoscoDomingo** [comment]
I second this. Having multiple devices I would love to be able to sync my settings across all of them, as well as my personal dictionary

**Comment by dean-futo** [comment]
Very similar to #643 - merging this issue into that one, to keep the focus on adding backup rather than both backup and sync. Please comment on that thread if you have further input.
