### ISSUE TITLE
Do Not Correct Word to Itself

### ISSUE THREAD

**Issue by peter-vasut** [futo-org/android-keyboard#134]
Type `Hello`. The suggestion bar shows `Hello` in the middle in bold, and it gets *blue* underline in the text, as if there is some error in the word, even though it is not going to be changed. It's misleading, you have to check what's the issue and if the keyboard is going to replace intended word with something else, even though everything is spelled correctly and nothing's going to change.

**Comment by kjkrum** [comment]
I'm not seeing blue underlines, but the suggestion bar *always* suggests the current word, which is a waste of a suggestion.

**Comment by dean-futo** [comment]
Consolidated into #672
