### ISSUE TITLE
Inconvenient placement of 'ß' key on german keyboard layout

### ISSUE THREAD

**Issue by bestlinuxgamers** [futo-org/android-keyboard#135]
For someone to type 'ß' with the german keyboard layout on the futo keyboard requires long pressing on the 's' key and then move the finger one to the right.
![Futo_keyboard](https://github.com/futo-org/android-keyboard/assets/52172848/d8bb2e37-6759-4f52-b094-11cf84cfa940)

Basically every other mobile keyboard only requires a long press on the 's' key. This is the AOSP keyboard for example:
![Aosp_keyboard](https://github.com/futo-org/android-keyboard/assets/52172848/ceffb84e-e9fa-4736-922e-4242af9c88b3)

For a letter that is so commonly used in the german language this additional step makes a big difference in the typing flow.

**Comment by rdbende** [comment]
The same is true for accented letters in languages like Hungarian

FUTO Keyboard:
![futo_keyboard_á](https://github.com/futo-org/android-keyboard/assets/77941087/5f62b3d6-e708-4fba-9822-0f8694ec3bc2)

Google Board:
![gboard_á](https://github.com/futo-org/android-keyboard/assets/77941087/c26b1856-9071-4faf-9b41-861604acd408)

**Comment by abb128** [comment]
This is fixed in 0.1.23.2
