### ISSUE TITLE
Voice Typing Crashes with Hebrew Multilingual

### ISSUE THREAD

**Issue by Yuvalg1** [futo-org/android-keyboard#144]
Every time I press the microphone key the keyboard closes, and sometimes I get an error message that "FUTO Keyboard keeps stopping"

**Comment by andersevenrud** [comment]
Same problem here for any non-English language I use. I tried all the different packs with the same result.

I don't know how to investigate further, because there's no obvious way to view the logs (even when in debug mode) afaik.

**Comment by dean-futo** [comment]
Consolidated into #664
