### ISSUE TITLE
[Feature request] Multilingual keyboards

### ISSUE THREAD

**Issue by NagBoard** [futo-org/android-keyboard#146]
Would be good to be to turn on an option to be able to type ukrainian "i" when long-pressing russian "и", which is standard since they both indicate the same sound. 

This might be useful for other languages as well, or may be further implemented into russian keyboard with letters "ъ" and "ї", which is standard too.

**Comment by Progaros** [comment]
Maybe import & export of custom key maps could be a solution. 
Everybody could create their perfect key layout and share it with each other

**Comment by NagBoard** [comment]
Closed as duplicate of #48
