### ISSUE TITLE
Bitwarden inline autofill not working in duckduckgo

### ISSUE THREAD

**Issue by ejerke** [futo-org/android-keyboard#147]
Inline autofill is not working for me when using duckduckgo and bitwarden.
Works in other browsers such as chrome and firefox.
The autofill is not triggering when I navigate to the site, but if I exit the app and open it again, it shows correctly.
Samsung Galaxy S21, One UI 6.1 (android 14)

**Comment by FetchFast** [comment]
I had this problem before I started using Futo

**Comment by ejerke** [comment]
@FetchFast Yea true my fault, this issue seems to be on the duckduckgo app, not in the keyboard.
