### ISSUE TITLE
Option to Remove "?123" Button

### ISSUE THREAD

**Issue by LucasTavaresA** [futo-org/android-keyboard#149]
With the option to enable the number row and remove the emojis button, I can get used with only using symbols by holding. 

I think it would be nice to disable this button

**Comment by Martin-L-H** [comment]
Strongly agree! The only reason to keep it would be because of the voice to text button, but I believe by moving it you can just remove the top exclamation mark row entirely.

**Comment by dean-futo** [comment]
We'll be keeping this button as it is standard in all major keyboards to indicate navigating to the numbers and symbols keyboard menu.
