### ISSUE TITLE
Feature request: Select all text

### ISSUE THREAD

**Issue by 0xedward** [futo-org/android-keyboard#15]
It'll be nice to have a select all text button on the action bar to make deleting large amounts of text easier than having to swipe on the delete button multiple times or going into text editor mode and holding down the left key after selecting the highlight and jump by word buttons.

[FlorisBoard](https://github.com/florisboard/florisboard/blob/f116e2082912b9a06ea2f7c6143caeee5b990b4d/app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt#L706) is an example keyboard with this feature

**Comment by Progaros** [comment]
would such customizatability help you?
https://github.com/futo-org/android-keyboard/issues/33#issuecomment-2181648113
the "select all" button would be one of the hideable utilities

**Comment by abb128** [comment]
This will be included in the next update
