### ISSUE TITLE
[UX] Paste and clipboard manager have the same icon

### ISSUE THREAD

**Issue by Leopold702** [futo-org/android-keyboard#155]
It's a minor issue, but also should be easy to fix/change.

I think the current icon is better suited for clipboard manager, and for paste it's better to have something similar to what iOS or Windows 10 uses.

![Screenshot_20240703-220130~2](https://github.com/futo-org/android-keyboard/assets/64221830/04e643c8-5d3e-4576-b2c3-79eabbc4ca01)

**Comment by swishkin** [comment]
Could you provide a screenshot of the iOS/Windows 10's paste icons you referred to?

**Comment by Leopold702** [comment]
Here is iOS icon:
![IMG_20240705_120929_126~2](https://github.com/futo-org/android-keyboard/assets/64221830/dd040e7b-b649-44bc-8e7b-fcda70b90ad4)

Here is Windows 11 icon:

![Capture1~2](https://github.com/futo-org/android-keyboard/assets/64221830/b3fe2993-5ee5-44bc-8422-d25f27a287fb)

Basically, they both indicate that there is some content in the clipboard that you can paste.

**Comment by abb128** [comment]
Fixed in 0.1.23
