### ISSUE TITLE
Multilingual Autocorrect: recognize language in-real time

### ISSUE THREAD

**Issue by frozht** [futo-org/android-keyboard#158]
I think autocorrect/suggested words can be improved in multilingual keyboards, perhaps it could try to identify which language is being used and automatically switch autocorrect/suggested words to the current language being written.

**Comment by SnakeSnowflake** [comment]
likely duplicates #38

**Comment by frozht** [comment]
> likely duplicates #38
Yep, duplicate.
Thanks.
