### ISSUE TITLE
Adjust Sensitivity for Swipe Gestures

### ISSUE THREAD

**Issue by oSumAtrIX** [futo-org/android-keyboard#165]
Currently there is no way to chose the sensitivity for these swipe-gestures. GBoard has a different sensitivity which makes it a bit difficult to switch over to Futo. The swipe to delete gesture may also have an option to snap to the beginning of words or delete entire words per swipe step

**Comment by dean-futo** [comment]
Consolidated into #665

**Comment by dean-futo** [comment]
Similar to #363 - merging this issue into that one. See #363 for details.
