### ISSUE TITLE
More small number characters

### ISSUE THREAD

**Issue by Lopolin-LP** [futo-org/android-keyboard#169]
I noticed the FUTO Keyboard has a lack of small numbers, only going from 1 to 4, while Gboard has all.

FUTO Keyboard:
![Screenshot_2024-07-04-13-06-00-423_org.futo.inputmethod.latin-edit.jpg](https://github.com/futo-org/android-keyboard/assets/82715586/28fb2da2-35eb-48c3-9b34-9c0be1f42bfc)

GBoard:
![Screenshot_2024-07-04-13-07-19-987_com.miui.home-edit.jpg](https://github.com/futo-org/android-keyboard/assets/82715586/b096d905-7d05-457a-8607-9307563aac0e)

I would also think that more special symbols could be added in general (if there are still some lacking, but other than numbers i didn't really find anything.)

**Comment by abb128** [comment]
This will be fixed in the next release
