### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by foolishgrunt** [futo-org/android-keyboard#17]
Sorry to clutter the Issues page with a question, but I guess you could call the current license an "issue" that has so far prevented me from paying...

Are there any plans to adopt FUTO's newly-released [GrayJay Core License](https://github.com/futo-org/grayjay-android/blob/master/LICENSE.md)?

**Comment by abb128** [comment]
The license has been updated: https://gitlab.futo.org/alex/latinime/-/blob/master/LICENSE.md

**Comment by lrq3000** [comment]
Why use a non opensource license? If you don't want big corps to steal the project and monetize it, there are other ways such as GPL which force all downstream derivative works to also be licensed under GPL (so good luck monetizing it if everyone must get the same rights you got).

This would ensure the project's longevity even when FUTO won't be the one maintaining it anymore if this ever happens (which is guaranteed to happen on a long enough timeframe).
