### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Qwerty-Space** [futo-org/android-keyboard#171]
The option to choose between suggestions and the action bar by default.  And possibly choose the layout of the action bar, and what buttons are on it.  For example, one might find it useful to have select all, cut, copy, and paste, instantly accessible instead of word suggestions.

**Comment by DavidBevi** [comment]
Just discovered: you can drag-n-drop buttons inside the action bar to re-arrange them. It seems like you can't remove them, at least not yet.

**Comment by abb128** [comment]
This seems it will no longer be relevant with the updated action bar: #244
