### ISSUE TITLE
[Bug] Vibrate on Keypress not working

### ISSUE THREAD

**Issue by otter501** [futo-org/android-keyboard#172]
I am using a Google Pixel 8 and nothing happens when I enable Vibrate on Keypress

**Comment by abb128** [comment]
What is your vibration duration set to?

**Comment by otter501** [comment]
100 ms

**Comment by luigge** [comment]
I am using a galaxy m51 and the vibration works fine in 100ms.

**Comment by JosephPaulHughes** [comment]
After installing FUTO keyboard, My OnePlus 8t sound and vibration on tap have stopped working. Adjusting the haptic in both phone settings or FUTO app do nothing. Also restarting/shutdown does not fix. I've also uninstalled the FUTO app and still no haptic feeding back on anything. 

This is kind of a big bug.

**Comment by abb128** [comment]
@JosephPaulHughes FUTO Keyboard doesn't touch any system settings or do anything particularly special with audio, so the issue you're describing might be something unrelated to FUTO Keyboard. Let me know if you figure out any more details

**Comment by otter501** [comment]
i fixed the bug by turning on touch haptics in my phone settings

**Comment by abb128** [comment]
Closing the issue if it's solved

**Comment by otter501** [comment]
i dont think this could be counted, its a little confusing that i have to enable touch in both the keyboard and phone settings, it should open up the phone touch settings so it works

**Comment by Switch123456789** [comment]
> if it's solved

Unfortunately it is not, if this setting is enabled, many gestures cause feedback (like the back-gesture), which some people might not want.

Also, when typing fast, random key-taps do not give haptic feedback, that is infuriation beyond believe.
