### ISSUE TITLE
Enable Dvorak Layout for Canadian English

### ISSUE THREAD

**Issue by Cerxi** [futo-org/android-keyboard#175]
It seems like Dvorak exists for other languages, such as American English, but for some reason Canadian English is stuck with only QWERTY? This is a pretty big deal for me and I don't quite understand why, if it exists for American English, it wouldn't for Canadian as well, since we generally use the same keyboard layout.

**Comment by dean-futo** [comment]
@Cerxi there is no Canadian English layout option, and as you said Dvorak is already an option for American English.
