### ISSUE TITLE
[Feature Request] Japanese Language Support

### ISSUE THREAD

**Issue by tommydrum** [futo-org/android-keyboard#176]
First off, awesome work here, the English side does work just about flawlessly, that said I also speak and often speak to Japanese people, making the lack of Japanese a non-starter for me...

(While the qwerty version of Japanese would work fine, the 12 key system is the standard.. Ideally having them both would be nice)

**Comment by jonathan-s** [comment]
Duplicate of #42

**Comment by tommydrum** [comment]
Duplicate of 42, sorry, closing.
