### ISSUE TITLE
Fix Internal Voice Input for Multiple Languages

### ISSUE THREAD

**Issue by DrDustwolf** [futo-org/android-keyboard#178]
Internal voice input isn't working.

The voice input for version 0.1.22 isn't working. I use several languages with the 244 word database from your page: English, United Kingdom, United States, Australia, German, Spanish, French, Polish. For German and Polish I use the dictionaries from the AOSP keyboard that is also linked on your page.

As a quick workaround I use your other app FUTO Voice Input version 0.1.3.3.

Both apps are installed via F-Droid.

![Screenshot_20240704-192518_FUTO Keyboard](https://github.com/futo-org/android-keyboard/assets/14179460/3d06de1b-9583-4723-b5d1-f007f839d7b3)
![Screenshot_20240704-192531_FUTO Keyboard](https://github.com/futo-org/android-keyboard/assets/14179460/2a6ef0f2-5f19-4011-90fa-bf4c123b4d6a)
![Screenshot_20240704-192544_FUTO Keyboard](https://github.com/futo-org/android-keyboard/assets/14179460/8cf05154-a6d7-4a1b-905e-c99c685c50cc)

**Comment by abb128** [comment]
Can you describe what isn't working exactly? Is it not typing anything at all? Is it crashing? Does it work if you use the built-in English model instead of importing?

**Comment by DrDustwolf** [comment]
It's showing: Listening > Processing > it chrashes/disappears


The built-in english voice input models didn't work either in my case.


A screen recording:
https://mega.nz/file/WCIVzB5Y#Zp1Rb_vJ4DcE_CasGg-MpMGF3U9IeOYe2AXtkA0XpuQ

**Comment by MordorMinion** [comment]
Same as #467?

**Comment by dean-futo** [comment]
Consolidated into #664
