### ISSUE TITLE
Long-press keys should default to language accents instead of symbols

### ISSUE THREAD

**Issue by seboaron** [futo-org/android-keyboard#18]
Currently (ver. 0.1.21), in the long press menus for wowels the first options are symbols (as shown in the pictures). This is a bit annoying, as Hungarian uses a lot of wowels with accent marks, and greatly reduces productivity. It would improve the experience for Hungarian massively, if the following changes would be implemented:
Instead of the symbols, these wowels should be first in the long press menu:
E -> É
U -> Ú, Ü, Ű
I -> Í
O -> Ó, Ö, Ő
A -> Á

Basically the same as in the keyboards of Google and Samsung.

![Screenshot_20240613_125427_Firefox](https://github.com/futo-org/android-keyboard/assets/94312176/c7625601-3214-46a5-b4c4-64f70f6e134b)
![Screenshot_20240613_125424_Firefox](https://github.com/futo-org/android-keyboard/assets/94312176/f9de3fc2-4f5d-4f25-a284-9da067ff84dc)
![Screenshot_20240613_125422_Firefox](https://github.com/futo-org/android-keyboard/assets/94312176/3a714b97-47cf-4ed1-af0b-0d01699b2f28)
![Screenshot_20240613_125415_Firefox](https://github.com/futo-org/android-keyboard/assets/94312176/24980035-e5ed-464c-bdb2-0e87ac50d2f7)
![Screenshot_20240613_125409_Firefox](https://github.com/futo-org/android-keyboard/assets/94312176/791a9d2e-4e6e-48cc-85a4-ef40c2dbfdec)

**Comment by just-simon** [comment]
¿Por qué no los dos?

**Comment by DavidBevi** [comment]
Strongly agree, if I had _give-priority_ points I'd spend them here (ITA layout)

**Comment by abb128** [comment]
This will be fixed in the next update, and there will be settings for customizing layout of long press keys
