### ISSUE TITLE
[enhancement] Delete words after a delay of key press of backspace. [Backspace] [Delete Key] 

### ISSUE THREAD

**Issue by iamlrk** [futo-org/android-keyboard#180]
I felt something was amiss when I was deleting letters, couldn't pin point it exactly. So I went back to Swift keyboard that I usually use and realized it was that when long pressing it deletes the entire word at once with a vibration at the end or deletion. 

This could potentially be a toggle as I do see the current one being useful in some instances.

**Comment by luigge** [comment]
I agree. I kinda prefere it since it feels faster to delete a single word than just swiping left and moving it to the place, although perhaps it's just a matter of time and getting used to it.

**Comment by Softwaerewolf** [comment]
Deleting words is definitely preferable, it's super important when you need to delete a lot of text at once, and accurately.

**Comment by remreren** [comment]
I agree. When deleting something, I expect to see word deletion behavior with a vibration feedback.

**Comment by razzeee** [comment]
This should probably reference the delete or backspace key in the issue. Otherwise it won't be searchable.

**Comment by FetchFast** [comment]
+1 for this. Swiping the delete key is useful, but this is more useful when you have a lot of text to delete.

**Comment by abb128** [comment]
An option for this will be included in the next release
