### ISSUE TITLE
Suggestion Bar Displays Duplicate Suggestions

### ISSUE THREAD

**Issue by kjkrum** [futo-org/android-keyboard#181]
The suggestion bar often displays the same suggestion twice. When this issue combines with issue #134, 2 of the 3 opportunities to correct the word are wasted. This makes the already-poor swipe word recognition even more frustrating. I'm unable to provide a screenshot because the keyboard is hidden when taking a screenshot.

**Comment by dean-futo** [comment]
Consolidated into #672

**Comment by dean-futo** [comment]
Duplicate of #351 - merging this issue into that one. See #351 for details.
