### ISSUE TITLE
Horizontal resizing

### ISSUE THREAD

**Issue by rexendevar** [futo-org/android-keyboard#184]
Basically what the title says. I was able to make the keyboard lower but not narrower, which makes everything harder to type as I'm not used to it.

**Comment by rexendevar** [comment]
Ideally, I'm looking for basically the exact same feature set that Gboard has in this respect.

**Comment by jameshgolen** [comment]
Yeah, this or one handed mode. I'm all in when it gets that.

**Comment by abb128** [comment]
Horizontal resizing and one-handed mode has been implemented in nightly and it will be part of the next release
