### ISSUE TITLE
Context-Sensitive Swipe Type

### ISSUE THREAD

**Issue by rexendevar** [futo-org/android-keyboard#185]
Another part of my difficulties with the FUTO keyboard's swipe type feature is its seeming inability to glean any information from textual context. It will select any word based on pure orthography and put absolute gibberish in the middle of every sentence because it thinks I typed  "SSN" when I actually typed "an". Which, yeah, I guess it might be my fault for messing up which letters I'm pressing, but you can be smarter than that and fix it - Gboard does.

On the other hand, the voice input is extremely functional and probably the best that I've actually used. Thank you for that.

**Comment by dean-futo** [comment]
Consolidated into #665
