### ISSUE TITLE
Import Custom Layouts

### ISSUE THREAD

**Issue by gmankab** [futo-org/android-keyboard#186]
hello, i use colemak to type in english, and custom cyrillic layout based on rulemak to type in cyrillic languages (russian, ukrainian, and belarussian)

here it is:

```txt
я
ж
ф
п
г ґ
й ї
л
у ў
ы
ю
ш щ

а
р
с
т
д
ч
н
е ё
и і	
о ь ъ
э є

з
х
ц
в
б
к
м
```

in heliboard you can import this txt file and get this layout:

![Screenshot_20240705-035818_1](https://github.com/futo-org/android-keyboard/assets/73340745/cdcd8670-306a-47a6-9a3b-7889a6415752)

can you please add same import feature in futo keyboard

**Comment by Lorthiz** [comment]
I second that. In polish we have a lot of diacritics and current layout displays them as last option, it would be great to either hide default secondary symbols from "QWERTY" layout or customize and import our own. I personaly would like the second option.

**Comment by I-Dude** [comment]
I would very much appreciate a feature like this as I like to use the English phonetic equivalent layout for other languages (Russian).

**Comment by dean-futo** [comment]
In the latest release we have improved the layout system, which you can read about here: https://github.com/futo-org/android-keyboard/releases/tag/0.1.24

If you're desired layout isn't already included in the keyboard, you're welcome to create and import a custom one using a yaml file: https://github.com/futo-org/futo-keyboard-layouts
