### ISSUE TITLE
Spaces inserted incorrectly after cursor control

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#190]
The space added after a word that is placed/corrected by the text suggestions is placed incorrectly if you move the cursor with the space bar.

https://github.com/futo-org/android-keyboard/assets/157768191/3e53abe6-d1ad-40fa-8164-ccb4e1f67720

**Comment by KaKi87** [comment]
Hi @abb128, any news on this ? Thanks 🙏

**Comment by KaKi87** [comment]
Hi,
I installed the nightly version to get this fixed, and noticed key borders for the number rows are gone ?
Thanks

**Comment by abb128** [comment]
@KaKi87 The design was updated to give more visual importance to letters over the number row which is now also slightly shorter, you can open a new issue if you have negative feedback on this

**Comment by KaKi87** [comment]
[Done](https://github.com/futo-org/android-keyboard/issues/627).

Also, how do I disable the automated space after inputting a special character ? 

Thanks

**Comment by KaKi87** [comment]
And turns out the keyboard layout made the `€` symbol even more difficult to access despite #513.
This is unbearable, I had to downgrade.
