### ISSUE TITLE
[Feature Request] Haptic Feedback Toggle

### ISSUE THREAD

**Issue by Hitu1197** [futo-org/android-keyboard#195]
Add a toggle to switch to haptic feedback as per system settings. It provides a lot better vibration feeling while typing in comparision to the default vibration engine which can feel werid from time to time.

**Comment by Hitu1197** [comment]
Bump

**Comment by NicoWeio** [comment]
It looks to me like setting haptic feedback to _default_ in the FUTO keyboard should actually make it match the system default.
https://github.com/futo-org/android-keyboard/blob/f7d3601458231f4cf560a58eecd16151b985ac9b/java/src/org/futo/inputmethod/latin/AudioAndHapticFeedbackManager.java#L119-L123

**Comment by Hitu1197** [comment]
Oh wow setting vibration to default does match the system haptic feedback. Thank you! I wasn't aware of this.
