### ISSUE TITLE
CAPS LOCK at start of typing.

### ISSUE THREAD

**Issue by DevLoap** [futo-org/android-keyboard#197]
Whenever I want to type into a new text field, 70% of the time I'm greeted with caps lock enabled and have to delete the first few words. Pushing the shift key once sets it to the next letter to be capital, but then back to lowercase.

**Comment by FilippoULIVO** [comment]
You can change this setting if you go to typing preferences/automatic capslock and disabling the feature

**Comment by DevLoap** [comment]
> You can change this setting if you go to typing preferences/automatic capslock and disabling the feature

Yes, but this is not what the issue is. 

Expected: "He had a good day."

Bug: "HE HAD A GOOD DAY."

It doesn't switch to lowercase after the first letter. It gets stuck on.

It doesn't happen every time, either. It appears to be extremely random.

**Comment by The-Quantum-Alpha** [comment]
I have the same experience.

**Comment by FilippoULIVO** [comment]
Ok,I haven't experienced this but now it's clear.
 maybe include the version,i'm sure it can help

**Comment by picklelfong** [comment]
> > You can change this setting if you go to typing preferences/automatic capslock and disabling the feature
> 
> Yes, but this is not what the issue is. 
> 
> Expected: "He had a good day."
> 
> Bug: "HE HAD A GOOD DAY."
> 
> It doesn't switch to lowercase after the first letter. It gets stuck on.
> 
> It doesn't happen every time, either. It appears to be extremely random.
> 
> Edit: Just happened again and I noticed the shift key wasn't even highlighted, like it would be if you were to double-tap the shift key.
> 
> Pixel 6a AP31.240517.031 | v0.1.22

Happens with mine too. Very annoying.

**Comment by davesousa** [comment]
Same issue on my end.

**Comment by abb128** [comment]
This bug will be fixed in the next release
