### ISSUE TITLE
[Feature Request] Clipboard History 

### ISSUE THREAD

**Issue by RbY-Rj** [futo-org/android-keyboard#198]
Need multiple clipboard history with pin options like gboard....

**Comment by BlackUdon** [comment]
Unless there's more information, that's already implemented.

> Need multiple clipboard history with pin options like gboard....

**Comment by amcarro3** [comment]
I also would like this feature but I only have the option to paste the last copied text. Gboad has the ability to see a list/ kabahn of previously copied items and select one

**Comment by BlackUdon** [comment]
Maybe the clipboard history should be moved to the right.

**Comment by The-Quantum-Alpha** [comment]
> that's already implemented.

There is a clipboard button in the toolbar, but tapping it just paste the last copied text.

**Comment by RbY-Rj** [comment]
Ook bro

**Comment by The-Quantum-Alpha** [comment]
I stand corrected, [there are two buttons](https://github.com/futo-org/android-keyboard/issues/155)

There should indeed be a single button.

**Comment by abb128** [comment]
Closing as this already exists and was made more visible in 0.1.23
