### ISSUE TITLE
Symbols Missing in Dvorak Layout

### ISSUE THREAD

**Issue by Cerxi** [futo-org/android-keyboard#200]
The QWERTY layout is replete with symbols on every letter, brackets and punctuation and asterisks and all sorts of characters. And yet when I swap to Dvorak, it literally all disappears. Why? Surely that's not necessary? It doesn't disappear on G board or swiftkey. I don't understand any reason why the symbols shouldn't stay exactly where they were on the exact same keys.
The only exception should be punctuation, which should follow the period. Ironically, enough, that is the only set of symbols that _does_ stay on the same key.

Compare QWERTY's symbols
![Screenshot_20240705-063936](https://github.com/futo-org/android-keyboard/assets/1817514/38b493e2-b4d2-4fd0-b22e-56d3d65a3088)

To Dvorak's
![Screenshot_20240705-063817](https://github.com/futo-org/android-keyboard/assets/1817514/c2e84b2a-12d5-481d-8e27-425b6a79d173)

**Comment by subcan** [comment]
@Cerxi super funny... I just joined Discord so I could find out how to show symbols... Once I had them enabled... exact sentiments...
This is what I consider a standard dvorak layout... would be nice to see this in an update.
![Screenshot_20240705-122053](https://github.com/futo-org/android-keyboard/assets/637090/e875c2b9-7854-40b1-abe6-422c7437191c)

**Comment by abb128** [comment]
This was fixed in nightly as part of the layout system rewrite
