### ISSUE TITLE
Swipe Typing Disabled with Word Suggestion Off

### ISSUE THREAD

**Issue by ShalokShalom** [futo-org/android-keyboard#206]
Hi there :)

When I disable "word suggestion" in the predictive text settings category, swipe typing is disabled entirely. 

I am not able to change the language of the interface, nor do I guess what original translation is, so I include a screenshot of what I believe is meant.

![Screenshot_2024-07-06-10-45-22-451_org futo inputmethod latin playstore-edit](https://github.com/futo-org/android-keyboard/assets/6344099/6ea7945a-b545-450a-b316-945c05251694)

I would also value, to be able to disable the underline, that appears below the current word, with this setting on.

It is distracting in some instances, as some apps like SimpleX paint it with a bright color.

I could open a separate issue for that, if its needed.

(That was the original motive, why I disabled that setting)

**Comment by dean-futo** [comment]
Consolidated into #665
