### ISSUE TITLE
Enabling "trackpad"/"swipe" for spacebar

### ISSUE THREAD

**Issue by Nightad** [futo-org/android-keyboard#207]
As a previous iPhone/iOS user, I really really enjoy the possibility to navigate around the text using a swipe in the spacebar.
I actually use OpenBoard that is one of the few FOSS app that allow this kind of action.
I would like an option to enabling the possibility to swipe right or left in the the spacebar to move the cursor right/left inside the text.

Thank you.

**Comment by DavidBevi** [comment]
With FUTO you just swipe over the spacebar without having to hold it first. This already moves the cursor.

I believe it's inherited from the vanilla keyboard of AOSP.

**Comment by Nightad** [comment]
> With FUTO you just swipe over the spacebar without having to hold it first. This already moves the cursor.
> 
> I believe it's inherited from the vanilla keyboard of AOSP.

Thanks, I probably had a bug: re-installing solved it!
