### ISSUE TITLE
Clipboard History not Working - Am I doing it wrong?

### ISSUE THREAD

**Issue by Rhubarb-Tau** [futo-org/android-keyboard#209]
Clipboard History does not seem to function.  

V0.1.22-playstore, There's a "Clipboard History" option in "Typing Preferences", but with it enabled, the (Clipboard) action icon in the suggestion bar still only pastes the single most recent item in the clipboard, no menu pops up showing clipboard history or allows items to be pinned.

I'm a new user, so maybe I'm doing it wrong, but I've tried a few things, still can't seem to access clipboard history. Long press on the clipboard icon vibrates, but otherwise does nothing. I've tried reinstalling the app from the Playstore, restarting my phone, and looking for other or duplicate clipboard icons, and I've come up empty.

If it makes a difference, phone is a Pixel 7 Pro running Android 14 Build AP2A.240605.024

**Comment by Rhubarb-Tau** [comment]
I see in the comments for issue 198 user BlackUdon posted a screenshot showing two clipboard action icons, but I only see one.

![Screenshot_20240706-130608](https://github.com/futo-org/android-keyboard/assets/174838288/f6073de5-6dfb-4f78-92ae-65d4448cbc1f)
![Screenshot_20240706-130634](https://github.com/futo-org/android-keyboard/assets/174838288/ab7d1d89-90db-4044-a5ff-76c1d960144e)

**Comment by abb128** [comment]
The expanded action bar is scrollable and there's more items if you scroll

**Comment by Rhubarb-Tau** [comment]
Got it, thanks, solved! 

I noticed that payment isn't supported on this build. I like Futo Keyboard and the larger Futo project, but I don't see a way to contribute. Any options I haven't found?

Thank You!
