### ISSUE TITLE
Add an easier language switch method

### ISSUE THREAD

**Issue by CattoFace** [futo-org/android-keyboard#210]
I believe there must be a quicker method to change between languages than available in the current futo keyboard.
As far as I can tell, in futo your 2 options are:
- long press space bar, menu opens, click language
- open the general menu on the top bar, scroll to the language button, click it.

Other keyboards usually offer at least one of 2 methods:
- language button toggle left of the spacebar
- swiping on the spacebar to change languages(often shadowed by text scrolling when enabled)

Personally I prefer the former but both are acceptable, the current methods are a deal breaker in my opinion.

**Comment by ryankupk** [comment]
+1, hold/swipe on the keyboard is also used for moving the cursor, and the language switch window pops up all the time when I try to do that.

**Comment by 00Martin** [comment]
+1
I switch between 9 languages pretty much constantly during the day, there's a little delay every time you use the space bar to switch language, it adds up and becomes frustating.
For me the language button on the left of the space bar is the way to go.

**Comment by marvhus** [comment]
+1  
  
I switch between a few languages on my keyboard regularly, and I frequently use the spacebar to move the cursor, but when I switched over to this keyboard, I began to frequently have the language switching thing open when I just wanted to move the cursor.  
  
(I literally had the language switching thing open several times while I was writing this when I was fixing some typos.)

**Comment by abb128** [comment]
@marvhus FYI you can increase the long-press delay if it's too short for you

**Comment by a-straight-white-male** [comment]
+1

Literally can't live without two languages. Left a Google Play review with the same request. Please add!

**Comment by IM-83** [comment]
+1

I just login here for this issue please add it asap!!, I prefer swiping on spacebar to change languages but...
It's better to give both options and ppl can choose

**Comment by TeoMorabito** [comment]
gboard has the option of using multiple languages at the same time
I hope this can be added here 🙏

**Comment by ShaddaiSchelin** [comment]
+1
Hear, hear!

**Comment by Jool402** [comment]
Here is a trick that I just learned: I hold the spacebar key on the FUTO keyboard to switch to a different language quickly.

**Comment by razzeee** [comment]
> Here is a trick that I just learned: I hold the spacebar key on the FUTO keyboard to switch to a different language quickly.

That's already mentioned in the initial post

**Comment by abb128** [comment]
The option to add a language switch key, as well as the option to configure swiping spacebar to switch languages, will be included in the next release
