### ISSUE TITLE
Rename "Theme" to "Appearance" and Reorganize Options

### ISSUE THREAD

**Issue by 00Martin** [futo-org/android-keyboard#212]
I've seen height adjustements mentioned already, but not in the following way.

Many keyboards offer the ability to make the keyboard "taller", which makes the keys bigger as well.
Preferably the size would be freely adjustable up to a limit, instead of a few pre-configured sizes.

Edit: Cut the post to make it smaller, my suggestion is in the comments.

**Comment by 00Martin** [comment]
Okay nevermind, I found the controls.
I'm gonna leave the issue opened because in my opinion it's not intuitive that it's all the way at the buttom of the "theme" section.
My suggestion would be to rename "Theme" to "Appearance", and inside "Appearance", have another section which would be called "Themes" for only the coloring, and if we go back in appearance, we also have the other options.

**Comment by 00Martin** [comment]
I'm adjusting the title of the issue.

**Comment by dean-futo** [comment]
@00Martin thanks for your request but we're going to leave it as Theme to keep things simple.
