### ISSUE TITLE
emoji button when holding search sometimes displays in a wrong place

### ISSUE THREAD

**Issue by vmkxyz** [futo-org/android-keyboard#213]
i've noticed that this happens usually after the keyboard crashes but sometimes it happens on random

the emoji key appearing in a wrong place:

![Screenshot_20240707-083254_FUTO Keyboard.jpg](https://github.com/futo-org/android-keyboard/assets/142111166/8e78ab5f-1cfc-40c3-ab81-79411b5fdb7f)

it appearing in the correct place (expected):

![Screenshot_20240707-083424_DeepL.jpg](https://github.com/futo-org/android-keyboard/assets/142111166/369f0d4c-a31b-44c0-a8cc-e298cc4c92ce)

((the differend themes are there cuz i used the dev change theme tile which crashes the keyboard when pressed repeatedly idk if thats known about))

**Comment by vmkxyz** [comment]
samsung galaxy A20e
android 11
oneui 3.1

futo keyboard 0.1.22

**Comment by abb128** [comment]
This should be fixed in the next release
