### ISSUE TITLE
Emoji kitchen for keybord

### ISSUE THREAD

**Issue by Carlos-lab-pixel** [futo-org/android-keyboard#214]
Add the Emoji kitchen function from Gboard

**Comment by deviantsemicolon** [comment]
I don't think this is a necessary feature to have tbh. Maybe as a plugin?

**Comment by Carlos-lab-pixel** [comment]
Yeah

Jay ***@***.***> schrieb am Do., 11. Juli 2024, 05:00:

**Comment by AntsyBoi** [comment]
Thid would require futo to add network support as gboard calls a google API for that feature. Not even having the network permission is one of the big features of the futo keyboard and losing that to add a google api that almost definitely tracks you wouldnt be worth it. Seriously comprimises on the privacy of the keyboard for a little feature. You could try having the FUTO keyboard and gboard installed and swapping to gboard when you want to use emoji kitchen and back to the FUTO keyboard for all other typing.

**Comment by Carlos-lab-pixel** [comment]
Okay thanks, it was just an idea

AntsyBoi ***@***.***> schrieb am Fr., 19. Juli 2024, 06:03:

**Comment by abb128** [comment]
Emoji Kitchen would require network access. It may be possible to scrape all emoji combinations and include all of them locally, but I couldn't find any information for the license of Emoji Kitchen emojis
