### ISSUE TITLE
Dictionary importing not working

### ISSUE THREAD

**Issue by breadbrowser** [futo-org/android-keyboard#217]
Am I doing something wrong? Because I am pretty confident I am doing it right.

https://github.com/futo-org/android-keyboard/assets/64813014/e57876ea-f8de-4060-81d5-a0635951510d

**Comment by Lorthiz** [comment]
https://github.com/futo-org/android-keyboard/issues/126

**Comment by breadbrowser** [comment]
> #126
it needs to be in .dict format
 https://github.com/NoerNova/aosp-dictionary-tools
