### ISSUE TITLE
More consistent diactrical characters locations in different languages

### ISSUE THREAD

**Issue by DanielChydz** [futo-org/android-keyboard#221]
Hi. I've been enjoying the keyboard so far, but there are 2 issues that make it annoying. The 1st one is overwhelming size of key popups, but I see it's already been mentioned in #75. The 2nd one is inconsistent diactrical characters for my language (Polish). It kind of relates to #135. I don't exactly know what would be the solution for the problem, but I can see it appear in other languages, not only Polish and German.

On a side note, it would be nice if long press and swipe to choose special/diactrical character wouldn't exit the selection popup if you swiped too far. A switch for this in settings would be nice.

Example of the issue is shown below. The diactrical characters are in different places - some on the left, some in the middle, some on the right.
<img src="https://github.com/futo-org/android-keyboard/assets/83183534/f760b4d7-8c6c-44e2-9061-001d87b73da8" width="20%" />
<img src="https://github.com/futo-org/android-keyboard/assets/83183534/bd8e502a-5be2-49d1-a035-fcc877466b7d" width="20%" />
<img src="https://github.com/futo-org/android-keyboard/assets/83183534/63d0eb33-b2c7-430f-b918-fa9b30a3de64" width="20%" />

**Comment by abb128** [comment]
This should be fixed in 0.1.23.2, there's also a new setting if you want to remove symbols or irrelevant letters
