### ISSUE TITLE
Feature Request: alt long press on keys

### ISSUE THREAD

**Issue by devonvos** [futo-org/android-keyboard#222]
It would be nice if we could enabling showing the alternate input from long pressing on the keys. It's a small thing but a huge quality of life improvement for new users who are still learning the keyboard (like myself atm)

**Comment by MRDGH2821** [comment]
Do you mean this?
![Screenshot_20240709-134843.png](https://github.com/futo-org/android-keyboard/assets/46621001/9c17352c-c4f5-46b5-bb2c-383ba195b5d2)

**Comment by devonvos** [comment]
That is definitely it, why is it hidden in the themes menu??

**Comment by abb128** [comment]
It'll be in a more sensible spot in the next version
