### ISSUE TITLE
[Feature Request] Please Implement Direct Boot support ASAP

### ISSUE THREAD

**Issue by TheYoungerSes** [futo-org/android-keyboard#223]
I was originally going to post this as an error report; but Futo Keyboard Discord managed to salvage my situation. Here are the details:

_Phone_: Moto G Power (2020)
_Keyboards enabled_: only Futo Keyboard.

I am fully behind Futo's mission, and for that trust; I had disabled all other keyboards on my phone. Unfortunate circumstance; My phone ran out of power; I got kicked to the lock screen, unable to interact with my password input field.

**A work around was found**, connect a physical keyboard to the phone, and use that as the input device. I luckily had a USB C to USB C cable with me from a Samsung charger wall wort; that was able to transmit data, not just power. 

So for all the people who are locked out of your phones, connect a keyboard, hopefully you have a way to connect/convert from your keyboard's output to your phone's port.

For the Developers; Please use this to track the development of Direct boot usage of Futo Keyboard; sure just a password is only one data point for Google, but it is still one datapoint too many for my taste.

**Comment by abb128** [comment]
Direct boot support has been prioritized and will be added in the next version to avoid people being locked out as you were
