### ISSUE TITLE
[Feature Request] Show Number Row When Typing Password

### ISSUE THREAD

**Issue by Windowsxd** [futo-org/android-keyboard#224]
Samsung keyboard and Gboard both show the number row whenever you are typing a password. This makes it more convenient to type a long password riddled with more than just letters.

**Comment by donpatzone** [comment]
That option already exists under Typing Preferences

**Comment by abb128** [comment]
This will be done in the next release

**Comment by haldi4803** [comment]
It is done! But not perfectly... Will open New issue.
Thank you verry much for implementing. Love it!
