### ISSUE TITLE
[Feature Request] Multilingual Keyboard

### ISSUE THREAD

**Issue by MiaSelene** [futo-org/android-keyboard#226]
It would be nice if I could select two languages at once for text prediction, because switching languages every time is a little clunky

**Comment by The-Quantum-Alpha** [comment]
As a bilingual man, I agree!

**Comment by blackfyre** [comment]
I'm also in favor!

**Comment by fdmarcin** [comment]
This is something I depend on a lot 🙏

**Comment by FetchFast** [comment]
At least a dedicated lang switch key would be a start

**Comment by tinsukE** [comment]
Seems like a duplicate of https://github.com/futo-org/android-keyboard/issues/38

I also suggest adding a 👍 to the issue, instead of posting a comment, that would provide easier visibility on community support to an improvement. Unless you're be bringing new information/considerations, of course.

**Comment by MiaSelene** [comment]
@tinsukE is right this is a duplicate , thanks for the heads up
