### ISSUE TITLE
Futo crashes after selecting as the default keyboard

### ISSUE THREAD

**Issue by DemonKingSwarn** [futo-org/android-keyboard#228]
So after I set futo as my default keyboard, it crashed. Leaving me with no keyboard. I got this issue on Android 14 (Vivo I2201).

The video below shows the exact thing

https://github.com/futo-org/android-keyboard/assets/69480361/b0ca6d86-7b96-43ba-8b9d-a1b92cd04b3d

**Comment by abb128** [comment]
Did you send a crash report with the popup that appeared?

**Comment by DemonKingSwarn** [comment]
well yes

**Comment by hakarune** [comment]
I reported similar issue a while ago. Instead of crashing fully it just randomly freezes after seeing as default and no keyboard comes up until you force quit it then it works until you stop using it.

**Comment by hakarune** [comment]
#3

**Comment by DemonKingSwarn** [comment]
turns out it was happening because i have uninstalled the userdictionary. i re-installed it using adb and now it works fine.
