### ISSUE TITLE
Keyboard crashes when using Nordic keyboard

### ISSUE THREAD

**Issue by ernax78** [futo-org/android-keyboard#229]
When selecting "Swedish" as language and typing, the Futo keyboard crashes after a few words. It works perfectly fine with English.

It is irrelevant if dictionary / language model is loaded or not.

Version: 0.1.22 from FDROID

Sent a crash report to keyboard@futo.org on 1st of July too with full crash log.

![image](https://github.com/futo-org/android-keyboard/assets/65963237/de22d17c-118d-476f-b08c-9700c4b4ce80)

This crashes both on Redmi Note 9 Pro (Miui 14.0.3) and Xiaomi Poco X3 (Miui 14.0.5)

` beginning of main\n07-01 07:00:13.632 W\/LatinIME(25163): Create input view\n07-01 07:00:13.758 I\/LatinIMELegacy(25163): Starting input. Cursor position = 0,0\n07-01 07:00:13.823 D\/DecorView[InputMethod](25163): updateDecorCaptionStatus displayWindowDecor is false\n07-01 07:00:13.844 D\/DecorView[InputMethod](25163): updateDecorCaptionStatus displayWindowDecor is false\n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): QUALCOMM build                   : 820d4a4028, I5580630f49\n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Build Date                       : 11\/04\/21\n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): OpenGL ES Shader Compiler Version: EV031.32.02.16\n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Local Branch                     : \n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Remote Branch                    : \n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Remote Branch                    : \n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Reconstruct Branch               : \n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Build Config                     : S P 10.0.7 AArch64\n07-01 07:00:13.847 I\/AdrenoGLES-0(25163): Driver Path                      : \/vendor\/lib64\/egl\/libGLESv2_adreno.so\n07-01 07:00:13.857 I\/AdrenoGLES-0(25163): PFP: 0x016ee190, ME: 0x00000000\n07-01 07:00:13.893 D\/hw-ProcessState(25163): Binder ioctl to enable oneway spam detection failed: Invalid argument\n07-01 07:00:13.955 E\/putmethod.lati(25163): open libmigui.so failed! dlopen - dlopen failed: library \"libmigui.so\" not found\n07-01 07:00:13.980 D\/LanguageModelFacilitator(25163): Calling closeInternalLocked on model due to seeming locale change\n07-01 07:00:13.982 D\/LanguageModelFacilitator(25163): no model for sv\n07-01 07:00:14.441 E\/RichInputConnection(25163): Unable to connect to the editor to retrieve text.\n07-01 07:00:14.441 D\/RichInputConnection(25163): Will try to retrieve text later.\n07-01 07:00:14.442 E\/RichInputConnection(25163): Unable to connect to the editor to retrieve text.\n07-01 07:00:14.442 W\/RichInputConnection(25163): Unable to connect to the editor. Setting caps mode without knowing text.\n07-01 07:00:14.445 D\/DecorView[InputMethod](25163): updateDecorCaptionStatus displayWindowDecor is false\n07-01 07:00:14.553 D\/AndroidRuntime(25163): Shutting down VM\n07-01 07:00:14.565 E\/AndroidRuntime(25163): FATAL EXCEPTION: main\n07-01 07:00:14.565 E\/AndroidRuntime(25163): Process: org.futo.inputmethod.latin, PID: 25163\n07-01 07:00:14.565 E\/AndroidRuntime(25163): java.lang.RuntimeException: Callbacks must add text or a content description in populateNodeForVirtualViewId()\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat androidx.customview.widget.ExploreByTouchHelper.createNodeForChild(SourceFile:58)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat androidx.customview.widget.ExploreByTouchHelper.obtainAccessibilityNodeInfo(SourceFile:75)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat androidx.customview.widget.ExploreByTouchHelper$MyNodeProvider.createAccessibilityNodeInfo(SourceFile:3)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat androidx.core.view.accessibility.AccessibilityNodeProviderCompat$AccessibilityNodeProviderApi16.createAccessibilityNodeInfo(SourceFile:2351)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1472)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1193)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:368)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:74)\n07-01 07:00:14.565 E\/AndroidRuntime(25163): \tat android.view.`

**Comment by abb128** [comment]
This will be fixed in the next release
