### ISSUE TITLE
[Feature Request] More symbols in blank spaces

### ISSUE THREAD

**Issue by MRDGH2821** [futo-org/android-keyboard#236]
When I switch to symbols tab, I see a huge blank space:
![Screenshot_20240709-135230.png](https://github.com/futo-org/android-keyboard/assets/46621001/077573bf-96e9-44ab-b515-8ca75a48d382)

![Screenshot_20240709-135238.png](https://github.com/futo-org/android-keyboard/assets/46621001/73502614-42cd-4b4c-aac2-b69ca53d6a26)

Although I have all keys I need to use, it would be nice if that blank unused space can instead show more keys, thus reducing the need for long pressing keys.

**Comment by MRDGH2821** [comment]
> Mabe they can add a dynamic sizing for keys so they increase in size to cover the distance up like in gboard.
> 
> Gboard character height size normally: ![Screenshot_2024-07-09-15-11-05-97_d365b52accad0f47adbc08c16219827d](https://private-user-images.githubusercontent.com/87696847/346906650-f516a503-506f-47f0-a578-6598a94b8689.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjIxNDQsIm5iZiI6MTcyMDUyMTg0NCwicGF0aCI6Ii84NzY5Njg0Ny8zNDY5MDY2NTAtZjUxNmE1MDMtNTA2Zi00N2YwLWE1NzgtNjU5OGE5NGI4Njg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwNDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMGM0MTUyNzJjMmE3OTMyMjRmZGZmZjE4M2YzODNiZTM5MzdjNjA3MTU2YTgwOWZkNTkxYTU1YjkyYjIyYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJFBZkPHgueY6q56-gLTBw5_FoyPIxUYkQ7QZkK_od8) Gboard character height size when there are only 2 rows instead of the usual 3: ![Screenshot_2024-07-09-15-10-52-72_d365b52accad0f47adbc08c16219827d](https://private-user-images.githubusercontent.com/87696847/346907485-2bdaf92d-2ff8-4912-af55-d39558d3d313.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjIxNDQsIm5iZiI6MTcyMDUyMTg0NCwicGF0aCI6Ii84NzY5Njg0Ny8zNDY5MDc0ODUtMmJkYWY5MmQtMmZmOC00OTEyLWFmNTUtZDM5NTU4ZDNkMzEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwNDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MzY5NmQ0MWQwN2Y1ZmQwN2IyZGRhZTA3ODk4MTRiMDkwNWQ1YTQ3OTIxYzVlZTczOTcyMzNhZWI2ZDc0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXDr_9wgcke6Ie0bDY3Si8UdH6_qhHJViGR28EZswh8)

Gboard does make the keys look bigger, thus utilising the space, but I'm looking for additional keys to be displayed, so that I don't have to keep long pressing.

I frequently use underscore symbol and my memory muscle was immediately attacked when I had to long press hypen key to get underscore as compared to Gboard

**Comment by abb128** [comment]
More symbols will be shown in the next version
![image](https://github.com/futo-org/android-keyboard/assets/65567823/82810823-5a59-4c71-b2e2-724b8f7f2b7d)
