### ISSUE TITLE
[Bug] Colemak layout has very poor additional keys/symbols support

### ISSUE THREAD

**Issue by big-chungus69420** [futo-org/android-keyboard#239]
Like I'm always having to switch to the numbers tab just to be able to type the single or double quotations mark, it's genuinely unusuable after a certain point.
G board:
![Screenshot_2024-07-09-15-01-31-30_d365b52accad0f47adbc08c16219827d](https://github.com/futo-org/android-keyboard/assets/87696847/4b0c0c43-edad-437a-a8ee-a8811a6be0c7)
Futo KeyBoard:
![Screenshot_2024-07-09-15-02-43-50_d365b52accad0f47adbc08c16219827d](https://github.com/futo-org/android-keyboard/assets/87696847/8cdf19d6-3b3e-446f-8ed0-257b3712cf0c)

**Comment by abb128** [comment]
This will be fixed in the next release
