### ISSUE TITLE
[Suggestion] Futo keyboard shows the keys hidden in the > drop down row by default

### ISSUE THREAD

**Issue by prypyet** [futo-org/android-keyboard#241]
Futo keyboard requires you to type the > key to access things like clipboard, themes etc and shows only word suggestions by default and when typing whereas gboard shows the clipboard, themes etc by default and only when you start typing words does it show the word suggestions. I think the gboard's behaviour is more sensible and should be adopted by futo.

Also why does the futo board have two clipboard keys? Also it would be nice to be able to remove some of these keys like you can do in gboard because i rarely need the emoji or the text editor or the other clipboard button or the debug menu up there in my drop down menu.

**Comment by DavidBevi** [comment]
[They recently announced an enhancement for that feature (and others)](https://github.com/futo-org/android-keyboard/issues/244)
