### ISSUE TITLE
Increase long-press time for space bar select language pop-up

### ISSUE THREAD

**Issue by Goose-Tech** [futo-org/android-keyboard#243]
Currently on v0.1.22, a long-press on the keyboard space bar displays the "select language" popup. The space bar is also used for horizontal scrolling through text. Often while trying to scroll horizontally, the select language popup will display, which is not desired. This may be remedied by increasing the long-press timing to prevent accidentally triggering it. Perhaps something like 2.0 seconds would help reduce an accidental trigger.

**Comment by scrampker** [comment]
A very short term fix I did was to increase global futo kb long press timer. Would love to see this feature as well.

**Comment by The-Quantum-Alpha** [comment]
I like it how it currently is as a multilingual person.

**Comment by scrampker** [comment]
That's fine, but for probably 99% of the users, the cursor would be the priority.  A simple toggle that enables/disables/changes the delay would make sense. Best of both worlds. I can't imagine a slightly-longer delay of a half-second for changing languages would make that big of a difference versus the near-constant struggle of trying to move the cursor -- even for bilingual use.

**Comment by The-Quantum-Alpha** [comment]
I understand your perspective, and a toggle feature to adjust the delay seems like a practical solution. However, I personally have not encountered issues with the space bar long-press interrupting my horizontal scrolling. The current input time seems adequate, even if I try to trigger the language switcher, it still works as intended.

**Comment by FetchFast** [comment]
A quick, dedicated language switch button to cycle languages is pretty important. The emoji key is also available by holding the enter key. 
We could have a dedicated button that you swipe in different directions for different things including setting languages.
I think getting this rapid is better than trying to auto detect languages, which seems like a bigger project?

**Comment by DavidBevi** [comment]
@everybody, FYI it's been announced an update:
- Action bar will be more customizable and will contain more actions
- There will be new secondary actions on a lot of keys, including enter
- There will be a customizable key instead of the emoji/language key (left of spacebar)

**Feedback is encouraged**: [[RFC] Action Bar update #244](https://github.com/futo-org/android-keyboard/issues/244)

**Comment by abb128** [comment]
Long-press time for spacebar will be doubled in the next release
