### ISSUE TITLE
[RFC] Action Bar update

### ISSUE THREAD

**Issue by abb128** [futo-org/android-keyboard#244]
We're working to make the action bar more useful. Currently, there's several issues that harm its usability:
* Can't customize which actions appear
* Many people don't realize you can re-arrange actions by long-pressing and dragging
* Many people don't realize you can scroll in the action bar
* Triggering an action requires 2 taps + scrolling if it's not one of the first
* Can't type easily with the action bar open because it obstructs the suggestions, it can't be open persistently

Some of these are fixable by just adding better settings and indications, but the last two are more fundamental to the current design of the action bar.

We have decided on a new design where the action bar pops out vertically, allowing using the pinned actions with only a single tap. If the extra vertical space is needed, it can be popped back in at any time. A triple dot menu will show non-pinned actions and have an option for configuring which actions to pin.

![image](https://github.com/futo-org/android-keyboard/assets/65567823/dad1b725-2a9c-495d-84b2-414561ea2416)
![image](https://github.com/futo-org/android-keyboard/assets/65567823/fc7aaddd-2495-452c-9b5d-ca434b178b8c)

In addition to this, some common actions will be accessible by long-pressing keys equivalent to shortcuts on a physical keyboard (e.g. ctrl+v pasting). I am aware of the difficulties long-press keys currently present when typing in other languages, so this will be configurable and you'll be able to re-order or disable symbols/actions from long-pressing keys. (the emoji key will also be configurable to a switch language key, or any other action)
![image](https://github.com/futo-org/android-keyboard/assets/65567823/30967fb6-b20a-4557-abca-3a3a3e7edad9)

The enter key will also contain some actions accessible by long-pressing
![image](https://github.com/futo-org/android-keyboard/assets/65567823/57976514-daf1-4276-aaf1-080c97a64ff4)

I'd be interested to hear opinions or comments on this, including:
* How often you use the current action bar, and how you use it
* Whether this change would have a positive or negative effect on your use of the action bar
* What actions you'd like to see added
* Any related feedback

**Comment by MulverineX** [comment]
These changes will be great! Looking forward to it.

**Comment by The-Quantum-Alpha** [comment]
This is great, but I would prefer if there would be an option to keep the current toolbar as is or to have the new option you're featuring above.

**Comment by abb128** [comment]
@issuant You seem to misunderstand, the state of the action bar being visible or not will be persistent, you can just leave it always visible

**Comment by Fuoxden** [comment]
Now this looks cool! I really like it! I cant wait!

**Comment by M123-dev** [comment]
Coming from the Samsung Keyboard I like the way it is there:

- Opening the keyboard: ActionBar
- Start typing: suggestions are shown
- Can go back to the actions at any time using the "<"

-----

Would love the declutter the action bar and
again the Samsung Keyboard has a neat solution, the hidden items are not gone, you can expand the action bar with a 3-dot-menu to see the hidden items.
This expanded page is also used for rearranging, pinning/unpinning to the "main" action bar.

----- 

While testing it for this comment I noticed there isn't even a button to enter the suggestions when the Action Bar is expanded, but never missed it the last few years. This could declutter it a bit more.

**Comment by abb128** [comment]
This is now being rolled out in v0.1.23
