### ISSUE TITLE
Option to remove Action Bar

### ISSUE THREAD

**Issue by sabbaghpierre** [futo-org/android-keyboard#247]
Please provide the option to remove the Action Bar  as some people like me prefer to customize their keyboard to use the least space possible on the screen while still being able to type comfortably.

**Comment by joaovgp** [comment]
I second that! Please let us disable it

**Comment by abb128** [comment]
This will be an option in the next release

**Comment by timur-g** [comment]
Can you please explain how to close Action bar?

**Comment by Zvonimir-FUTO** [comment]
> Can you please explain how to close Action bar?

Probably not what you are looking for but it's related to this issue, in **Keyboard & Typing** settings you can disable **Show action/suggestions** bar.

What you are probably looking for is #1559

**Comment by timur-g** [comment]
Thanks. That removes both suggestions and favorites, and I would like to remove only Favorites. This would better be split to 2 options. That referenced issue has good idea, just it is more complex to make.

**Comment by abb128** [comment]
@timur-g You can press the arrow to the left of suggestions to collapse the actions

**Comment by timur-g** [comment]
Thanks! Should be obvious, but I did not look at that, was searching in Settings and did not figure out.
