### ISSUE TITLE
Auto-Capitalization Not Disabled After First Sentence

### ISSUE THREAD

**Issue by booflesnoof** [futo-org/android-keyboard#252]
i prefer to type in all lowercase, but it always auto-capitalizes the first word of every sentence after the first, despite that option being disabled. this happens on my Samsung Galaxy Note 8 as well as Samsung Galaxy A14 5G, v0.1.22-playstore

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Duplicate of #547 - see that issue for details.
