### ISSUE TITLE
[Question] will futo ever be on ios in the future?

### ISSUE THREAD

**Issue by Fuoxden** [futo-org/android-keyboard#253]
I may not like apple but most of my family use iphones, ipads, and are inside the ecosystem, i am wondering if futo has plans to get onto the app store anytime soon

**Comment by FetchFast** [comment]
This app is based on the android keyboard. It would be a total rewrite, with only the name shared

**Comment by abb128** [comment]
Probably not in the near future. iOS is a lot more complicated to develop for, and just the Android version is already keeping us busy. From my general understanding there's also less of an immediate need for a privacy-friendly iOS keyboard as custom keyboards can be denied internet access - I haven't used iOS or developed for iOS personally though so don't quote me on that
