### ISSUE TITLE
Keyboard Crashes in AIB Bank App on Android

### ISSUE THREAD

**Issue by FUTOJohn** [futo-org/android-keyboard#254]
https://play.google.com/store/apps/details?id=aib.ibank.android

For this bank app, unable to type numbers .Each time, I try to type the keyboard disappears. Eventually crashes. I have installed the alpha version of the keyboard from Play Store.

Phone : Pixel 8Pro
OS : 14 ,July 5th Security patch.

Thanks.

**Comment by dean-futo** [comment]
@FUTOJohn I'm able to type numbers in the AIB app without it crashing. Is this still occurring for you?

**Comment by dean-futo** [comment]
Very similar to #234 - merged this issue into that one.
