### ISSUE TITLE
Split vertical offset setting for vertical/horizontal view

### ISSUE THREAD

**Issue by CaptaiNiveau** [futo-org/android-keyboard#255]
I set the keyboard offset setting at the bottom of the Theme settings to the max value, 50.
It's really useful, since the Pixel 8 is quite long and the keyboard is way too low by default without the nav bar.

However, when I use the keyboard in the horizontal view, the keyboard also gets shifted up. That makes it really awkward to type in that position.

It'd be nice if you could make two separate settings for this, one for the vertical view and one for the horizontal view. 
The same goes for the Keyboard Height setting, though I personally don't use it.
Also, if you're at it, a higher max value for the offset would be nice, too. 50 is enough for me, but 60 might be even nicer.

Thanks, I appreciate this project and also got the license :)

**Comment by abb128** [comment]
Separated portrait/landscape options have been implemented in nightly and it will be part of the next release
