### ISSUE TITLE
accessibility: keyboard crashes when switching to symbols mode with talkback enabled

### ISSUE THREAD

**Issue by techexplorers123** [futo-org/android-keyboard#256]
the keyboard crashes when talkback is running and you switch to symboles mode.
steps to reproduce:
1. tern on talkback.
2. find an edit box and open keyboard.
3. now, switch to symboles mode by pressing the button and try to explor the screen.
4. the talkback will freeze for a sec then a crash report window will popup saying the futo keyboard is crashed.
here is the crash logs [Crash.txt](https://github.com/user-attachments/files/16177519/Crash.txt)

**Comment by abb128** [comment]
This will be fixed in the next release
