### ISSUE TITLE
Accessibility: typing is really buggy and slow with TalkBack.

### ISSUE THREAD

**Issue by techexplorers123** [futo-org/android-keyboard#262]
Tern on TalkBack. Then, try typing with gboard and after that try futo board.
You can see the difference.
Below, attaching a screen capture showing the bug
[Screen capture](https://next.techclub.co.in/s/t5o6sxSftLAK9MP)

**Comment by abb128** [comment]
The link is no longer valid, if this issue still persists could you open a new issue with an attached video and more details? On my device the typing experience seems similar
