### ISSUE TITLE
[Feature request] swipe space to change language 

### ISSUE THREAD

**Issue by jonathan-s** [futo-org/android-keyboard#266]
Long press to change language takes a long time. It would be better with a swipe to space so can cycle between the different languages.

The swiftkey keyboard also has long press where the menu comes up right above the spacebar and you drag the finger to left and right to select the language, which is much better UX than what is currently.

**Comment by TeoMorabito** [comment]
please no
swiping space moves the cursor

gboard has a way to setup the use of multiple languages at the same time
Futo should incorporate something like this
like at least be able to combine 2 languages if not 3 and automatically detect the one in use 🙏

**Comment by jonathan-s** [comment]
@TeoMorabito, if you install microsoft swiftkey and try it out with several languages you'll notice that swiping _does not_ move the cursor.

**Comment by abb128** [comment]
An option for this will be included in the next release. When active, moving the cursor will still be possible by first long pressing, and then swiping
