### ISSUE TITLE
Alphanumeric Inputs Not Corrected

### ISSUE THREAD

**Issue by remreren** [futo-org/android-keyboard#268]
I have my number line activated all the time. When I want to click E letter, I can sometimes click 3 in the number line which is incorrect. The keyboard is not recognizing the alphanumeric inputs as words so it cannot fix.

For example in Turkish there is a common word "ben". When I am writing this word, it becomes into "b3n" and the correction should show "ben".

When I accidentally write "bwn" instead of "ben", it shows correction and automatically corrects the word but when an alphanumeric input is given, it neither fixes nor recognizes the word.

The other examples:
"Yardım":
- "Yaedım", "Yatdım", and  "Yardum"  corrects to "Yardım"
- "Yard6m" and "Ya3dım" *not* corrects to "Yardım"

**Comment by dean-futo** [comment]
Consolidated into #666
