### ISSUE TITLE
Customizable Punctuation Spacing Rules

### ISSUE THREAD

**Issue by BurntVoxel** [futo-org/android-keyboard#273]
Have you ever noticed how each app seems to have different markup rules? And how even if they say they support Markdown, they may have different rules? Hard-coding grammatically correct punctuation rules like sentence-terminating punctuation versus non-terminating punctuation is hard enough. So don't! Allow us to tweak the rules to suit our needs.

I don't know if tweaking the rules per-app is even possible, but adjusting the rules globally is still valuable for users who spend a lot of time typing in a particular style, whether that means a particular markup syntax, or writing code on mobile, or using non-standard punctuation just for the fun of it. Not to mention that it would make developing the punctuation rules themselves simpler, as you could just use the keyboard, spot a bug, tweak the rules, test again, export the rules, and send a pull request.

The Rulebook should be an object containing a list of Contexts, each with a list of Behaviors, each with a blacklist & whitelist pair, both lists of individual symbols. If a symbol is included twice in a row, it should indicate that a sequence of multiple of that symbol is considered a distinct symbol. (Such as `**markdown bold**`). 
Alternatively, maybe make the lists newline-separated lists, so you can use complex symbols, such as `[b]BBCodes[/b]`, or `<!--HTML comments-->`, or informal sentence terminators like ` /s`.

Context suggestions: 
- First symbol on line (like `## Markdown Headings` vs `#hashtags`)
- Start of sentence
- After number, not word (like `3.14` vs `Hello. Hi. `)
- After end of sentence. 
- End of line
- Every-Odd (` "open quote...`)
- Every-Even (`... and close quote" `)

Behavior suggestions: 
- Space Before
- Space After
- Return to alphanum keyboard (yes after quotes, no after numbers and dollar sign...)
- Stop Sentence (capitalize next. `.!?`) 
- *Start* Sentence (like these `- bullet lists`)
- Allow no-caps ( `` if(wrapper == "`"){sentenceType = Code; Rules.requireCaps = False;}``)
- Start Title Case (`# Headings`)
- Enable CamelCase (`#HashtagsCanBeSeveralWordsButStillBeProofread`)

**Comment by dean-futo** [comment]
@BurntVoxel thanks for your detailed request but this is a bit out of the scope of the keyboard.
