### ISSUE TITLE
Unable to Delete/Disable Transformer Model

### ISSUE THREAD

**Issue by GasparAM** [futo-org/android-keyboard#283]
Hello!
The English model interferes with my writing and since there was no way to disable the model I tried deleting it. But as you can see from the attached video file I am unable to do so

https://github.com/user-attachments/assets/a5f435f6-ae83-45f9-aa1e-51a80f1d88b0

**Comment by abb128** [comment]
You can disable Transformer LM in predictive text settings

**Comment by GasparAM** [comment]
yeah but the point is that you can not disable it

**Comment by GasparAM** [comment]
or rather delete it
