### ISSUE TITLE
[Feature Request] Add emoji search bar and consider emoji suggestions

### ISSUE THREAD

**Issue by onyxz7** [futo-org/android-keyboard#285]
Hi 👋
I've been using FUTO Keyboard as a privacy-respecting alternative to GBoard. It's great, but I have two suggestions to improve the emoji experience:

**1. Emoji search bar:** Add a search function when the emoji kitechen is open for quicker emoji finding.
**2. Emoji suggestions in prediction bar:** Consider adding emoji suggestions to the prediction bar.

Those 2 feature are higly inspired by the gboard, and I realy think they would definitely be a most for this already pretty good alpha keyboard 

Thanks for considering!

**Comment by abb128** [comment]
Search is already prepared for the next release, and suggestions should already work in English (e.g. if you type "joy" it should suggest the joy emoji)

**Comment by onyxz7** [comment]
Great 😃👍 
Sorry, because I am french and it was the language used by the keyboard so i didn't notice it.
I am glad that emoji search bar came on next release !
You are realy doing a great job !
