### ISSUE TITLE
Keyboard Frequently Enables Caps Lock Unexpectedly

### ISSUE THREAD

**Issue by 1-NoLimits** [futo-org/android-keyboard#286]
Maybe just me but when I return to any app (eg whatsapp) I noticed the caps lock is on.

Not sure why but ban we get an option to disable this?

**Comment by The-Quantum-Alpha** [comment]
[It will be fixed for the next release](https://github.com/futo-org/android-keyboard/issues/246#issuecomment-2226769694)

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Duplicate of #154 - see that issue for details.
