### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by Whoopalla** [futo-org/android-keyboard#292]
Google has the button left to spacebar. But here it is on action bar. Can I change it some other way? Or move the button?

**Comment by abb128** [comment]
Long-press the spacebar

**Comment by Whoopalla** [comment]
> Long-press the spacebar

Yeah, but it's two presses. And the second one is far from the first

**Comment by abb128** [comment]
In the next version you'll be able to replace emoji key with language key to make it more easy
