### ISSUE TITLE
Auto-Capitalization Doesn't Work After Punctuation and Emoji(s)

### ISSUE THREAD

**Issue by samimaat** [futo-org/android-keyboard#294]
Video, where after a period there should be  automatic capital letters after an emoji, there are only lowercase letters. Auto-cap should also work after multiple emojis.

https://github.com/user-attachments/assets/7a299b1e-2dda-44c2-ad3b-8cdf2443abb1

**Comment by samimaat** [comment]
I noticed that this also applies to other kinds of symbols as well. Such as - @ , and so on. Maybe not every symbol should be ignored, but I didn't go into too much detail on this.

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Merged into #601 due to close similarity - see that issue for details.
