### ISSUE TITLE
Autocorrect Replaces 'Knob' with 'Innovation'

### ISSUE THREAD

**Issue by wycre** [futo-org/android-keyboard#300]
When typing the phrase 'its the knob' the word 'knob' will be replaced with 'innovation'. 
![Screenshot_20240717-095226](https://github.com/user-attachments/assets/55fb8946-3929-4ab2-b003-3b4553147f0b)

This won't happen when typing in just the word 'knob', it has to have words before it.

It knows that 'knob' is a real word as it is one of the 3 completion options. Adding 'knob' to my personal dictionary solves this problem, but only for this word. FUTO keyboard might hallucinate other corrections, but it would be very hard to find them.

**Comment by wycre** [comment]
Just tried other combinations:
- 'the knob' corrects to 'the innovation'
- 'the knobs' corrects to 'the knives'
- 'a knob' corrects to 'a knife'
- 'your knob' corrects to 'your knives'
- 'your knobs' corrects to 'your knives'
- 'our knob' corrects to 'our innovation'
- 'out knobs' corrects to 'our knives'
- `some knobs' corrects to 'some knives'
- 'more knobs' & 'more knob' does not autocorrect
- 'we have got knob' corrects to 'we have got innocent'
- 'we have got knobs' corrects to 'we have got knives' 
- "we've got knobs" corrects to "we've got knives"
- "we've got knob" does not autocorrect but "got knob" is underlined after pressing space

**Comment by supermarble94** [comment]
this could be due to the offensive words filter, as knob is slang for penis.

**Comment by dean-futo** [comment]
Consolidated into #666
