### ISSUE TITLE
[Feature request] Floating keyboard support

### ISSUE THREAD

**Issue by djismgaming** [futo-org/android-keyboard#301]
## Floating keyboard support

It would be great to have a floating keyboard option. If this floating keyboard could be resized by the user, during use, even better!

**Comment by d-avery** [comment]
This is also important to me. On small screens, in landscape mode, the keyboard opens in full size, taking up 70%+ of the screen real estate. It would be nice to have a floating landscape keyboard feature, similar to how gboard handles it. Movable, resizable.

**Comment by abb128** [comment]
Floating mode has been implemented in nightly and it will be part of the next release
