### ISSUE TITLE
[Feature] Option to hide action bar

### ISSUE THREAD

**Issue by ChrisgammaDE** [futo-org/android-keyboard#303]
I'm a very simple user. I don't need autocorrect, speech input or anything else the action bar offers. I just want my keys.

I would love to have a setting to hide the action bar, because with everything disabled it's just a waste of realestate.

As an example, this is how GBoard looks, when everything is disabled:

![Light comparison](https://github.com/user-attachments/assets/5a25d234-4c23-486c-a905-3f5193ddbe39)

**Comment by abb128** [comment]
An option for this will be added in the next release
