### ISSUE TITLE
Auto Capitalize Behavior Erratic After App Switching

### ISSUE THREAD

**Issue by AtmosphericHaze** [futo-org/android-keyboard#304]
Option to start each sentence with upper case sometimes doesn't change to lower case and keeps writing in uppercase. It happens mainly after sending a message on one communicator and switching to another one. 
Phone is Xiaomi 12 Global. 
App Version 0.1.22-playstore
https://github.com/user-attachments/assets/cb92b3f7-7e9a-43a8-91f4-03dfe38c6fcf

**Comment by thesmart1** [comment]
I experience the same issue. Caps lock remains on until all text is deleted and input is restarted.

**Comment by axel-kah** [comment]
duplicate of #246

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Merged into #601 due to close similarity - see that issue for details.
