### ISSUE TITLE
Space Bar Causes Lag in WhatsApp

### ISSUE THREAD

**Issue by jow-i** [futo-org/android-keyboard#306]
Experiencing a close to 2s lag after pressing the space bar. Only happens when using whatsapp and occasionally on github.

**Comment by Juampy-R** [comment]
Hey there, i was having the same problem. If you deactivate the Transformer LM option on Predictive Text, the problem goes off, hope it helps you.

**Comment by jow-i** [comment]
Thanks a lot. This solved the issue.

**Comment by dean-futo** [comment]
Consolidated into #673
