### ISSUE TITLE
FUTO keyboard keeps stopping

### ISSUE THREAD

**Issue by mfrimann** [futo-org/android-keyboard#308]
I constantly get this message and I need to restart the keyboard. I'm running the latest version on a S23.

**Comment by SdoggaMan** [comment]
FWIW, I'm getting this whenever the numberpad keyboard is in use - it's completely unusable, it always crashes almost immediately. The regular QWERTY keyboard is rock solid as far as crashes go, but the numpad always crashes. 

Android 13 - Moto Edge 30 Pro - Version 0.1.220playstore, code 10804

**Comment by abb128** [comment]
If this persists, please open a new issue with more details like a captured bug report if possible
