### ISSUE TITLE
 [Feature request] Add an option to always show secondary key bindings

### ISSUE THREAD

**Issue by EEL4114** [futo-org/android-keyboard#309]
One feature from the standard google keyboard that is unfortunately missing in the FUTO keyboard rn is the ability to always see what symbol a key would insert when pressed long, for example by displaying that symbol in the top right edge of the key buttons, as Gboard does it.
At least to me that addition would make typing on the FUTO keyboard faster, more fluent and more enjoyable overall :)
(I'm sorry if someone else already posted this; I probably overlooked it; I also hope that I'm not just too dumb to find the setting for it).
<img width="494" alt="keyboard" src="https://github.com/user-attachments/assets/82eaca65-ca18-40eb-9fbb-e08cf87a318d">

**Comment by leloup314** [comment]
+1

**Comment by bmn** [comment]
This is in the option Theme > Show symbol hints.

**Comment by leloup314** [comment]
Thanks a bunch! It might be worth to consider relocating this option to "Typing Preferences" as it is not intuitive to be located under "Theme" IMO

**Comment by EEL4114** [comment]
oh thanks a lot! Yea I'd suggest relocating the setting to Typing preferences, as I really didn't expect it to be in the themes section

**Comment by mateusz-kolecki** [comment]
Thanks for awesome keyboard! Please consider enablind this by default.

**Comment by kj4ezj** [comment]
My friend asked why this feature doesn't exist and "theme" is where I looked first FWIW, because this is a visual element. It is buried under the visual themes though, I did not expect there to be further settings when I scrolled down. It may be smart to enable it by default since people are assuming the feature is not present.

In any case the feature does exist, so we should close this issue.

**Comment by kj4ezj** [comment]
Duplicates [issue 80](https://github.com/futo-org/android-keyboard/issues/80).

**Comment by abb128** [comment]
Closing as this option is already in Themes. It'll be moved to a more clear spot in the next update
