### ISSUE TITLE
Text suggestions issue with cursor control

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#31]
If you tap a text suggestion while the cursor is being moved by the space bar or backspace cursor control it fails to replace the word with the suggestion, also if you use backspace cursor control but don't actually delete anything it fails to replace it.
The video below contains 3 instances of the bug.
[

https://github.com/futo-org/android-keyboard/assets/157768191/4c139884-539c-455a-80e7-30acdae11ebf

](url)

**Comment by abb128** [comment]
All of these cases should no longer be possible or be fixed in nightly
