### ISSUE TITLE
Use Any Layout with Any Language

### ISSUE THREAD

**Issue by EEL4114** [futo-org/android-keyboard#310]
I personally prefer using the quertz layout with ä, ö and ü for german, but for english typing, I can't use the same layout which really messes up my muscle memory and not using the english language setting significantly reduces auto-correction quality for english text (as everyone would expect).

**Comment by BlackWolfWoof** [comment]
This is currently the only thing preventing me from switching from Gboard.
If this would be added i'd switch right away as it makes it easy and seamless for us.

**Comment by dean-futo** [comment]
Part of the large discussion regarding the request for multi-language capability in a single layout in #683 - merging this issue into that one.
