### ISSUE TITLE
Key Pop-Ups Are Oversized in Horizontal Mode

### ISSUE THREAD

**Issue by SdoggaMan** [futo-org/android-keyboard#313]
In Horizontal mode, the pop-ups above each key are massive, so you can only see the top section of the character, like the horizontal stick on a '7' or a shallow semi-circle on an 'O'. 

Not particularly impactful unless you need the additional characters under those pop-ups but more than happy to help test and resolve this however I can!

Android 13 - Moto Edge 30 Pro - Version name: 0.1.22-playstore, code 10804

**Comment by dean-futo** [comment]
Very similar as #494 - merging this issue into that one.
