### ISSUE TITLE
Numberpad mode crashes constantly

### ISSUE THREAD

**Issue by SdoggaMan** [futo-org/android-keyboard#314]
This may be related to #308 - however, that seems to apply to the whole keyboard app. 

On my system, the numberpad version of the keyboard crashes constantly, in any app (bank app, authenticators, when entering card info to pay for this delicious software, etc.) 

The regular keyboard is rock solid and has not crashed once that I've noticed. 

Android 13 - Moto Edge 30 Pro - Version name: 0.1.22-playstore, code 10804

**Comment by marbv1** [comment]
It would be nice to be able to switch to numpad mode whenever I want, like when pressing "?123" button and then "=\<"... I used to use this a lot on AnySoftKeyboard.

**Comment by SdoggaMan** [comment]
FWIW, this appears to have been fixed or significantly reduced on v0.1.23.2-playstore. The worst apps (Microsoft Authenticator, bank app, CC entry into Grayjay) all appear to be fully functional now. I'll reply again if I have another crash.

**Comment by abb128** [comment]
Open a new issue if this persists
