### ISSUE TITLE
Issues on OnePlus / Oxygen OS

### ISSUE THREAD

**Issue by smurfhunter** [futo-org/android-keyboard#315]
Have noticed the keyboard seems to stop opening on my oneplus 11 pro after a couple hours, and the fix is to force stop and reopen the app. I've disabled battery restrictions on the app. Latest version of the phone's OS, Android 14.

If there's better information I can provide, please let me know!

**Comment by GOinfo-Ltd** [comment]
I have noticed the same thing. Oneplus Open on Android 14.

It happens both on the outside and inside screen.

I believe it happens more often after I manually discard the keyboard with the button at the bottom left, but I'm not 100% sure.

When the crash happens, the Keyboard simply doesn't show up when it should, and trying to open the FUTO Keyboard app just shows the splash screen and stops there.

All restrictions on battery are disabled as well.

**Comment by gigatux** [comment]
Same thing here too. OnePlus 11 on Android 14.

OnePlus does seem to have aggressive energy saving functionality, but it might not be that if others have removed battery restrictions on the keyboard.

**Comment by smurfhunter** [comment]
Tried turning off memory as RAM - that seemed to help, it went half a day without issue. That could also be placebo, because it definitely didn't fix the issue.

**Comment by ryannoblett** [comment]
I have the same issue on my OnePlus 10 Pro, latest OxygenOS/android 14.

It seems pretty random, keyboard just stops opening. I fix it by manually opening the futo keyboard app from the app drawer and waiting for a bit, it tries to open, then crashes, then the keyboard works again. Sometimes it lasts an hour, sometimes days, can't pin it down.

**Comment by abb128** [comment]
Can anyone confirm this happens on the latest version, v0.1.23.2? There was a potentially related issue that was fixed

**Comment by gigatux** [comment]
For the first time ever, my keyboard has remained not-dead for 2 days now. This is following upgrading to the latest version. Has anyone else found this fix the issue?

I know I'm going to jinx it and it'll die as soon as I send this message.

**Comment by smurfhunter** [comment]
> Can anyone confirm this happens on the latest version, v0.1.23.2? There was a potentially related issue that was fixed

I've just updated and will keep the thread posted

**Comment by gigatux** [comment]
Still running well here and I got the release pretty much as soon as it dropped on git.

I'm going to tentatively say that the new release has fixed this issue.

**Comment by GOinfo-Ltd** [comment]
So far so good for me too!

I will report back if it happens again. Thank you!

**Comment by GOinfo-Ltd** [comment]
I have not had this issue again since then. I am also going to tentatively say this is fixed.

Thank you again!
