### ISSUE TITLE
Keyboard takes up 80-90% of screen on Samsung Z Fold 4

### ISSUE THREAD

**Issue by MSvoboda-DU** [futo-org/android-keyboard#317]
Keyboard functions normally when the phone is closed, but when the phone is open, it takes up 80-90% of the screen. 
I've attached a screen capture to illustrate the issue. This picture is of the entire screen with the keyboard open. Notice the gap between the top of the keyboard and the header of the phone. 

[Uploading 450003066_1171585874032416_6865353441560895080_n_Redacted.pdf…]()

**Comment by abb128** [comment]
Split layout and some fold optimizations have been implemented in nightly

**Comment by MSvoboda-DU** [comment]
Thank you!
