### ISSUE TITLE
[Feature Request] KeePassDX

### ISSUE THREAD

**Issue by Ginarks** [futo-org/android-keyboard#318]
KeepassDX is an open source password manager it works with .kdbx files so we can use the same file for KeePassXC and KeePassDX which is great to have everything in the same place personally i update or add new passwords in KeePassXC and just update the file in KeePassDX everytime so i can access my passwords on my phone and curently we can acces passwords stored with google and i dont know if we actually can do the same thing with KeePassDX.

**Comment by abb128** [comment]
You need to set your password manager as the inline autofill provider in its settings, and then it should present you the option to autofill in password fields

**Comment by Ginarks** [comment]
Thank you.
