### ISSUE TITLE
SMS Code Autofill Functionality

### ISSUE THREAD

**Issue by apprehensions** [futo-org/android-keyboard#320]
Would be handy for FUTO to automatically detect codes in SMS messages and the ability to fill them in.

**Comment by weedy** [comment]
Honestly, I just needed to pop up with the contents of my clipboard. Like Gboard does anytime I switch apps and open the keyboard.

My notification pop up has a big giant copy, whatever the heck the number is, from the text message.

If I just also instantly got a button in Futo to paste that, like Gboard does, that would be much appreciated.

**Comment by dean-futo** [comment]
Discussed in #429 regarding smart-parsing (including autofill of 2FA codes) - merging this issue into that one.

**Comment by weedy** [comment]
The action bar mostly solves this.

I can both paste the current thing in the clipboard and open the clipboard manager to see past history. 
Between my messages app just having a "copy 123455" in the notification shade and Bitwarden set to automatically put the second factor into the clipboard when I autofill. I think this is much less of an issue.
