### ISSUE TITLE
[Feature request] Widescreen - have a different keyboard layout for widescreen or large displays

### ISSUE THREAD

**Issue by Webbeh** [futo-org/android-keyboard#326]
Good morning,

I have been using FUTO since it was announced a few weeks ago, and I'm super happy with it.

I am on Oneplus Open (foldable).

One gripe I have is that there is no proper widescreen support (at least that I found). The keyboard simply "scales up" to fill the width of the screen, whether I'm in landscape on the outside screen, or whether I'm on the inside screen.

This results in a keyboard that's quite hard to use with some keys that are hard to reach.

I'm suggesting a split keyboard layout whenever the keyboard reaches a certain width, with a few examples here :
![image](https://github.com/user-attachments/assets/99d65979-2a5c-4b6c-85d7-0eb90c83c6a7)
![image](https://github.com/user-attachments/assets/b9391466-f9d2-4b0a-a598-28de3032fc74)
![image](https://github.com/user-attachments/assets/c68ebff0-1f96-4d2f-83a9-fa88a120c1fb)

This would not only make the keyboard drastically easier to use, but also take up less height on the screen. At this moment, whenever the keyboard is up in landscape mode, it takes literally the whole screen to me.

![Screenshot_2024-07-22-09-56-59-96_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/05f48d0a-d833-4bf0-a605-0e7af52681a6)

Thank you very much !

**Comment by thepting** [comment]
Just got a Pixel fold pro 9 and am running into the same problem.  Ended up switching backs to Gboard so I can typed.

**Comment by ecamp017** [comment]
second this, Galaxy Fold 5.

**Comment by abb128** [comment]
Split layout and some fold optimizations have been implemented in nightly
