### ISSUE TITLE
Swipe to Type Gets Worse Over Time

### ISSUE THREAD

**Issue by elvishcraftsman** [futo-org/android-keyboard#332]
When I installed FUTO keyboard, it was mainly because I wanted something with swipe functionality that was also privacy-focused. I was gratified that it seemed to work better than the keyboard I had used previously (AnySoftKeyboard).

However, over time, it seemed to get worse and worse. I eventually had to be very precise with my swiping, or it would get the wrong word. I couldn't do two-letter words, because it just wouldn't pick them up. Now, several months later, the swipe feature is simply unusable. More often than not, it gets the wrong word, no matter how precise I am.

Today I uninstalled and reinstalled it. Seems to be working as well as it was in the beginning.

**Comment by abb128** [comment]
What was the problem with it exactly, did it start suggesting more non-words? The only thing that would affect it over time is the expansion of the user dictionary (dictionary built from words you type), which can introduce new words or skew word frequencies. It hasn't been tested too much with user dictionary over time so it's possible there may be some issues with it

**Comment by carbon66** [comment]
I think I have noticed the same thing and it's hard to tell whether it is me being less accurate or if it's not capturing the points that I intend to stop that on the keys. I think it would be useful to integrate the neural network part to potentially help guess the correct word you intend to type.

**Comment by dean-futo** [comment]
Consolidated into #665
