### ISSUE TITLE
[Feature request] Keyboard re-sizing

### ISSUE THREAD

**Issue by Greatest-Cupcake** [futo-org/android-keyboard#333]
The ability to reduce/increase the size/scale of the keyboard (within reason). I.E. the keyboard currently takes up 36.6 of my screen. I'd like to be able to reduce that to 30, or even 25%. For others, I'm sure larger would also help (my grandmother for example), so being able to do up to 50% would be great.
Version: 0.1.22
Preferences attached.
![Screenshot_20240722-145821_FUTO_Keyboard](https://github.com/user-attachments/assets/90d5c07b-6b9f-4b14-8535-295cb0f8d14b)

**Comment by abb128** [comment]
You can already resize at the bottom of theme options. After v0.1.23, this would be in a dedicated section in Keyboard & Typing -> Resize Keyboard

**Comment by Greatest-Cupcake** [comment]
Duh! Didn't think to scroll down after seeing it as colour palettes; shame on me!
