### ISSUE TITLE
Emoji button missing in 0.1.23

### ISSUE THREAD

**Issue by snaarb** [futo-org/android-keyboard#335]
Just received update 0.1.23 via the manual update button and it appears that the emoji selection is no longer visible.
See screenshot.

![Screenshot_20240722_175808_Firefox](https://github.com/user-attachments/assets/dff700bb-49f9-42d8-934d-6e050eef4594)

**Comment by abb128** [comment]
Does this occur in every text field, or is it visible in some?

**Comment by snaarb** [comment]
I believe it happens in every text field.

**Comment by Sureshgorai25** [comment]
> Just received update 0.1.23 via the manual update button and it appears that the emoji selection is no longer visible. See screenshot.
> 
> ![Screenshot_20240722_175808_Firefox](https://private-user-images.githubusercontent.com/176347098/351134407-dff700bb-49f9-42d8-934d-6e050eef4594.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDk2MjYsIm5iZiI6MTcyMTcwOTMyNiwicGF0aCI6Ii8xNzYzNDcwOTgvMzUxMTM0NDA3LWRmZjcwMGJiLTQ5ZjktNDJkOC05MzRkLTZlMDUwZWVmNDU5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNDM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDQ4MDA1MDhhYTlmMzNjYTJkYTUxM2Q2NTJiMTVmNDVhOTBmMDA5MjMyZDc4MjI2Y2I1ZGEyNTdmNzEwZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-9ke2Q5kgaZIAvOymJ4ZlIac9FubH6JqXJxgCOkqeBw)



> Just received update 0.1.23 via the manual update button and it appears that the emoji selection is no longer visible. See screenshot.
> 
> ![Screenshot_20240722_175808_Firefox](https://private-user-images.githubusercontent.com/176347098/351134407-dff700bb-49f9-42d8-934d-6e050eef4594.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDk2MjYsIm5iZiI6MTcyMTcwOTMyNiwicGF0aCI6Ii8xNzYzNDcwOTgvMzUxMTM0NDA3LWRmZjcwMGJiLTQ5ZjktNDJkOC05MzRkLTZlMDUwZWVmNDU5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNDM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDQ4MDA1MDhhYTlmMzNjYTJkYTUxM2Q2NTJiMTVmNDVhOTBmMDA5MjMyZDc4MjI2Y2I1ZGEyNTdmNzEwZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-9ke2Q5kgaZIAvOymJ4ZlIac9FubH6JqXJxgCOkqeBw)

Why your keyboard looks different than mine?
![Screenshot_20240723-085532](https://github.com/user-attachments/assets/2fd7da7b-a87b-4a6d-b8f3-dc761cf61abb)

**Comment by exetico** [comment]
@abb128 Emoji was added as action button. I had the same issue.

Hot-fix: Moved Emoji to "Pinned", and checked that it was visible as Pinned. It was..

Moved it back as "Action", and wolla. The Emoji button was visible again.

My app are also 0.1.23 (from Play Store).

![Screenshot_20240723-085132](https://github.com/user-attachments/assets/1918f528-18f9-4cfa-ae08-d7d6ac4ce5fc)

**Comment by The-Quantum-Alpha** [comment]
> Moved it back as "Action",

Somehow I cannot even do that, it won't allow me to put anything there..

Indeed the emoji key is missing, and speaking on behalf of some of my people, it's an important key.. :)

**Comment by abb128** [comment]
Ok, this is a bug. You can manually fix it by opening the Edit Pinned menu and closing it without even dragging anything.

@The-Quantum-Alpha You should be able to put it there. The drag and drop can be a little buggy sometimes, it may take a bit of dragging in the gap to convince it

**Comment by royborgen** [comment]
I have this same issue. The hotfix to move it from action key and back did not work. I was unable to move it back under Action keys. However I am able to use emoji's if I place it under Pinned Actions. It will then display next to the microphone icon for dictations.

**Comment by The-Quantum-Alpha** [comment]
I have tried all the things you mentioned above, and what did it was to add the actions button by sliding it to the right on the gap..

> can long-press the enter key to access emoji menu as well

Indeed, I don't use emojis that much, but some close ones do.. and they prefer quick access.

Thank you for the response.

**Comment by abb128** [comment]
Should be fixed in 0.1.23.1 which is available as a manual standalone update, and will be rolled out over Google Play and other platforms soon

**Comment by The-Quantum-Alpha** [comment]
Give this man a raise!

**Comment by royborgen** [comment]
Truly impressive response time on fixing this! Much appreciated!
