### ISSUE TITLE
Redesign the emoji panel 

### ISSUE THREAD

**Issue by sajjad000** [futo-org/android-keyboard#34]
To improve the user experience, please redesign the emoji panel To this design:

https://github.com/futo-org/android-keyboard/assets/118594121/20f34b76-a011-40cf-94d5-939a33fbe766

As this design makes it easier for the user to reach the buttons, especially if the person uses one hand

**Comment by abb128** [comment]
IMO it would be better to keep the emoji menu similar to other popular keyboards that users are already familiar with, rather than going with something completely different
