### ISSUE TITLE
Change the location of the exit button from the emoji menu 

### ISSUE THREAD

**Issue by sajjad000** [futo-org/android-keyboard#340]
hello

In the emoji menu, there are two exit buttons on the left side to improve the user experience, please move one of the buttons to the right side 
![Screenshot_20240723_095141](https://github.com/user-attachments/assets/79b2e226-da2f-4316-b4a4-12a3c7ea5d09)

This is from the SwiftKey keyboard, which I always use because the button to exit the emoji menu is on the right side, and it is comfortable because it is close to the finger

https://github.com/user-attachments/assets/bd324f6a-f03d-4906-b122-1dd74836169d

In order to satisfy everyone and improve the user experience, I added two exit buttons at the top on the right and left side to be easy to access in the case of using one hand Please make it like this 
![Picsart_24-07-24_16-55-48-974](https://github.com/user-attachments/assets/1811e873-bbc3-4917-924f-527fd3c15adf)

**Comment by abb128** [comment]
I believe the problem you're describing is not something that should be solved by adding redundant buttons that will confuse most people, but rather by general one-handed mode support (#48)
