### ISSUE TITLE
Extra Spaces Added by Autocorrect

### ISSUE THREAD

**Issue by Erron-26** [futo-org/android-keyboard#348]
Version Name: 0.1.23.1 - playstore

Hi, I have a very annoying problem that I'm not sure if it happens in other languages, but with the Spanish keyboard, when the autocorrect corrects a word, sometimes an extra space is added without me noticing. It happens sometimes, even when I select a word from the suggestions for correction, it also adds that involuntary space.

It's annoying because since the last update, it happens more frequently than usual. So, I send a message on WhatsApp that I thought was well-written and it might have some spaces there that I don't know where they came from. This did not happen with the Samsung keyboard. So, if this is part of the core functionality of the Futo keyboard, I would like an option to disable that extra space.

**Comment by FireNinja7365** [comment]
Probably related to #190

**Comment by Erron-26** [comment]
Did you report this issue about 3 weeks ago? To be honest, ever since I updated the keyboard, I feel like even the simple things I type have spaces where it didn't matter before. I'm not sure if there's some extra bug related to this going. Anyway thanks

**Comment by abb128** [comment]
This should be fixed in nightly and the fix will be included in the next release.
