### ISSUE TITLE
Duplicate Word Suggestions in Text Prediction

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#351]
Sometimes text suggestions contain duplicate words.

![Screenshot_20240724-012141-231](https://github.com/user-attachments/assets/5b9e1280-48dc-445c-87f6-6165fbea8ec3)

**Comment by dean-futo** [comment]
Consolidated into #672

**Comment by dean-futo** [comment]
Duplicate of #181 - merging that issue into this one. Both point to the same problem pictured above of how text prediction will give duplicate suggestions.

**Comment by dean-futo** [comment]
@FireNinja7365 this is not reproducible in the nightly build and will be fixed in the next release.

**Comment by FireNinja7365** [comment]
Still happens occasionally (I'm talking about the first two you can ignore the last one)
![Screenshot_20241109-070023-838](https://github.com/user-attachments/assets/0e760860-d70a-4cde-b465-3521bafa4a0e)
