### ISSUE TITLE
Keyboard Closes Upon Voice Processing

### ISSUE THREAD

**Issue by mad1mystic** [futo-org/android-keyboard#352]
Keyboard closes itself upon word processing , used to work properly before,  works in work profile. When speaking is done keyboard automatically closes .

**Comment by abb128** [comment]
Do you have a custom voice input model imported, or are they all default?

**Comment by mad1mystic** [comment]
> Do you have a custom voice input model imported, or are they all default?

It's default , I tried uninstalling and installing again but problem persist , keyboard was working before this sudden crashing problem . strangely the voice input function is working properly in work profile of Android. keyboard updated to latest version !

**Comment by MordorMinion** [comment]
Same as #467 ?

**Comment by dean-futo** [comment]
Consolidated into #664
