### ISSUE TITLE
Bug: After enabling voice verbose progress, cannot disable it.

### ISSUE THREAD

**Issue by unoukujou** [futo-org/android-keyboard#361]
V1.23.2

Settings, Voice Input, Verbose Progress.

I enabled it. Then I went back to the settings to disable it but the UI showed it as already disabled? But it is actually enabled and no way to disable it.

**Comment by abb128** [comment]
What verbose info are you seeing that you're not expecting to see? Is it the little toast that says which mic is being used? That one displays if the "Prefer bluetooth mic" toggle is enabled

**Comment by unoukujou** [comment]
> What verbose info are you seeing that you're not expecting to see? Is it the little toast that says which mic is being used? That one displays if the "Prefer bluetooth mic" toggle is enabled

Yes that's what I was seeing. So I'm not sure exactly what Verbose Progress does? Apparently no difference for me whether it's enabled or disabled.

And the first time I enabled it, when I came back to the setting, it was set back to disabled all by itself without me ever disabling it. Though again, I'm not sure what this setting does.

**Comment by abb128** [comment]
The verbose setting is mainly left over from some old stuff to diagnose certain issues, it's no longer really relevant, it may be removed in a next version to reduce confusion
