### ISSUE TITLE
Bug: Swipe typing doesn't work on some search fields

### ISSUE THREAD

**Issue by Doc-4** [futo-org/android-keyboard#37]
Some search fields, specifically ones that don't generate suggestions in the keyboard, also will not type anything via swiping. Video provided:

https://github.com/futo-org/android-keyboard/assets/60247583/8b9642ee-cc74-45b9-9f78-dea0421f2eaa

**Comment by robsdedude** [comment]
Ironically, I've noticed this issue when trying to file a feature request in this issue tracker through the GitHub Android app. The word completion/correction is also missing.

**Comment by tsjnachos117** [comment]
I've experienced the same bug with my phone's default calendar app. It's quite annoying, as I usually need it in times/places where it's too noisy to use the speech recognizer.

**Comment by abb128** [comment]
This occurs in text fields where the app has specified that it provides its own auto-completions, in these text fields the keyboard skips generating its own suggestions which also means skipping swipe suggestions. In the next version this will be fixed by generating suggestions regardless
