### ISSUE TITLE
Accidental Number button presses and autocorrect

### ISSUE THREAD

**Issue by te-simps** [futo-org/android-keyboard#370]
The keyboard would function a bit better if the number key row was slightly shorter in height and had a bigger space from the top letter row. I often accidentally type the number instead of a letter and this is not picked up by the autocorrect. Words like we8ght don't get corrected automatically.

**Comment by Archov** [comment]
This is the biggest issue I've got with the keyboard right now. I'm not 100% sure if it's enough to make me go back, but it might be.

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.
