### ISSUE TITLE
[feature-request] T9 keyboard option in number/character keyboard

### ISSUE THREAD

**Issue by skj-skj** [futo-org/android-keyboard#371]
when typing long numbers or 4-6 digits pin I find it useful to use T9 keyboard layout in the Gboard.

Screenshot example:
![Screenshot-T9-Keyboard-Layout](https://github.com/user-attachments/assets/cb7a3bbd-d74b-46f0-83ed-7b12ee424097)

Thanks.

**Comment by abb128** [comment]
Duplicate of #64
