### ISSUE TITLE
Autocorrect Mistakes with 'xcvbn' Key Row

### ISSUE THREAD

**Issue by m1st0** [futo-org/android-keyboard#372]
Issue: One of the simplest ways I don't see autocorrection is when the spacebar is easily missed and words are misspelled with the "xcvbn" letters.

Expected: Intelligence on autocorrect to recognize word mispeling with above letters.

Such that:
Onebnofvthesimplestbways I dontnsee . . .

**Comment by GOinfo-Ltd** [comment]
I have to admit I didn't even think of opening this as an issue, but I do have the same problem.

**Comment by wings2004** [comment]
Honestly I was going to recommend a feature that let you add padding between the space row and the bottom number row. That would help a lot for now.

**Comment by Tema726** [comment]
Yes, this one!

**Comment by kispin** [comment]
Same, I came here to make the same suggestion! I keep hitting B instead of the space bar.

**Comment by dean-futo** [comment]
Consolidated into #666

**Comment by Webbeh** [comment]
Thank you!

**Comment by dean-futo** [comment]
Duplicate of #271 - see that issue for details.
