### ISSUE TITLE
Emoji Suggestion Word Duplication Bug

### ISSUE THREAD

**Issue by Lu9-ST** [futo-org/android-keyboard#376]
So sometimes I will write an emoji name as a suggestion and since that (for now at least) is seemingly tied to english only, I'd then switch to english, then the emoji appears, but when i tap it, the word for the suggestion remains. This probably extends to just regular word suggestions beyond just emoji too, meaning a word will duplicate itself

for instance:
Language is set to portuguese, but I type "joy" for the 😂 emoji, I switch to english, the emoji appears, but clicking it results in:
"joy😂" rather than just "😂" 
And if I select the *word* instead, it will result in "joyjoy"

**Comment by dean-futo** [comment]
Consolidated into #672
