### ISSUE TITLE
[Feature request] Option to disable the language picker

### ISSUE THREAD

**Issue by thatguy764** [futo-org/android-keyboard#379]
Holding down the spacebar currently brings up the dialogue to switch languages, even if only one is installed. This can be a problem as it's very easy to accidentally bring up that dialogue while trying to use the spacebar to move the text cursor around by sliding along it. The option to either disable the language selection, or move it somewhere else, or just reducing the sensitivity on the space bar would be highly appreciated.

**Comment by abb128** [comment]
You can already configure this in long-press key settings in the latest version
