### ISSUE TITLE
LLM model for autocorrection : qwen:0.5b (multilingual, 350mb)

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [futo-org/android-keyboard#380]
Hi,

I don't know much about the transformer model used for word corrections but I recently stumbled upon a model that might be super relevant : qwen2 ([ollama link here](https://ollama.com/library/qwen2:0.5b)). It's multilingual anf exists in version 0.5b for only 350MB. Maybe this could be used by other languages than english?

**Comment by abb128** [comment]
This model is too big to be usable and it's intended for a different purpose
