### ISSUE TITLE
Cannot pay for Keyboard.

### ISSUE THREAD

**Issue by buntuv** [futo-org/android-keyboard#381]
### What happened?

At the step when asking for the currency I  want to pay with I type USD, but it does not allow to proceed. 

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
It should let you select USD from the list and then you can continue and complete the purchase. If it still doesn't work could you attach a screen recording of the issue?

**Comment by buntuv** [comment]
I tried it again and it worked. Thanks...

Jul 27, 2024 7:28:02 PM abb128 ***@***.***>:
