### ISSUE TITLE
Farsi/Persian: easy punctuation access

### ISSUE THREAD

**Issue by AriaMoradi** [futo-org/android-keyboard#382]
### Language

Farsi

### Description

Punctuation marks should go under the period symbol (.)
The existing diacritics could stay under period or be distributed under other keys similar to the standard Persian keyboard.

### Complexity

Should be easy, just move some symbols around.

**Comment by AriaMoradi** [comment]
Microsoft swiftKey has this already figured out, maybe it could be used as a reference?

**Comment by abb128** [comment]
This will be added in the next update
