### ISSUE TITLE
[Bug] Only Bulgarian BDS keyboard available

### ISSUE THREAD

**Issue by dikel** [futo-org/android-keyboard#385]
### What happened?

When adding a Bulgarian keyboard, only the BDS layout is available even thought there are 2 layouts in the source code: [bulgarian](https://github.com/futo-org/android-keyboard/blob/bc8fb32086f7f14e362dada4b0001961f4594887/java/res/xml/kbd_bulgarian.xml) and [bulgarian-bds](https://github.com/futo-org/android-keyboard/blob/bc8fb32086f7f14e362dada4b0001961f4594887/java/res/xml/kbd_bulgarian_bds.xml)

### Keyboard Version

0.1.23

**Comment by abb128** [comment]
Looks like it was excluded by mistake. It'll be included in the next version.
