### ISSUE TITLE
Make the ñ key hold type a "/"

### ISSUE THREAD

**Issue by BoscoDomingo** [futo-org/android-keyboard#386]
### Language

Spanish

### Description

```ñ``` should print "/" when long-pressed, such as in the Google Keyboard:

![Screenshot_2024-07-28-17-20-45-018_com miui notes-edit](https://github.com/user-attachments/assets/e53d367a-f3ff-4651-9dba-cd1270f3fc0c)

### Complexity

0 complexity. Just adding a new symbol to an existing letter

**Comment by abb128** [comment]
This is fixed in nightly
