### ISSUE TITLE
First Word Automatically Capitalized Despite Auto-Capitalize Being Turned Off

### ISSUE THREAD

**Issue by Condorasaur** [futo-org/android-keyboard#388]
### What happened?

When the first word in a sentence is autocorrected (most notably when it automatically adds an apostrophe for contractions) it is automatically capitalized as well, despite auto-capitalization being turned off. I prefer to manually capitalize words and having to manually decapitalize them is not fun.

### Keyboard Version

0.1.23.2-playstore

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Duplicate of #547 - see that issue for details.
