### ISSUE TITLE
Allow fine grained keyboard height customisation between the default fixed choices

### ISSUE THREAD

**Issue by driftywinds** [futo-org/android-keyboard#391]
### Use Cases

I am used to gboard being a specific height, and when I shifted to the FUTO keyboard I realised my ideal keyboard height lays between the 91% and the 100% fixed choices that the app provides. I want to customise it to be between those two choices but that is not possible yet.

### Proposal

Just add a plus and minus sign for the users to be able to manually set the height percentage between the two choices, e.g. choose a number between the 91% and the 100% that are available right now.

### References

![Screenshot_2024-07-29-11-23-57-31_7828b6c7e396d29747fb0876b6b35e65](https://github.com/user-attachments/assets/76300ac6-60c2-44c2-8037-81b1979b3480)

**Comment by abb128** [comment]
You can already tap the percentage to enter a custom value

**Comment by driftywinds** [comment]
> You can already tap the percentage to enter a custom value

Yes, thank you!!

**Comment by NikunjKhangwal** [comment]
Maybe a note should to added to let users know about this hidden functionality?
