### ISSUE TITLE
Increase Key Border Contrast for AMOLED Black Theme

### ISSUE THREAD

**Issue by driftywinds** [futo-org/android-keyboard#392]
### What happened?

The colour difference between the key borders and the amoled black background is negligible which makes it look like the amoled black theme does not have key borders even when it is turned on.

A simple fix for this would be to make the colour of the key borders lighter than they already are, or allow customisation of the key border colour by the user themselves.

For ref - (the key borders might seem okay on your screen but it sucks for AMOLED screens)
![Screenshot_2024-07-29-11-29-22-46_7828b6c7e396d29747fb0876b6b35e65](https://github.com/user-attachments/assets/639e0561-b09c-4d8e-8d40-2b01c30f4bea)

### Keyboard Version

0.1.23.2

**Comment by dean-futo** [comment]
Similar to #753 - merging this request into that one.
