### ISSUE TITLE
Allow adjusting inset of keyboard from the sides of the screen

### ISSUE THREAD

**Issue by LoganDark** [futo-org/android-keyboard#397]
### Use Cases

My phone is the Nubia Z60 Ultra, which has very little bezels. FUTO keyboard goes very close to the edges of the screen, making it very difficult to use while holding the phone, especially when the included screen protector is not removed because it catches.

### Proposal

The height and offset of the keyboard is already customizable, but you can't adjust the inset from the edges of the screen. A setting like that maybe could be added so that my digits don't collide and drop the phone while I'm trying to type.

**Comment by abb128** [comment]
This has been added in nightly
