### ISSUE TITLE
Feature Request cursor control

### ISSUE THREAD

**Issue by birdup000** [futo-org/android-keyboard#4]
I threw this into Antropic Claude 3 Haiku to better explain the feature.

"trackpad" or "cursor control" feature on smartphones. This allows you to use the keyboard as a mini trackpad to precisely position the cursor when typing.

On iPhones, this feature is called "Cursor Control" and it works by long-pressing on the spacebar to activate the trackpad mode. You can then slide your finger around the keyboard area to move the cursor.

Many Android smartphones also have a similar feature, often referred to as "Keyboard Trackpad" or "Cursor Control." The exact implementation may vary by device, but the general functionality is the same - long-pressing the spacebar activates a mini trackpad on the keyboard for precise cursor positioning.

This feature is very handy for editing text, moving the cursor to a specific spot, or making corrections without having to tap directly on the screen. It's a useful productivity enhancement for mobile typing.

**Comment by abb128** [comment]
You can already drag the spacebar to drag the cursor left and right
