### ISSUE TITLE
Feature Parity with FlorisBoard & FUTO Voice Input Compatibility

### ISSUE THREAD

**Issue by Andrew-Mattias** [futo-org/android-keyboard#40]
There are two huge issues with Base AOSP keyboard, which is used as a base for FUTO keyboard:

1. It is lackluster on features and options
2. It is really sluggish and slow (to respond on gestures especially).

I dont know how you can deal with general sluggishness without rewriting big chunks keyboard codebase. The fact that smartphones that are able to render PS3 level games an 3D graphics are not snappy as hell when typing and lag on keyboard gestures is kinda embarrasing. FlorisBoard is a goog example to compare you keyboard to. FlBd is not an AOSP fork and it is considerably snappier, more responsive and silky smooth on gestures most of the time.

As for the features - if you are aiming to become №1 FOSS/Source first keyboard, you should reach feature-parity with FlorisBoard. Aside from swipe-input and and intellectual suggestions, Floris board is №1 Android keyboard when it comes to speed and feature-compleetness. I think there is no point at listing all FlorisBoard features here (many of which are already suggested in othe feature-requests), so i'll just provide a link to a project web-site

https://florisboard.org/

P.S. Can you List FlorisBoard as a compatible option for FUTO voice input if possible. FlorisBoard is a superb and megapopular keyboard on f-droid and it is compatible with your voice input.

**Comment by tgoeg** [comment]
I know this might not be popular - but what about joining forces with floris board devs? Floris board is eons ahead of any other keyboard as already stated. It would take considerable work to even achieve feature parity. Time which could be invested for improving floris board itself.
Please excuse if this has already been considered before and decided not worth the try.
(And if, I'd be interested in why, however, nosy as I am!)

**Comment by Andrew-Mattias** [comment]
> I know this might not be popular - but what about joining forces with floris board devs? Floris board is eons ahead of any other keyboard as already stated. It would take considerable work to even achieve feature parity. Time which could be invested for improving floris board itself.

At this point it is unrealistic that they would rebase their work from AOSP keyboard (which is shit) to FlorisBoard (which is entirely different codebase i can imagine). Thats why i dont have much hope that they will do it. Feature and performance parity with FB could be a goal still. This makes me sad, because like 85% of perfect keyboard is already made by FB and we need start anew to maybe get beyond this 85% level from 20-30% baseline again.

**Comment by dean-futo** [comment]
Thanks for your feedback. Closing this issue as there weren't any specific feature requests. Please check out our latest nightly build if you haven't already and let us know if you have any specific requests in regards to achieving feature parity with FlorisBoard.
