### ISSUE TITLE
Add Pure Black Option for AMOLED Theme

### ISSUE THREAD

**Issue by D3SOX** [futo-org/android-keyboard#401]
### Use Cases

I have enabled this setting but the keyboard doesn't respect that I want a pure black background

<img src="https://github.com/user-attachments/assets/840a5fd3-d218-4857-8d6f-e292582f91f8" height=500 />

### Proposal

My suggestion is to just add another variant of the Dynamic theme but with a pitch black background.

**Comment by dean-futo** [comment]
Similar to #753 - merging this request into that one.
