### ISSUE TITLE
Correct Swipe Direction for Right-to-Left Languages

### ISSUE THREAD

**Issue by Ahmed-AbdulSamee** [futo-org/android-keyboard#402]
### What happened?

When typing in Arabic which direction is from right to left and using the space curser swipe or backspace swipe the swipe direction is the opposite of the cursor direction.
This is a video I recorded of this happening :

https://github.com/user-attachments/assets/6b4b803f-b310-4c60-867d-3f866dabb8dd

### Keyboard Version

0.1.23.2

**Comment by dean-futo** [comment]
Duplicate of #450 - fixed in nightly.
