### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by ThatOneCalculator** [futo-org/android-keyboard#405]
### What happened?

Some of the latest emojis (like 🫵, 🙂‍↕️, 🙂‍↔️, 🍋‍🟩, 🐦‍🔥) seem to be completely missing from Futo

### Keyboard Version

0.1.23.2

### Additional info

GitHub seems to not render the head shaking emojis properly, here's what they are

![Screenshot_20240731-084313](https://github.com/user-attachments/assets/f31a78b4-df8d-42b0-8340-2d8e844f29f2)

**Comment by abb128** [comment]
Unicode 15.1 emoji will be added in the next version

**Comment by ThatOneCalculator** [comment]
When will the next version release? Rn this is one of the few things keeping me from daily driving Futo, since I use the nodding emoji a lot lol

**Comment by abb128** [comment]
If you want you can use the nightly APK at https://keyboard.futo.org/nightly.apk it currently has the change and should be stable for use
