### ISSUE TITLE
Material You Dynamic Theming

### ISSUE THREAD

**Issue by Blykam** [futo-org/android-keyboard#406]
### Use Cases

It would be very cool to have Material You Support for the Dynamic Theme, not just Light/Dark. Just like GBoard does it.

### References

https://source.android.com/docs/core/display/material?hl=de

**Comment by abb128** [comment]
I'm not sure I understand your request. Dynamic theme is Material You

**Comment by Blykam** [comment]
At least on my Samsung S23 Ultra with Android 14 it does not change the Color Palette of the Futo Keyboard according to the one set by the OS.
For example: Wallpaper Purple -> OS Theme Purple -> Keyboard should also change to Purple Color Palette.
GBoard does adhere to this. At least on my device Futo Keyboard is always blue themed in Dynamic Mode

**Comment by D3SOX** [comment]
Works for me on CalyxOS

**Comment by Blykam** [comment]
Yeah, thanks for clarifying. Seems to be a Bug in OneUi 6.x.
I found a work around. Now it works for me, too!

**Comment by abb128** [comment]
Can you share your workaround?

**Comment by Blykam** [comment]
https://www.reddit.com/r/oneui/comments/186kk9y/comment/kdankup/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

In Dev Options change Accessability Contrast setting to high and back.

**Comment by lvsovoy** [comment]
This is still happening on one ui 7, but instead of doing above mentioned workaround with high contrast, what worked for me was going into settings -> wallpaper and style and changing the colour palette to something else, then back. Futo keyboard then changed to the colour of the theme.
