### ISSUE TITLE
Swipe Typing Misses 30-50% of Words in Spanish

### ISSUE THREAD

**Issue by AlbertoVelazquez** [futo-org/android-keyboard#408]
### What happened?

I understand that the swipe is in alpha version, but its use is completely flawed. Sometimes it misses, in Spanish, 30-50% of words. Even if you go precisely to each letter without error it chooses words with letters that you have not even touched.

Epidemia => Ella
Rocambolesco => Ruidoso
Viable=> Viene
Hola=> Hoja, Hija
Complicado => colocado
Digas => Dias

The surprising thing is that it almost always puts the correct word as the next one in proposals. Another surprising example is “Complicado” which gives “colocado” as the solution but if you try to write “colocado” it gives you “codo” or “costo.

### Keyboard Version

0.1.23.2

**Comment by dean-futo** [comment]
Consolidated into #665

**Comment by dean-futo** [comment]
Similar to #560 - merging this issue into that one. See #560 for details.
