### ISSUE TITLE
Keyboard Unresponsive in Reddit App

### ISSUE THREAD

**Issue by steviefaux** [futo-org/android-keyboard#409]
### What happened?

So, I'm typing away and keep thinking I'm not hitting space but I believe this is the keyboard being unresponsive. Its much much worse in Reddit. As you can see it randomly becomes unresponsive. Then the preditions flicker and the shift doesn't work.

Have, sadly, had to switch back to another keyboard again.

More easily explained in the vid. Also included the version number and the version of the software on the Samsung S23 Ultra that I'm using.

Seems to be mainly in the Reddit app.

https://youtu.be/8iR4GR0DyH4?si=0iz1iIQl45Ng5j6o

Paid for it now as well via your website as the payment in the app feature doesn't seem to be setup yet.

### Keyboard Version

0.1.23.2-playstore

**Comment by DavidBevi** [comment]
It happened to me too, only once, with previous version (1.22).
I've never been able to reproduce it (Sony XZ2C, Android 10).

**Comment by dean-futo** [comment]
@steviefaux I'm not able to reproduce this either. The keyboard is working well for me in the Reddit app with no lag.
