### ISSUE TITLE
Confusing Bug Report Questionnaire

### ISSUE THREAD

**Issue by ProbablyCompletelyLost** [futo-org/android-keyboard#414]
### What happened?

This is probably a really minor for most people, but on the bug report form I'm filling out now, the section section (Keyboard Version) has the instructions: "Open the FUTO Keyboard settings and look for the version name at the bottom, or in the Help & Feedback menu.", but the version name is at the top, at least on version name 0.1.23.2-playstore. 
Not just that but then the field below is a number format which implies that you didn't want the version name you said was at the top but isn't, but you maybe want the version code below it instead? 

I know it's probably just me not understanding the instructions [was my 1st time doing one of these and this emerged from that] but still.

### Keyboard Version

0.1.23.2-playstore

**Comment by abb128** [comment]
This is what it refers to, which is at the bottom:
![image](https://github.com/user-attachments/assets/5a88d3f6-006f-4b3a-916d-ff913fd90c37)
