### ISSUE TITLE
Fix Duplicate Text Issue in Suggestions During Edit Mode

### ISSUE THREAD

**Issue by Magniquick** [futo-org/android-keyboard#419]
### What happened?

- Enter some text
- Switch into text editor mode while the suggestions for the word you are editing is being displayed
- Go back to keyboard and accept any suggestion
- the old word and the new suggestion are both there, ie the suggestions appends, not overwrites, the old word. 
Android 14

### Keyboard Version

0.1.23.2-playstore

### Text field info

Happens in all tested apps

**Comment by dean-futo** [comment]
Consolidated into #672
