### ISSUE TITLE
LG Wing and terminal Support

### ISSUE THREAD

**Issue by ContinualDissapointment** [futo-org/android-keyboard#421]
### Use Cases

Sshing
Remote Control of other devices
network diagnostics
debugging
gaming
multi-tasking

### Proposal

The LG Wing was a dual screen swivel phone that could essentially enable the user to ssh into other devices, remotely control PCs, play games, all while using the proper aspect resolution upper screen for content and the bottom screen for control. Unfortunately, the only keyboard that worked on the bottom screen of this quirky device is the LG Keyboard, which is abandoned and has bloat and lacks a lot of important features, some that are incredibly baffling. Futo could give current users of this device a proper tool to take full advantage of this device, especially if the keyboard could have terminal/symbol keys. (win key, tab, esc, etc)

**Comment by abb128** [comment]
Unless there's modern phones that come out with this form factor, I don't believe the development time required would be worth it to support a very specific device which is now 3 years old and was discontinued only 6 months after its release. Not that I can even find one for sale in the EU
