### ISSUE TITLE
Add Per-Key Location Learning to Improve Typing Accuracy

### ISSUE THREAD

**Issue by Kinzon** [futo-org/android-keyboard#422]
### Use Cases

Back when I used Swype, it had a feature that slowly edited the input area of each key as you used it. It was super useful as any time I personally use swipe to text it's with my right thumb, and the keys on the far left the keyboard tend to give me issues accuracy wise. 

### Proposal

While some sort of learning would be nice, even just having the option to shift the input area of the keyboard towards one side (while keeping the keyboard itself looking uniform) would be appreciated. 

More specifically, a sort of gradient to this change. For example, keys on the right side stay mostly lined up with the visuals, while keys on the left side are shifted more to the right to allow for that extra ease of use. 

### References

Akin to #397 

(Few edits for grammar sake)

**Comment by dean-futo** [comment]
@Kinzon this has been implemented in the latest nightly build: https://keyboard.futo.org/nightly-apk
