### ISSUE TITLE
Fix Delay in Swipe Typing After Normal Typing

### ISSUE THREAD

**Issue by Kinzon** [futo-org/android-keyboard#427]
### What happened?

Trying to use swipe typing after typing normally results in a delay to swipe input. The delay varies and at times causes swipe typing to ghost the first few letters that were trying to be inputted. When it happens the key popup can be seen, and can even trigger a long press. The issue is also slightly inconsistent, struggling less when letters are farther apart at the start of a word. 

https://github.com/user-attachments/assets/8ecfc1fd-a271-46e5-bd5c-1f2167b429f4

Video attached shows typing "The quick brown fox jumps over the lazy dog" alternating between normal typing and swipe typing. Biggest delays were on "brown" and "jumps". Brown both failed and worked to swipe after normal typing, but jumps only worked after a previous swipe. 

(Edit: much easier to see happen after single letter words when swipe typing)

Device - Samsung Galaxy S24 Ultra

### Keyboard Version

0.1.23.2-playstore

**Comment by Vorpal-Mystic** [comment]
Also happening to me on Pixel 8.

**Comment by SepticFuddy** [comment]
I'm experiencing a similar issue of intermittent delay at the start of swiping, but I'm not so sure that tap typing is what's causing it. I just tried a similar test to the OP but sometimes after tapping out a word I wouldn't get the delay.

The swipe delay is definitely my #1 issue with the keyboard, though. Every time a stroke gets read as long-pressing on letters, it of course ruins the whole swipe. Swiping is 90% of how I type on the device, so it has obviously impacted me coming from a firewalled MS SwiftKey. I definitely appreciate what this app is doing though, especially for people who rely on voice-to-text.

I'm running v0.1.23.2-playstore.
Atom XL running LineageOS 17.1 and degoogled, though that doesn't seem to be related to the issue.

**Comment by dean-futo** [comment]
Consolidated into #665
