### ISSUE TITLE
[Featue Request] replace emoji key (with language switcher)

### ISSUE THREAD

**Issue by D3SOX** [futo-org/android-keyboard#43]
I'd like to replace the emoji key with a one tap language switcher that rotates through all languages. I have a similar use case like #38. But I think this is much easier to solve so  this would be particularly useful to me until the multi language is implemented.

**Comment by abb128** [comment]
Duplicate of #8 and already prepared for next update

**Comment by D3SOX** [comment]
Oops sorry didn't search for closed issues
