### ISSUE TITLE
[Feature request] Minuum mode

### ISSUE THREAD

**Issue by Tsaukpaetra** [futo-org/android-keyboard#434]
### Use Cases

I've been using the [Minuum keyboard](http://minuum.com/) for over a decade because I love the screen real estate it affords. Unfortunately it has been abandoned and slowly over the Android releases exhibits bugs and other artifacts stemming from being outdated.

It would be nice to be able to toggle a collapsed mode for normal usage and normal size for precision typing.

### Proposal

This proposal is to allow an optional "collapsed" mode for the main keyboard canvas where effectively all the letters and such are slotted down into a single row as opposed to the 4+ rows typically had in your average keyboard, and optionally keeping a the appearance of the relative height positions for visual clarity. This mode might also strengthen auto correct by default as typing would naturally be much more sloppy.

I think at the minimum adding an action to toggle the keyboard height could satisfy the initial technical ask, as the other half of combining all the keys into a single row could be accomplished with a custom layout. 🤔 

### References

![Screenshot_20240808-221832_Discord](https://github.com/user-attachments/assets/b5f70a2e-05db-425a-aa1c-4944b331f87b)
This is an example of the Minuum keyboard. Further examples can be found at Minuum.com

**Comment by McIrco95** [comment]
There is a setting to change the keyboard height
Settings/ keyboard and typing/ Resize Keyboard
![Screenshot_20240810-220739](https://github.com/user-attachments/assets/66a60305-5ca2-4c1d-b6b9-8a714798cebc)

**Comment by Tsaukpaetra** [comment]
Right, but it's a setting five taps deep, and due to the nature of the virtual keys still expects a modicum of accuracy, and it's not a toggle so when I need to be accurate I have to drill down into the settings to make it big again. :)

**Comment by abb128** [comment]
I'm going to close this as being out-of-scope for now. Creating a collapsed layout would be easy, but making it work well would require significant effort. More than that, the design is patented: https://patents.google.com/patent/USD746313S1/en

**Comment by Tsaukpaetra** [comment]
Heh, well darn, looks like I'm waiting for 2029 to try again LMAO.
