### ISSUE TITLE
T9 numbers on numpad keyboard

### ISSUE THREAD

**Issue by alphasierra59** [futo-org/android-keyboard#438]
### Use Cases

Entering numbers using letters as references.

### Proposal

Add letters to the numpad input where letters are used to select numeric entry
Current:
![image](https://github.com/user-attachments/assets/62edba1a-91d0-4385-b07a-001c62b3cccd)
Example:
![image](https://github.com/user-attachments/assets/d237c094-6dac-4ab2-b2f5-5d3bef4bf00e)

**Comment by abb128** [comment]
This should be fixed in nightly when you're typing in text fields marked as phone number inputs
