### ISSUE TITLE
[Featue Request] a clipboard thats similar to heliboards clipboard.

### ISSUE THREAD

**Issue by Fuoxden** [futo-org/android-keyboard#44]
Im a big fan of FUTO keyboard, And i love heliboard, I would love the clipboard to be similar to heliboards like this:
![ResizedImage_2024-06-26_22-34-34_2129](https://github.com/futo-org/android-keyboard/assets/169393581/b59b7d30-1de4-4c3c-9dda-05c66d960674)

Being able to have multiple entries, Being able to clear your history, Export it, Share it, ect, Thank you for reading.

**Comment by abb128** [comment]
There's already a basic clipboard history menu in the actions bar, it should be the last one in the list. It'll be made a little more prominent by being placed on long-pressing the enter key in the next update

**Comment by Fuoxden** [comment]
Okay! thanks for responding! i Appreciate it!
