### ISSUE TITLE
Fix Internal Voice Input Crashing Issue

### ISSUE THREAD

**Issue by XingShelly** [futo-org/android-keyboard#444]
### What happened?

I am currently trying to use voice input to type issues on GitHub through a Firefox browser, but the internal voice input option keeps crashing the whole keyboard, so I have to resort to external voice input commands.

### Keyboard Version

0.1.23.2

**Comment by MordorMinion** [comment]
Might be same as issue #467

**Comment by dean-futo** [comment]
Consolidated into #664
