### ISSUE TITLE
Option to disable the select language button on the space bar

### ISSUE THREAD

**Issue by laxmanpradhan** [futo-org/android-keyboard#45]
Right now, if you press hold on the space bar, it will pop up an option to change keyboard language. The issue is that, more often than not, when trying to use the "cursor scroll on spacebar swipe" feature, it pops up the keyboard switch dialog instead. 

Being able to scroll back and forth by swiping on the keyboard is a key feature found in FUTO and also other keyboards, however with the dialogue poping up half the time it is very annoying to use. 

A simple option to not have the language switcher on the spacebar would be great to allow swipe to scroll to work correctly.

**Comment by domportera** [comment]
what would be REALLY nice is the ability to assign an arbitrary action to it

**Comment by DavidBevi** [comment]
| | |
|-|-|
| I want to add on this topic. The picture is taken from the [Google Play Store page](https://play.google.com/store/apps/details?id=org.futo.inputmethod.latin.playstore&hl=en_GB&gl=US). </br></br>  This gives me a strong suggestion that the voice-dictation is triggered by holding the spacebar, which makes a lot of sense, and I'd want it. </br></br> I tried lots of things but I don't think it work as the image suggested me. </br></br> Honestly I mega want it, so @devs if you consider reworking the spacebar also consider this option!| ![image](https://github.com/futo-org/android-keyboard/assets/61429850/48a2658e-dd07-4cc0-8655-36b52eaf2cfd) |

**Comment by abb128** [comment]
An option for this will be included in the next release
