### ISSUE TITLE
Fix Spacebar Cursor Direction for Right-to-Left (RTL) Languages

### ISSUE THREAD

**Issue by qdab** [futo-org/android-keyboard#450]
### What happened?

While swiping on the space bar the cursor changes direction opposite from the intended location

Bug footage:
https://github.com/user-attachments/assets/4920ad9c-4132-4019-88a7-e6c5bcf4fded

### Keyboard Version

 v0.1.23.2

### Text field info

Same bug across all text fields.

tested same scenario on IOS keyboard and cursor is agnostic to the language

IOS cursor footage:
https://github.com/user-attachments/assets/7fdc2dca-687d-46d4-bb17-497c09972458

**Comment by qdab** [comment]
> ### What happened?
> 
> Edit: tried to upload but cant for some reason
> 
> While swiping on the space bar the cursor changes direction opposite from the intended location
> 
> Uploading cursor.RTL.bug.mp4…
> https://github.com/user-attachments/assets/4920ad9c-4132-4019-88a7-e6c5bcf4fded
> ### Keyboard Version
> 
> v0.1.23.2
> ### Text field info
> 
> Same bug across all text fields.
> 
> tested same scenario on IOS keyboard and cursor is agnostic to the language
> 
https://github.com/user-attachments/assets/cad48d42-10fa-41b9-b348-7053c84f0cc7

**Comment by AhmadAlHallak** [comment]
Also seeing the same issue on Android (v0.1.23.2)

**Comment by Majoramari** [comment]
Adding to this issue, the keyboard generally doesn't respect the language direction and just sticks to left-to-right. Even if you're typing in Arabic, despite swiping on the spacebar or using the text editor arrows, it always goes in the wrong direction.

**Comment by abb128** [comment]
This should be fixed in nightly
