### ISSUE TITLE
Bulgarian Phonetic alphabet

### ISSUE THREAD

**Issue by MeMeDumDum** [futo-org/android-keyboard#451]
### Language

Bulgarian

### Description

In a previous issue post it was said that the alphabet was there originally but was removed accidentally and that a new update is gonna bring it back, however it is still not there. I don't know if the problem is that I downloaded the app from the gplay store and not from github but it should still be addressed.

**Comment by abb128** [comment]
It will be in the next update, an update just hasn't been released yet
