### ISSUE TITLE
(Question) Does futo keyboard support direct boot with samsung devices? 

### ISSUE THREAD

**Issue by Fuoxden** [futo-org/android-keyboard#46]
Im a samsung user and i hate the samsung keyboard, im gonna uninstall it using canta from F-droid and im hoping to use futo as my default keyboard

**Comment by abb128** [comment]
It doesn't support Direct Boot at the moment and a warning for this is shown when being enabled. If you have a text lockscreen password then you'll need to have a different keyboard installed for entering the text password for the first unlock after reboot. Supporting Direct Boot is a long-term goal on the roadmap

**Comment by Fuoxden** [comment]
Okay! Well i cant wait for when it is someday supported! Thank you for the response!
