### ISSUE TITLE
Add Secure Internal Memory for Commonly Used Words

### ISSUE THREAD

**Issue by onfire60** [futo-org/android-keyboard#463]
### Use Cases

In other keyboards i have used in the past it was helpful when the keyboard would remember words that i commonly used over and over again and gave me predictive suggestions based on those words. If this keyboard could do this but storing those words internally and securely within each device that would be awesome. Also not tracking the typed text on password fields or in private instances in browsers. If this already exists. Let me know.

### Proposal

Swift Keyboard does something like this. But i never really trusted it and how it stored that information. So if that could be recreated here this keyboard would be the ultimate keyboard in my opinion.

**Comment by onfire60** [comment]
Nevermind I see the feature now.

**Comment by dean-futo** [comment]
@onfire60 these features already exist in the keyboard. You can modify your preferences in _Text Prediction_ and _Personal Dictionary_ sections of the settings menu.

**Comment by dean-futo** [comment]
@onfire60 these features already exist in the keyboard. You can modify your preferences in the _Text Prediction_ and _Personal Dictionary_ sections of the settings menu.

**Comment by intgr** [comment]
~~I think this does not exist.~~

~~I wish the keyboard would learn words that I type, that are missing in the dictionary, *without* having to go to settings to add them manually.~~

If I'm wrong, I couldn't find the setting to enable it: could you be more specific?

EDIT: I may have misunderstood the OP. But there's already an issue for my request:  https://github.com/futo-org/android-keyboard/issues/1009
