### ISSUE TITLE
Prevent Auto-Correct from Replacing Common Slang (u, ur)

### ISSUE THREAD

**Issue by caboose16** [futo-org/android-keyboard#464]
### What happened?

Regular uses of "u" and "ur" get changed to "I" and "it" by auto-correction. This is common texting slang that should not be auto corrected.

Examples:

- "Text me when u get home" gets changed to "Text me when I get home"
- "ur really cool" gets changed to "it really cool"

### Keyboard Version

0.1.23.2-playstore

**Comment by Chinoman10** [comment]
Isn't this just a misconfiguration on your 'Personal Dictionary'?

**Comment by caboose16** [comment]
> Isn't this just a misconfiguration on your 'Personal Dictionary'?

I tested this now on a clean install. Issue still occurs. If this is a 'Personal Dictionary' misconfiguration then the default is misconfigured.

**Comment by ryandikdan** [comment]
I've also had this issue, and even when I add a capital 'U' to the personal dictionary, it still consistently corrects it to 'I'. Is there a way to fix this?

**Comment by dean-futo** [comment]
Consolidated into #666

**Comment by dean-futo** [comment]
Very similar to #522 - merging this issue into that one. See that one for details.
