### ISSUE TITLE
Fix Emoji Search for Numbers and Symbols

### ISSUE THREAD

**Issue by bruceschaff** [futo-org/android-keyboard#465]
### What happened?

When searching for emojis numbers do not type out at all, and symbols do not bring up any results.

### Keyboard Version

0.1.23.2-playstore

**Comment by picklelfong** [comment]
This is kinda true. GBoard will pull up a lot more potentially relevant emoji's while this one is a hit or miss. Sometimes i have to temporarily switch keyboards to find an emoji. It's like google has more words to index emoji's or something but I'm not sure how it works.

**Comment by dean-futo** [comment]
Consolidated into #674

**Comment by dean-futo** [comment]
Duplicate of #558 - merging into that issue. See #558 for details.
