### ISSUE TITLE
Add Colemak-DH Keyboard Layout

### ISSUE THREAD

**Issue by Kaya66** [futo-org/android-keyboard#466]
### Language

English

### Description

![maxresdefault-2817836448](https://github.com/user-attachments/assets/eeb82100-edb2-4138-a1e9-3b031f88174f)

I'm hoping it will be a simple modification. Just take the existing layout and move 2 sets of 2 keys  (4 keys moved total)

### Complexity

Simple

Taking an existing layout and moving 4 keys around.

**Comment by Kaya66** [comment]
I'm unsure where the layout files are located though I would be willing to try to build the modification mysel.

**Comment by abb128** [comment]
Fixed in #550
