### ISSUE TITLE
Increase Symbol Hint Size for Improved Visibility

### ISSUE THREAD

**Issue by deadcombo** [futo-org/android-keyboard#47]
Hello, I find the symbol hints rather small and often struggle to tell them apart in less than ideal lighting. Bit bigger would be nice.

Cheers.

**Comment by josb** [comment]
Here's what they look like on SwiftKey using its "Pitch" theme.

**Comment by josb** [comment]
Here's what symbols look like in SwiftKey, using its stock "Pitch" theme:
![20240629_205028](https://github.com/futo-org/android-keyboard/assets/50617/4bcb395e-7527-4b01-94fc-029d95b6fac9)

**Comment by kjkrum** [comment]
This seems related to #90. The main font could be smaller and the hints bigger.

**Comment by dean-futo** [comment]
Duplicate of #769 - merging this request into that one.

**Comment by chileverde** [comment]
@dean-futo, Thanks for merging my issue with the previous one (which I hadn't seen).

Glad to know I'm not the only one who needs this!
