### ISSUE TITLE
Display secondary characters for long press on keyboard.

### ISSUE THREAD

**Issue by hillyarb** [futo-org/android-keyboard#476]
### Use Cases

With the Google keyboard I can see which key I need to long press to access a given character. For example I also shows a smaller ">" in the corner. This makes it much easier and quicker to access special characters, especially ones not used as often. 

![Screenshot_20240815-220356](https://github.com/user-attachments/assets/547c75fd-600b-47ff-a6fe-ac71756220d9)

### Proposal

Just display the common characters on the keyboard. I know long press is used to get to them still because our if habit I still hold m for the question mark.

**Comment by abb128** [comment]
Enable the show hints option in Settings > Keyboard & Typing > Long-press keys
