### ISSUE TITLE
Forced QWERTY at lockscreen

### ISSUE THREAD

**Issue by Kaeptn-G** [futo-org/android-keyboard#477]
### What happened?

I'm in QWERTZ layout with German language and everytime I need to type my password to unlock, Layout is QWERTY without the possibility to change it. Long press space key and "changing" to the only selected layout (QWERTZ) won't have any effect either.

### Keyboard Version

0.1.23.2-playstore

### Text field info

lockscreen only. Cannot Screenshot, as it would be just black.

**Comment by Stylback** [comment]
v.0.1.23.2 (Obtanium), Nordic layout (numeric row-less)

I'm experiencing the same issue where my layout is not respected on the lockscreen, instead defaulting to QWERTY (with numeric row). Opening the layout-switcher using the long-press action on the spacebar shows that I **should** be on Nordic, actually switching layout using the same menu changes the highlight but not the actual layout.

I would paste a screenshot or debug info, if that was possible to capture on the lockscreen (which it does not appear to be).

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.
