### ISSUE TITLE
One-handed mode

### ISSUE THREAD

**Issue by mad1mystic** [futo-org/android-keyboard#48]
Keyboard is really promising testing it out rn, would be really nice to have adjustable width setting to make one hand mode since most phones are really big for one hand , iOS iPhone app would be great too! Thanks for the app , app seems quite stable for an alpha looking forward for more features and development.

**Comment by panicthescaredycat** [comment]
Yea... One handed mode is like a MUST... I really want to use the Z Fold 5, but it's hard when there's no, One Handed :(

**Comment by horiveira** [comment]
This would be great. I'm testing out the keyboard and the lack of one-handed mode is the only thing keeping me from using it as my default.

**Comment by TheSecondPower** [comment]
I think this would be really helpful for swipe typing. This or #184, but theoretically a one-handed "mode" could be turned off quickly if I have a lot I need to type manually, so I think I'd rather have one-handed mode.

**Comment by nortuzar** [comment]
I have a galaxy s22 ultra and this is a must for me in order to use swipe typing, its the only thing that keeps me from using it by default. 
Nice project! Love the privacy focus

**Comment by lavenderdotpet** [comment]
Please add this its a must have on big phones with small hands

**Comment by abb128** [comment]
One handed mode has been implemented in nightly and it will be part of the next release
