### ISSUE TITLE
Integrate LanguageTool for Grammar and Style Checks

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/android-keyboard#482]
### Use Cases

[LanguageTool](https://languagetool.org/) is a free, open source grammar checker

### Proposal

Basically, you can add a new LanguageTool section which includes a username/email, API key, and API endpoint.

Samsung keyboard has grammarly integration, and gboard has a proprietary grammar checker, both of which use a blue underline to indicate grammer problems similar to how spellcheck is in red.

The plugin for Obsidian, a markdown note taker, has the following options
- **User details**
  - Endpoint; Endpoint that will be used to make requests to
    - (Standard) https://api.languagetool.org
    - (Premium) https://api.languagetoolplus.com
    - (Custom)
  - API Username; Enter a username/email for API access (not needed for standard)
  - API Key; Enter an API key (not needed for standard)
- **General**
  - Autocheck text; Check text as you type
  - Autocheck delay; Length of time to wait for Autocheck after last keypress
  - Static Language; Set a static language that wil always be used. (LanguageTool tries to auto detect the language, this is usually not necessary)
  - Mother Tongue; Set the language you are most comfortable with. This will be used to interpret the language you are writing in
- **Language Variety Selector**
  - English
    - USA
    - British
    - Canada
    - Australia
    - New Zealand
    - South Africa
  - German
    - Germany
    - Switzerland
    - Austria
  - Portuguese
    - Portugal
    - Brazil
    - Angola
    - Mozambique
  - Catalan
    - Catalonia
    - Valencia
- **Rules & Categories**
  - Picky mode; Provides more style and tonality suggestions, detects long or complex sentences, recognices colloqualism and reduundancies, proactively suggests synonyms for commonly used words
  - Other rule categories; comma separated  |  [Rules](https://community.languagetool.org/rule/list)
  - Enable specific rules; comma separated
  - Disable specific rules; comma separated

### References

``

**Comment by dean-futo** [comment]
@VoxelPrismatic thanks for your request but these types of integrations require sending text input to external servers, which isn't privacy preserving. We're still getting auto-correct right, but perhaps we could look into incorporating our own grammar check algorithm down the road.
