### ISSUE TITLE
voice input crash

### ISSUE THREAD

**Issue by xunil89** [futo-org/android-keyboard#49]
`{"REPORT_ID":"7c50cb3a-c699-4ede-9500-2fa445da2e4f","APP_VERSION_CODE":10804,"APP_VERSION_NAME":"0.1.22","PACKAGE_NAME":"org.futo.inputmethod.latin","FILE_PATH":"\/data\/user\/0\/org.futo.inputmethod.latin\/files","PHONE_MODEL":"Redmi Note 9 Pro","BRAND":"Redmi","PRODUCT":"lineage_miatoll","ANDROID_VERSION":"13","BUILD":{"BOARD":"atoll","BOOTLOADER":"unknown","BRAND":"Redmi","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"joyeuse","DISPLAY":"TQ3A.230901.001","FINGERPRINT":"Redmi\/joyeuse_global\/joyeuse:12\/RKQ1.211019.001\/V14.0.3.0.SJZMIXM:user\/release-keys","HARDWARE":"qcom","HOST":"android-build","ID":"TQ3A.230901.001","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Xiaomi","MODEL":"Redmi Note 9 Pro","ODM_SKU":"nfc","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"lineage_miatoll","RADIO":"unknown","SKU":"unknown","SOC_MANUFACTURER":"QTI","SOC_MODEL":"SM7125","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1697302097000,"TYPE":"user","UNKNOWN":"unknown","USER":"nobody","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"94","KNOWN_CODENAMES":"{HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"13","RELEASE_OR_CODENAME":"13","RELEASE_OR_PREVIEW_DISPLAY":"13","SDK":"33","SDK_INT":33,"SECURITY_PATCH":"2023-10-06"}},"TOTAL_MEM_SIZE":112419729408,"AVAILABLE_MEM_SIZE":45787176960,"BUILD_CONFIG":"N\/A","CUSTOM_DATA":{"defer_manual_update_until":"1720723809616","dismissedMigrateFdroidObtainiumNotice":"true","resource_VoiceInput_it_IT":"voiceinput_it_IT.bin","last_used_emoji":"😂<|>😂<|>😂<|>🤷🏻‍♂️<|>🤦🏻‍♂️<|>🙂<|>🙂<|>😂<|>🤷🏻‍♂️<|>🤦🏻‍♂️<|>🤦🏻‍♂️<|>🤷🏻‍♂️<|>🤣<|>🤣<|>🤦🏻‍♂️<|>🤦🏻‍♂️<|>😁<|>🤣<|>🤣<|>🤦🏻‍♂️<|>🤣<|>🤣<|>🤣<|>🤣<|>🤣<|>🤣<|>🤷🏻‍♂️<|>🤦🏻‍♂️<|>🤷🏻‍♂️<|>🤣<|>🤣<|>🤣<|>🤣<|>🤣<|>🤣<|>😅<|>😍<|>😍<|>🤷🏻‍♂️<|>","subtypes":"[it_IT:KeyboardLayoutSet=qwerty:]","last_update_check_failed":"true","last_version":"10804","prefer_bluetooth_recording":"false","activeThemeOption":"DynamicSystem","activeSubtype":"it_IT:KeyboardLayoutSet=qwerty:","keyHints":"true","verbose_progress":"true","keyboardHeightMultiplier":"0.9"},"IS_SILENT":false,"STACK_TRACE":"java.lang.IllegalArgumentException: The Whisper model could not be loaded from the given buffer\n\tat org.futo.voiceinput.shared.ggml.WhisperGGML.<init>(SourceFile:30)\n\tat org.futo.voiceinput.shared.types.ModelFileFile.loadGGML(SourceFile:40)\n\tat org.futo.voiceinput.shared.whisper.ModelManager.obtainModel(SourceFile:16)\n\tat org.futo.voiceinput.shared.whisper.MultiModelRunner$preload$2$1.invokeSuspend(SourceFile:14)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)\n\tat kotlinx.coroutines.DispatchedTask.run(SourceFile:115)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)\n\tSuppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f553ec7, Dispatchers.Main.immediate]\n","INITIAL_CONFIGURATION":{"colorMode":5,"densityDpi":396,"fontScale":1,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"it_IT","mcc":222,"mnc":10,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":880,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":436,"seq":3015,"smallestScreenWidthDp":436,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":false},"CRASH_CONFIGURATION":{"colorMode":5,"densityDpi":396,"fontScale":1,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"it_IT","mcc":222,"mnc":10,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":880,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":436,"seq":3015,"smallestScreenWidthDp":436,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":false},"DISPLAY":{"0":{"currentSizeRange":{"smallest":[1080,1011],"largest":[2179,2179]},"flags":"FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE","metrics":{"density":2.4750001430511475,"densityDpi":396,"scaledDensity":"x2.4750001","widthPixels":1080,"heightPixels":2179,"xdpi":397.56500244140625,"ydpi":395.843994140625},"realMetrics":{"density":2.4750001430511475,"densityDpi":396,"scaledDensity":"x2.4750001","widthPixels":1080,"heightPixels":2400,"xdpi":397.56500244140625,"ydpi":395.843994140625},"name":"Schermo incorporato","realSize":[1080,2400],"rectSize":[0,0,1080,2179],"size":[1080,2179],"rotation":"ROTATION_0","isValid":true,"orientation":0,"refreshRate":60.000003814697266,"height":2179,"width":1080,"pixelFormat":1}},"USER_COMMENT":"","USER_EMAIL":"","USER_APP_START_DATE":"2024-06-27T20:50:14.952+02:00","USER_CRASH_DATE":"2024-06-27T20:50:20.945+02:00","DUMPSYS_MEMINFO":"","LOGCAT":"06-27 20:50:13.736 V\/GraphicsEnvironment( 2614): Neither updatable production driver nor prerelease driver is supported.\n06-27 20:50:13.791 W\/Parcel  ( 2614): Expecting binder but got null!\n06-27 20:50:13.816 W\/Parcel  ( 2614): Expecting binder but got null!\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): QUALCOMM build                   : 83a0eede45, If3f4a1ab82\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Build Date                       : 11\/18\/21\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): OpenGL ES Shader Compiler Version: EV031.32.02.15\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Local Branch                     : \n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Remote Branch                    : refs\/tags\/AU_LINUX_ANDROID_LA.UM.9.1.R1.11.00.00.604.070\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Remote Branch                    : NONE\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Reconstruct Branch               : NOTHING\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Build Config                     : S P 10.0.6 AArch64\n06-27 20:50:13.841 I\/AdrenoGLES-0( 2614): Driver Path                      : \/vendor\/lib64\/egl\/libGLESv2_adreno.so\n06-27 20:50:13.846 I\/AdrenoGLES-0( 2614): PFP: 0x016ee190, ME: 0x00000000\n06-27 20:50:13.859 E\/OpenGLRenderer( 2614): Unable to match the desired swap behavior.\n06-27 20:50:13.866 I\/Gralloc4( 2614): Adding additional valid usage bits: 0x8202000\n06-27 20:50:13.912 E\/OpenGLRenderer( 2614): Unable to match the desired swap behavior.\n06-27 20:50:14.841 E\/putmethod.latin( 2651): Not starting debugger since process cannot load the jdwp agent.\n06-27 20:50:14.936 V\/GraphicsEnvironment( 2651): ANGLE Developer option for 'org.futo.inputmethod.latin' set to: 'default'\n06-27 20:50:14.937 V\/GraphicsEnvironment( 2651): ANGLE GameManagerService for org.futo.inputmethod.latin: false\n06-27 20:50:14.937 V\/GraphicsEnvironment( 2651): Neither updatable production driver nor prerelease driver is supported.\n06-27 20:50:14.947 I\/ACRA    ( 2651): ACRA is enabled for org.futo.inputmethod.latin, initializing...\n06-27 20:50:14.957 D\/WM-WrkMgrInitializer( 2651): Initializing WorkManager with default configuration.\n06-27 20:50:14.960 D\/WM-PackageManagerHelper( 2651): Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService\n06-27 20:50:14.961 D\/WM-Schedulers( 2651): Created SystemJobScheduler and enabled SystemJobService\n06-27 20:50:14.970 I\/LatinIMELegacy( 2651): Hardware accelerated drawing: true\n06-27 20:50:15.016 W\/InputAttributes( 2651): No editor info for this field. Bug?\n06-27 20:50:15.021 I\/LatinIME:LogUtils( 2651): Dictionary info: dictionary = UserHistoryDictionary.it_IT ; version = 1718305385 ; date = 1719506799\n06-27 20:50:15.021 I\/LatinIME:LogUtils( 2651): Dictionary info: dictionary = userunigram.it_IT ; version = 1718301061 ; date = 1718301061\n06-27 20:50:15.022 D\/LanguageModelFacilitator( 2651): Starting processor\n06-27 20:50:15.025 I\/LatinIME:LogUtils( 2651): Dictionary info: dictionary = main:it ; version = 54 ; date = 1414726258\n06-27 20:50:15.028 I\/UpdateChecking( 2651): Job already scheduled, no need to do anything\n06-27 20:50:15.032 W\/InputAttributes( 2651): No editor info for this field. Bug?\n06-27 20:50:15.050 W\/Parcel  ( 2651): Expecting binder but got null!\n06-27 20:50:17.043 I\/LatinIMELegacy( 2651): Timeout waiting for dictionary load\n06-27 20:50:19.294 D\/OpenGLRenderer( 2614): endAllActiveAnimators on 0xb4000070360fdf00 (RippleDrawable) with handle 0xb400006fce4df840\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): QUALCOMM build                   : 83a0eede45, If3f4a1ab82\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): Build Date                       : 11\/18\/21\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): OpenGL ES Shader Compiler Version: EV031.32.02.15\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): Local Branch                     : \n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): Remote Branch                    : refs\/tags\/AU_LINUX_ANDROID_LA.UM.9.1.R1.11.00.00.604.070\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): Remote Branch                    : NONE\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): Reconstruct Branch               : NOTHING\n06-27 20:50:19.366 I\/AdrenoGLES-0( 2651): Build Config                     : S P 10.0.6 AArch64\n06-27 20:50:19.367 I\/AdrenoGLES-0( 2651): Driver Path                      : \/vendor\/lib64\/egl\/libGLESv2_adreno.so\n06-27 20:50:19.372 I\/AdrenoGLES-0( 2651): PFP: 0x016ee190, ME: 0x00000000\n06-27 20:50:19.389 E\/OpenGLRenderer( 2651): Unable to match the desired swap behavior.\n06-27 20:50:19.393 I\/Gralloc4( 2651): Adding additional valid usage bits: 0x8202000\n06-27 20:50:19.422 W\/LatinIME( 2651): Create input view\n06-27 20:50:19.483 I\/LatinIMELegacy( 2651): Starting input. Cursor position = 0,0\n06-27 20:50:19.603 D\/LanguageModelFacilitator( 2651): Calling closeInternalLocked on model due to seeming locale change\n06-27 20:50:19.604 D\/LanguageModelFacilitator( 2651): no model for it\n06-27 20:50:20.273 D\/ProfileInstaller( 2651): Skipping profile installation for org.futo.inputmethod.latin\n06-27 20:50:20.571 D\/MediaCodecList( 2651): codecHandlesFormat: no format, so no extra checks\n06-27 20:50:20.571 D\/MediaCodecList( 2651): codecHandlesFormat: no format, so no extra checks\n06-27 20:50:20.571 D\/MediaCodecList( 2651): codecHandlesFormat: no format, so no extra checks\n06-27 20:50:20.572 D\/MediaCodecList( 2651): codecHandlesFormat: no format, so no extra checks\n06-27 20:50:20.574 I\/OMXClient( 2651): IOmx service obtained\n06-27 20:50:20.577 D\/MediaCodec( 2651): flushMediametrics\n06-27 20:50:20.592 I\/OMXClient( 2651): IOmx service obtained\n06-27 20:50:20.595 D\/MediaCodec( 2651): flushMediametrics\n06-27 20:50:20.602 D\/MediaCodec( 2651): flushMediametrics\n06-27 20:50:20.614 D\/MediaCodec( 2651): flushMediametrics\n06-27 20:50:20.706 D\/LOG_TAG ( 2651): WebRtcVad success\n06-27 20:50:20.706 I\/System.out( 2651): Resulting handle is -5476376666984957184\n06-27 20:50:20.737 I\/LatinIME: ( 2651): Attempting to load model from buffer...\n06-27 20:50:20.738 I\/LatinIME: ( 2651): whisper_init_from_buffer_with_params_no_state: loading model from buffer\n06-27 20:50:20.738 I\/LatinIME: ( 2651): whisper_model_load: loading model\n06-27 20:50:20.739 I\/LatinIME: ( 2651): whisper_model_load: n_vocab       = 51865\n06-27 20:50:20.739 I\/LatinIME: ( 2651): whisper_model_load: n_audio_ctx   = 1500\n06-27 20:50:20.740 I\/LatinIME: ( 2651): whisper_model_load: n_audio_state = 768\n06-27 20:50:20.740 I\/LatinIME: ( 2651): whisper_model_load: n_audio_head  = 12\n06-27 20:50:20.740 I\/LatinIME: ( 2651): whisper_model_load: n_audio_layer = 12\n06-27 20:50:20.740 I\/LatinIME: ( 2651): whisper_model_load: n_text_ctx    = 448\n06-27 20:50:20.740 I\/LatinIME: ( 2651): whisper_model_load: n_text_state  = 768\n06-27 20:50:20.741 I\/LatinIME: ( 2651): whisper_model_load: n_text_head   = 12\n06-27 20:50:20.741 I\/LatinIME: ( 2651): whisper_model_load: n_text_layer  = 12\n06-27 20:50:20.741 I\/LatinIME: ( 2651): whisper_model_load: n_mels        = 80\n06-27 20:50:20.741 I\/LatinIME: ( 2651): whisper_model_load: ftype         = 7\n06-27 20:50:20.741 I\/LatinIME: ( 2651): whisper_model_load: qntvr         = 2\n06-27 20:50:20.742 I\/LatinIME: ( 2651): whisper_model_load: type          = 3 (small)\n06-27 20:50:20.809 I\/LatinIME: ( 2651): whisper_model_load: adding 1607 extra tokens\n06-27 20:50:20.810 I\/LatinIME: ( 2651): whisper_model_load: n_langs       = 99\n06-27 20:50:20.811 I\/LatinIME: ( 2651): whisper_model_load:      CPU buffer size =   277.87 MB\n06-27 20:50:20.875 I\/LatinIME: ( 2651): whisper_model_load: model size    =  105.46 MB\n06-27 20:50:20.875 E\/LatinIME: ( 2651): whisper_model_load: ERROR not all tensors loaded from model file - expected 479, got 167\n06-27 20:50:20.876 E\/LatinIME: ( 2651): whisper_init_with_params_no_state: failed to load model\n06-27 20:50:20.898 E\/LatinIME: ( 2651): whisper_init_from_buffer_with_params: received null context\n06-27 20:50:20.898 E\/LatinIME: ( 2651): Failed to initialize whisper_context from direct buffer\n06-27 20:50:20.902 E\/ACRA    ( 2651): ACRA caught a IllegalArgumentException for org.futo.inputmethod.latin\n06-27 20:50:20.902 E\/ACRA    ( 2651): java.lang.IllegalArgumentException: The Whisper model could not be loaded from the given buffer\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat org.futo.voiceinput.shared.ggml.WhisperGGML.<init>(SourceFile:30)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat org.futo.voiceinput.shared.types.ModelFileFile.loadGGML(SourceFile:40)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat org.futo.voiceinput.shared.whisper.ModelManager.obtainModel(SourceFile:16)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat org.futo.voiceinput.shared.whisper.MultiModelRunner$preload$2$1.invokeSuspend(SourceFile:14)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat kotlinx.coroutines.DispatchedTask.run(SourceFile:115)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)\n06-27 20:50:20.902 E\/ACRA    ( 2651): \tSuppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f553ec7, Dispatchers.Main.immediate]\n06-27 20:50:20.891 W\/logcat  ( 2916): type=1400 audit(0.0:16887): avc: denied { read } for name=\"audio.primary.atoll.so\" dev=\"dm-1\" ino=842 scontext=u:r:untrusted_app:s0:c159,c258,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0 app=org.futo.inputmethod.latin\n","INSTALLATION_ID":"9b042c11-6c31-49e6-9093-1db11b542b02","DEVICE_FEATURES":{"android.hardware.sensor.proximity":true,"android.software.adoptable_storage":true,"android.hardware.sensor.accelerometer":true,"android.software.controls":true,"android.hardware.faketouch":true,"android.software.telecom":true,"android.hardware.telephony.subscription":true,"android.hardware.usb.accessory":true,"android.hardware.telephony.cdma":true,"android.hardware.telephony.data":true,"android.software.backup":true,"android.hardware.touchscreen":true,"android.hardware.touchscreen.multitouch":true,"android.software.print":true,"android.hardware.consumerir":true,"android.software.activities_on_secondary_displays":true,"android.hardware.wifi.rtt":true,"com.google.android.feature.PIXEL_2017_EXPERIENCE":true,"android.software.voice_recognizers":true,"android.software.picture_in_picture":true,"android.hardware.fingerprint":true,"android.hardware.sensor.gyroscope":true,"android.hardware.audio.low_latency":true,"android.software.vulkan.deqp.level":true,"android.software.cant_save_state":true,"com.google.android.feature.PIXEL_2018_EXPERIENCE":true,"android.hardware.security.model.compatible":true,"android.hardware.telephony.messaging":true,"android.hardware.telephony.calling":true,"android.hardware.opengles.aep":true,"org.lineageos.livedisplay":true,"org.lineageos.profiles":true,"android.hardware.bluetooth":true,"android.software.window_magnification":true,"android.hardware.telephony.radio.access":true,"android.hardware.camera.autofocus":true,"com.google.android.feature.GOOGLE_BUILD":true,"android.hardware.telephony.gsm":true,"android.hardware.telephony.ims":true,"android.software.incremental_delivery":true,"android.software.sip.voip":true,"android.hardware.se.omapi.ese":true,"android.software.opengles.deqp.level":true,"com.google.android.apps.photos.NEXUS_PRELOAD":true,"android.hardware.usb.host":true,"android.hardware.audio.output":true,"android.software.verified_boot":true,"android.hardware.camera.flash":true,"android.hardware.camera.front":true,"android.hardware.se.omapi.uicc":true,"android.hardware.screen.portrait":true,"android.hardware.nfc":true,"com.google.android.feature.TURBO_PRELOAD":true,"com.nxp.mifare":true,"android.hardware.sensor.stepdetector":true,"android.software.home_screen":true,"android.hardware.microphone":true,"android.software.autofill":true,"org.lineageos.hardware":true,"org.lineageos.globalactions":true,"android.software.securely_removes_users":true,"com.google.android.feature.PIXEL_EXPERIENCE":true,"android.hardware.bluetooth_le":true,"android.hardware.sensor.compass":true,"android.hardware.touchscreen.multitouch.jazzhand":true,"android.software.app_widgets":true,"android.software.input_methods":true,"android.hardware.sensor.light":true,"android.hardware.vulkan.version":true,"android.software.companion_device_setup":true,"android.software.device_admin":true,"com.google.android.feature.WELLBEING":true,"android.hardware.wifi.passpoint":true,"android.hardware.camera":true,"com.google.android.feature.ZERO_TOUCH":true,"org.lineageos.trust":true,"android.hardware.screen.landscape":true,"android.software.device_id_attestation":true,"android.hardware.ram.normal":true,"org.lineageos.health":true,"com.google.android.apps.photos.nexus_preload":true,"org.lineageos.android":true,"android.software.managed_users":true,"android.software.webview":true,"android.hardware.sensor.stepcounter":true,"android.hardware.camera.capability.manual_post_processing":true,"android.hardware.camera.any":true,"android.hardware.camera.capability.raw":true,"android.hardware.vulkan.compute":true,"android.hardware.touchscreen.multitouch.distinct":true,"android.hardware.location.network":true,"android.software.cts":true,"android.software.sip":true,"android.hardware.camera.capability.manual_sensor":true,"android.software.app_enumeration":true,"com.google.android.apps.dialer.SUPPORTED":true,"android.hardware.camera.level.full":true,"android.hardware.wifi.direct":true,"android.software.live_wallpaper":true,"com.google.android.feature.GOOGLE_EXPERIENCE":true,"android.software.ipsec_tunnels":true,"com.google.android.feature.EXCHANGE_6_2":true,"org.lineageos.settings":true,"android.hardware.audio.pro":true,"android.hardware.nfc.hcef":true,"android.hardware.nfc.uicc":true,"android.hardware.location.gps":true,"android.sofware.nfc.beam":true,"android.software.midi":true,"android.hardware.nfc.any":true,"android.hardware.nfc.hce":true,"android.hardware.wifi":true,"android.hardware.location":true,"android.hardware.vulkan.level":true,"android.hardware.wifi.aware":true,"android.software.secure_lock_screen":true,"android.hardware.biometrics.face":true,"android.hardware.telephony":true,"android.software.file_based_encryption":true,"glEsVersion":"3.2"},"ENVIRONMENT":null,"SHARED_PREFERENCES":{"default":{"vibrate_on":false,"pref_vibration_duration_settings":-1,"pref_enable_number_row":false}}}`

**Comment by abb128** [comment]
It looks like the model may be corrupt. Try downloading it again? Where did you download it from?

**Comment by xunil89** [comment]
perfect seems to work, I reloaded the template from the site futo

29 giu 2024 22:14:41 abb128 ***@***.***>:
