### ISSUE TITLE
Incorrect Character Options for Long-Press on Period Key in Spanish Layout

### ISSUE THREAD

**Issue by ismawork** [futo-org/android-keyboard#490]
### What happened?

When I select Spanish language, if I keep pressed the "."  I get an overlay with different keys. But one of them, shows two characters instead of just one ",?".  If I select that one it writes ",?" 

### Keyboard Version

0.1.23-2-playstore

**Comment by CaffiendDevKit** [comment]
Having the same issue, adding in some screenshots just for clarification.

How it currently looks in Futo keyboard
![Screenshot_20240829-225733~2](https://github.com/user-attachments/assets/4e15def6-1b12-4cf9-8607-cba0df0da35b)

How it looks in another keyboard from a native Spanish speaker
![Screenshot_20240829-230121~2](https://github.com/user-attachments/assets/ea6dd6f2-021a-43c8-a331-956586da829c)

**Comment by abb128** [comment]
Fixed in 0.1.24
