### ISSUE TITLE
Double tap shift activates caps lock

### ISSUE THREAD

**Issue by Imold** [futo-org/android-keyboard#491]
### Use Cases

Other keyboards activate caps lock by double tapping shift. This is faster then long pressing shift, and new users accustomed to double tapping shift wouldn't struggle to figure out how to activate caps lock. 

I know I had issues with it, although now that I've figured out I have to hold shift it's only an inconvenience.

**Comment by ajensen1234** [comment]
I'm quite certain THIS KEYBOARD works by DOUBLE tapping SHIFT, not Holding Shift.

(This comment was typed on this keyboard, double tapping to achieve the caps lock).
When I tried holding shift, it only capitalized the next letter ("Holding Shift").

I'm on v1.23.2

**Comment by Imold** [comment]
huh it does work, no idea why it didn't before weird. Well then closed.
