### ISSUE TITLE
Allow User-Customizable Keyboard Layouts

### ISSUE THREAD

**Issue by S7venLights** [futo-org/android-keyboard#493]
### Use Cases

For a long time I have used a customizable keyboard called MultilingO keyboard (hardly maintained anymore).
Since one of the descriptors for FUTO keyboard is customizable, why dot make it fully customizable.
This way users can create and share layouts tuned to their exact needs and this would make UX issues user solvable.

### Proposal

[Multiling O keyboard](https://play.google.com/store/apps/details?id=kl.ime.oh&hl=en) is very lightweight, almost everything is fully customizable, everything can be backed up and exported and it has a simple enough way of making layouts with text files.I share some here:
https://telegra.ph/Customizable-1337Leet-Keyboard-Layouts-02-25
But someone also made [a tool](https://web.archive.org/web/20200129121333/https://ok-layout.appspot.com/le.html) to output layouts for you.
It also has a better way of using the suggestion bar as a customizable button/shortcuts bar when you're not typing (meaning less vertical space is used up). And you can use various swipes and long presses to access different layouts with useful functions.
This is my optimal layout (although if I had swipe spacebar, I wouldn't use the arrows) (I set long press to be Caps as most common symbols needed are in the number row)
![image](https://github.com/user-attachments/assets/e95df3c6-c749-4050-9453-7398ceec5c6f)

[Unexpected keyboard](https://github.com/Julow/Unexpected-Keyboard) is also very interesting and has an [easy way to make layouts](https://unexpected-keyboard-layout-editor.lixquid.com/).

See more customizable keyboards for inspiration on how to allow customization:
https://github.com/Helium314/HeliBoard
https://www.keyboarddesigner.com/
https://keyman.com/developer

BTW, if FUTO wants to enable E2EE across any communication apps, see if you can implement anything like this (doesn't require internet permission):
https://www.oversec.io/
or https://github.com/amnesica/KryptEY

Other useful/interesting links:
[Telegram channel](https://t.me/CompLeetKeys) where I post my findings.
https://play.google.com/store/apps/details?id=com.usr.dict.mgr
https://cryptoji.com/
https://f-droid.org/packages/mf.asciitext.lite

### References

https://github.com/futo-org/android-keyboard/issues/434 This user could make what he wants with a customizable app.

**Comment by Chinoman10** [comment]
This would make migrations very easy! I'm currently struggling with Swiftkey to FUTO...

**Comment by AntiSol** [comment]
Hello, is this really "high complexity"? I was just reading about custom layouts in the futo-keyboard-layouts repo. It says there that custom layouts are enabled in the developer menu in the nightly builds of futo-keyboard. 

I came here to ask for that feature to be enabled for use in the standard (i.e not-nightly) builds, too. It seems like that should be pretty simple, no? Or am I misunderstanding something?

**Comment by abb128** [comment]
Custom layouts have indeed been added to nightly and the feature will be available in the next stable release

**Comment by AntiSol** [comment]
I've been experimenting with the nightly build, it works great! Thank you.

**Comment by abb128** [comment]
> Where are we to report bugs in and make non-layout feature requests for this? Here or the other repo?

If you're reporting a missing layout, a layout change request, a layout engine bug, or layout engine feature request or limitation (i.e. you can't express your desired layout under the system), you can report it in https://github.com/futo-org/futo-keyboard-layouts/issues

Otherwise here is fine. Issues can be transferred between repos as well
