### ISSUE TITLE
Add Feature to Input Current Location

### ISSUE THREAD

**Issue by Philippe-Choquette** [futo-org/android-keyboard#496]
### Use Cases

Many messaging apps allow you to share your current location with the one you're conversing with. This is useful to plan meetings, indicate where you are to get picked up, etc.

However, some messaging apps lack this capability (i.e., Google Chat). As such, having a built-in way to input your current location data would be useful through FUTO keyboard.

### Proposal

Implement a way to quickly input your current location through FUTO keyboard.

This is the only keyboard that I could find on Android that baked in such a feature:
https://altkeys.ai/features.html

It basically invokes the share menu with a Google Maps URL to your current coordinates. This is just one way to do it, and I guess there would be others, but it's a starting point for inspiration.

**Comment by dean-futo** [comment]
@Philippe-Choquette thanks for your request but this is still more of a messaging app feature than a keyboard feature, even though not all of them implement it.
