### ISSUE TITLE
Conflicting Gestures

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#5]
https://github.com/futo-org/android-keyboard/assets/157768191/a31c518d-9a51-4f86-a1a6-d3a15017d5aa

When swiping from the symbols button or the caps button, if you touch a button that uses cursor control it breaks and gets stuck

Solution idea:
Disable cursor control gestures for space bar and backspace when any other gesture is active

**Comment by abb128** [comment]
Should be fixed by now
