### ISSUE TITLE
QWERTZ layout long-press number 6 in wrong location

### ISSUE THREAD

**Issue by sticnick** [futo-org/android-keyboard#505]
### What happened?

When using QWERTZ layouts (in Czech and German for sure, maybe others) the  positions of the keys for the letters Y and Z are sawapped compared to the QWERTY layout, but the punctuation and numbers also are swapped for long-press. The number 6 long-press should be swapped to the Z in QWERTZ.
![Futo Keyboard QWERTZ](https://github.com/user-attachments/assets/ec84878f-5d8a-4689-9a74-ea18dcb345d5)

### Keyboard Version

0.1.23

**Comment by abb128** [comment]
You're on 0.1.23, not 0.1.23.2? I believe this was one of the bugs that was resolved in 0.1.23.2

**Comment by sticnick** [comment]
Oh yes you're right, my apologies. I had to download the new apk because f-droid said it was up to date already on 0.1.23
