### ISSUE TITLE
word prediction above the key the word starts with; usimg swipe to select

### ISSUE THREAD

**Issue by Rohan-B-97** [futo-org/android-keyboard#506]
### Use Cases

Word prediction with more than 3 suggestions. And easier to select because the next letter the user is looking for will have the predection right above it. It can be used to type faster without having to look up at the three predictions.

Here's an example of how it looks on on the BlackBerry keyboard.

https://github.com/user-attachments/assets/08191043-eb1e-4555-ac26-1ff4c6bded15

### Proposal

Add word prediction that's attached above the letter the word starts with; whichcan be selected by swiping up.

**Comment by abb128** [comment]
This was brought up before and I believe the conclusion was that this particular design couldn't be implemented due to a design patent by Blackberry. I believe this was the patent https://patents.google.com/patent/US9122672B2
