### ISSUE TITLE
Floating keyboard option for landscape mode

### ISSUE THREAD

**Issue by xlirate** [futo-org/android-keyboard#508]
### Use Cases

Many apps that operate in landscape mode expect the user to have G-board's floating keyboard instead of the more classical keyboard-tray layout. These apps can react in unpredictable or unusable ways.

Discord is one such app

This is how it reacts to G-board:
![g-board](https://github.com/user-attachments/assets/7c9d95ea-242f-488b-8454-373709887e91)

This is how it reacts to Futo's andriod keyboard
![futo-board](https://github.com/user-attachments/assets/14802f25-e93b-4914-9e76-4204a8fa75fc)

**Comment by abb128** [comment]
Duplicate of #301
