### ISSUE TITLE
Long-press buttons color issue when force-dark enabled

### ISSUE THREAD

**Issue by KaKi87** [futo-org/android-keyboard#509]
### What happened?

Long-press buttons are wrongly colored when Android's force-dark option is enabled.

| Force-dark disabled | Force-dark enabled |
| --- | --- |
| ![Screenshot_20240827-212843_FUTO Keyboard](https://github.com/user-attachments/assets/4ff7b7fd-5e42-4217-9c8f-1ae47422b04d) | ![Screenshot_20240827-212754_FUTO Keyboard](https://github.com/user-attachments/assets/24bb044c-f1ea-4edf-8ce6-52b94acd3775) |

### Keyboard Version

0.1.23.2

### Text field info

Any

---
Thanks

**Comment by abb128** [comment]
This will be fixed in the next release as part of a refactor

**Comment by KaKi87** [comment]
Could you please reference this issue when the fix will be committed ? Thanksco

**Comment by abb128** [comment]
It's already committed just wasn't pushed until now. If you're building from source keep in mind the current master might not be very stable, the layout system is in the middle of a migration and some layouts and features are still missing

**Comment by KaKi87** [comment]
Actually I'm just curious about the implementation of the fix. Thanks
