### ISSUE TITLE
[Bug] List of languages shows extra text relating to locale settings

### ISSUE THREAD

**Issue by null-von-sushi** [futo-org/android-keyboard#51]
Phone: Pixel 6 Pro
OS: Graphene OS (build 2024062700)
FUTO Keyboard version: 0.1.22 (versionCode 10804)

<table><tbody><tr>
<td><details><summary>Screenshot of bug</summary>

![bug](https://github.com/futo-org/android-keyboard/assets/13616397/a01ac73e-cebe-4ae4-b6f8-e202d8aa7d9f)
![bug2](https://github.com/futo-org/android-keyboard/assets/13616397/eb53bcaa-8333-4237-a309-819c9c1e47fe)
</details></td>
</tr></tbody></table>

It seems that the list of languages which is automatically added (presumably based on the list of languages configured on the device) shows unnecessary locale related codes at the end.

On my device I had the following selected under System Settings ->  System -> Languages:
- System Languages:
  - English (United Kingdon)
  - 繁體中文 （臺灣）
  - Deutsch (Deutschland)
- Regional preferences:
  - Temperature: Celsius (°C)
  - First day of the week: Monday
    
My timezone is set to automatic (GMT+1) but I doubt it's that.

Please note that the extra text is not shown if I manually add a language in the FUTO keyboard settings, it only shows for language automatically added after a fresh install, and it shows as the default value in the dropdown to pick your language.

**Comment by abb128** [comment]
This bug will be fixed in the next release
