### ISSUE TITLE
Holding backspace to delete one word at a time

### ISSUE THREAD

**Issue by gouravkr** [futo-org/android-keyboard#511]
### Use Cases

When holding the backspace key over a long text, the deletion rate speeds up. This makes it difficult to stop at a precise location. SwiftKey's deletion works better where it deletes one word at a time.

This could be an option in settings instead of the default behavior. 

### Proposal

This is the default behavior in SwiftKey
https://github.com/user-attachments/assets/46544502-6e38-4c71-a472-b4c1705c1ab9

**Comment by abb128** [comment]
There's already an option to configure long-press backspace to delete words instead of letters in keyboard settings if that's what you're asking

**Comment by gouravkr** [comment]
Thanks, I trawled through the settings before posting, but somehow missed this. 

For anyone coming here later, you can find it under Keyboard and typing > Long press keys and spacebar > Backspace behavior when holding/typing
