### ISSUE TITLE
Improved comma placement

### ISSUE THREAD

**Issue by MXC48** [futo-org/android-keyboard#514]
### Use Cases

It would be nice if when I put a comma it automatically stuck to the previously written word. Sometimes it can happen that by going too fast you put an extra space and then you have to go back and so on to put the comma.
I know that swiftkey already does this and I've found it a great feature.

**Comment by Chinoman10** [comment]
Came here to request this! Glad someone already did it... So I'm here to show my support haha :100:

**Comment by MXC48** [comment]
The new automatic punctuation placement feature is great!
It's perfect for English, but has a few problems for French 😅
In English, all punctuation is systematically stuck to the last word. But in French, ?!: have a space between them and the word preceding them... On the other hand, all other punctuation is placed as in English

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.
