### ISSUE TITLE
Add Support for Email Addresses in Dictionary Predictions

### ISSUE THREAD

**Issue by Dan-Burgess** [futo-org/android-keyboard#515]
### Use Cases

Email addresses are commonly used strings that are resistant to prediction. Futo allows these to be added to a dictionary but they do not show up in predictions.

### Proposal

Allow prediction of strings containing non-alphanumeric characters.

**Comment by weedy** [comment]
#248

**Comment by dean-futo** [comment]
@weedy this is indeed a duplicate of #248. Merging this request into that one.
