### ISSUE TITLE
Keyboard width

### ISSUE THREAD

**Issue by Majester** [futo-org/android-keyboard#518]
### Use Cases

Add the option to pad the keyboard width or key width. Many phone covers have a ridge making tapping the edge keys accurately difficult. Sreen protectors are narrower than the edge, creating a similar problem.

### Proposal

Add the ability to offset the keyboard left and right margins to increase the padding to tfe screen edge.

**Comment by testsnake** [comment]
On my pixel 7 pro, gboard has pretty huge margins on all sides. Even excluding the screen protector issue, I find having the keyboard in a smaller space to be a lot more comfortable. 

The closest I could get the FUTO keyboard to my gboard setup was still quite bigger.

![Screenshot_20240918-181510~2.png](https://github.com/user-attachments/assets/042a7e33-861e-4ac5-9690-893b1341de62)

![Screenshot_20240918-181502~2.png](https://github.com/user-attachments/assets/71ada7d6-271e-4ad1-9813-e3517be1bdfa)

**Comment by abb128** [comment]
An option to resize and add side margins is available in nightly and will be included in the next release
