### ISSUE TITLE
Allow Dynamic Spacing for Shortcuts in Favorites Menu

### ISSUE THREAD

**Issue by Irique-pliskin** [futo-org/android-keyboard#521]
### Use Cases

This is a mostly aesthetic complaint:
Currently, the shortcuts/actions in the favorites menu maintain a consistent spacing between them. This limits the amount of shortcuts that can be readily accessible without swiping across them and forces a certain amount to be used, unless you want unused space to be visible.

**Comment by abb128** [comment]
Duplicate of #576
