### ISSUE TITLE
Possible Memory Leak Causing Increased RAM Usage Over Time

### ISSUE THREAD

**Issue by tamarindojuice** [futo-org/android-keyboard#524]
### What happened?

Process/service starts using like ~40mb of RAM but with usage gets bigger and bigger, sometimes up to the ~400mb.
Seems to be a memory leak that increases RAM usage overtime. 
![Screenshot_20240901_192923](https://github.com/user-attachments/assets/06ee6721-13e7-4a6f-b9d2-690ec4a78c2e)

### Keyboard Version

0.1.23.2 -playstore

**Comment by bradn2** [comment]
The memory leak I noticed is when any voice model other than the default is set - if you keep doing voice to texts it seems like it keeps loading the model over and over but not freeing it until you close the keyboard.  I open a terminal and run "watch free" and then use the keyboard to see this behavior.

**Comment by abb128** [comment]
This has been fixed in nightly, thanks for reporting
