### ISSUE TITLE
Bulgarian (Phonetic Traditional) Layout

### ISSUE THREAD

**Issue by mogoyaki** [futo-org/android-keyboard#529]
### Language

Bulgarian

### Description

Hi guys :)
Even that Bulgarian (BDS) is the official keyboard layout (as far as I know)
The most used one is the Bulgarian (Phonetic Traditional) Layout
and they are quite different.
example: https://kbdlayout.info/kbdbgph1
example:
ENG-qwerty
BUL-ЫУЕИШЩ
BUL (Phonetic)-явертъ

**Comment by nikbpetrov** [comment]
This would be great - the only thing preventing me from switching to FUTO atm is that I switch between the two constantly.

Bulgarian-specific voice input models (at least a better one than the current one) would also be nice.

**Comment by abb128** [comment]
This layout is added in Nightly
![image](https://github.com/user-attachments/assets/78ce17a1-f09e-49c3-8696-6cd3605f0bfe)

**Comment by mogoyaki** [comment]
Thanks ! :)
