### ISSUE TITLE
Include direct Obtainium link on website (https://keyboard.futo.org/#download)

### ISSUE THREAD

**Issue by imgalaxyhunter** [futo-org/android-keyboard#53]
https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.futo.inputmethod.latin%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Ffuto-org%2Fandroid-keyboard%22%2C%22author%22%3A%22futo-org%22%2C%22name%22%3A%22FUTO%20Keyboard%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3Anull%7D

**Comment by tom-futo** [comment]
Thank you for suggestion, the Obtanium link was added to our site.

**Comment by NicholasFlamy** [comment]
> Thank you for suggestion, the Obtanium link was added to our site.

I think y'all missed the point. The point was to add a link with Obtainium config. Also, y'alls inconsistent semantic versioning of the GitHub releases breaks proper version detection with patch versions because v0.1.24 should've been v0.1.24.0.
