### ISSUE TITLE
"Block Offensive Words" Not Working

### ISSUE THREAD

**Issue by itsordinaryperson** [futo-org/android-keyboard#531]
### What happened?

In Text predictions -> Block offensive words enabled but offensive words are still shown in suggestions. Manually added some general words to check but the words are still shown in suggestions.

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
The offensive word list is English-only at the moment and may not include every word. If you could give some examples of words that should be blocked but aren't, I could add them to the list.

**Comment by abb128** [comment]
Closing as there has not been a response
