### ISSUE TITLE
Remove Duplicate "%" Key from Default QWERTY Layout

### ISSUE THREAD

**Issue by Nabushika** [futo-org/android-keyboard#539]
### Language

English

### Description

Long press Q => %
Long press F => %
Ditto for the symbol layer, the buttons in the Q and F places are both %s.
I think Swiftkey has a tilde character on a long press, perhaps one of them could be switched to that?

### Complexity

Likely minimal

**Comment by abathur** [comment]
@dean-futo I may be misunderstanding but it looks like this regressed? 

I landed here looking for an easier way to type tildes, and I still see % on both q and f. (on v0.1.24.2-playstore).
