### ISSUE TITLE
Long-Press Enter Key Does Not Work in Browser Toolbar Inputs

### ISSUE THREAD

**Issue by KaKi87** [futo-org/android-keyboard#541]
### What happened?

Long-pressing the *Enter* key on browser toolbar inputs simply doesn't work.

Tested with Chrome-based and Firefox-based apps.

Thanks

### Keyboard Version

0.1.23.2

### Text field info

Browser toolbar inputs

**Comment by dean-futo** [comment]
This has been fixed in nightly and will be working in the next release.

**Comment by KaKi87** [comment]
Thanks, unfortunately I won't be able to enjoy it because of worse issues in nightly :

- the keyboard layout made the `€` symbol even more difficult to access despite #513 ;
- key borders for the number rows are gone ;
- a whitespace is always automatically inserted after inputting a special character.

**Comment by dean-futo** [comment]
@KaKi87 if you haven't updated to 0.1.24 yet, please do so and let me know if you're still experiencing any of these issues.

**Comment by KaKi87** [comment]
Are you saying the changes I mentioned were reverted before the release ?

**Comment by dean-futo** [comment]
No, I'm saying please update to the latest release as the version you were using when you made this ticket is no longer the latest. As I said, let me know if you still experience these issues in the latest release.

**Comment by KaKi87** [comment]
Yes, I still am experiencing those issues :

- the keyboard layout made the `€` symbol even more difficult to access despite #513 ;
- key borders for the number row are gone.

However I noticed from the changelog that the space after special character can be disabled, so I did.

But, the two remaining issues forced me to downgrade.
