### ISSUE TITLE
Layout with dedicated keys for german special charaters

### ISSUE THREAD

**Issue by arn0nym0us** [futo-org/android-keyboard#543]
### Language

German

### Description

Would be great to have a layout with dedicated keys for german umlauts ä, ö and ü since they occure very frequently in the german language and are a hassle to type using the longpress menu.

Looks like this:
https://i0.wp.com/www.smartdroid.de/wp-content/uploads/2018/11/gboard-mit-umlauten.jpg?resize=850%2C520&ssl=1

**Comment by arn0nym0us** [comment]
Nevermind, it already exists.
I just found it, it was hidden as "Swiss" Layout ;-)

**Comment by abb128** [comment]
In the next release there will be a dedicated Deutsch layout that's basically the same as the current Swiss layout, but it will be the default option when adding German
