### ISSUE TITLE
Auto-Capitalization Occurs Despite Being Disabled

### ISSUE THREAD

**Issue by skylinestar1986** [futo-org/android-keyboard#552]
### What happened?

It's too random. Sometimes it capitalizes. Sometimes it doesn't. Sometimes it capitalizes on all new text line. I have toggled the setting and it still persist to capitalize. It's so frustrating. 

Most obvious text is the word "why". If I enter "cat", it doesn't capitalize. It doesn't capitalize "how", "what", "where" but it does capitalize "why".

### Keyboard Version

0.1.23.2-playstore

**Comment by Flameopathic** [comment]
same issue; it most often capitalizes words when it has to autocorrect them, so "thats" autocorrects to "That's" if it's at the start of a sentence.

**Comment by dean-futo** [comment]
Consolidated into #663

**Comment by dean-futo** [comment]
Duplicate of #547 - see that issue for details.
