### ISSUE TITLE
Swipe Typing Fails for Long and Complex Words

### ISSUE THREAD

**Issue by zzyzx-dc** [futo-org/android-keyboard#560]
### What happened?

Swipe typing a word which involves complicated swipes like:
- actually
- manipulation
- bizarre
- entryway
- complicated
- successfully

I swipe these carefully and see the pattern contact each letter, but it's hit or miss. You feel like you successfully swiped it, and see the swipe trail, but there is no response from the app at all. 

Other times in the same session, the predictor finds them instantly.

Speech to text is working perfectly, but I suspect most Android users swipe and this makes adopting the app very difficult. 

### Keyboard Version

0.1.23.2 playstore

**Comment by esa1975** [comment]
Just thought I'd add my two cents here. Thank you for an almost perfect keyboard. It is seriously impressive. Swipe is something that I really need in a keyboard and it's what keeps me using Gboard. FUTO's swipe is reasonably good, but it does miss long words as described here and also often two letter words, which makes it very difficult to adopt fully. I am using the same version as the original poster. I'd be happy to try a version using Obtanium or similar if it helps to test outside of the Play Store.

**Comment by dean-futo** [comment]
Consolidated into #665

**Comment by dean-futo** [comment]
Similar to #661 and #408 - merging those issues into this one. All have to do with swipe typing being inaccurate, especially for long, complex, or foreign words.

**Comment by dean-futo** [comment]
@zzyzx-dc I was able to type all of those words without any issue. Will you provide a video of the failures?

**Comment by esa1975** [comment]
> @zzyzx-dc I was able to type all of those words without any issue. Will you provide a video of the failures?

Apologies for butting in but I'd like to add that, while it is possible to use the swipe feature to enter the list of words they provided, doing so requires a high level of accuracy, much higher than Gboard for example. Perhaps the better way to say it is that something like Gboard allows for a much lower level of precision than Futo and is more forgiving of less than perfect connections between individual letters. The result is that the usability and speed of entry for any given word is far higher than Futo's in my experience. I could try to record a comparison between the two if you're unable to recreate that experience yourself.

**Comment by dean-futo** [comment]
@esa1975 thanks for clarifying. We are actively working on enhancing swipe-typing accuracy, as discussed in #363. Merging this issue into that one since it's already something that's on our radar.
