### ISSUE TITLE
Vibrate on Keypress Fails to Work on Sony Xperia

### ISSUE THREAD

**Issue by Cricket422** [futo-org/android-keyboard#561]
### What happened?

HI, I've been using the Futo keyboard now for I want to say 2 months now and I wanna say I love the app but unfortunately I'm unable to get the vibrate on keypress to work for me for the life of me, I've tried reinstalling it and everything but nothing works so I'm not sure what's  happening (currently using a Sony xperia v5 with android 14)

### Keyboard Version

0.1.23.2-playstore

**Comment by abb128** [comment]
Another user reported in #172 that enabling touch haptics in system settings fixed it, can you see if it fixes it for you too?

**Comment by Cricket422** [comment]
That seems to have fixed it thank you so much!
