### ISSUE TITLE
Backspace Not Working Properly After Copy Action

### ISSUE THREAD

**Issue by notasheepl** [futo-org/android-keyboard#564]
### What happened?

Pixel 5a, android 14 (AP2A.240805.005), Version 0.1.23.2-playstore

Steps: 
1. Select text (touch and hold, select all action or text editor) 
2. Tap copy to clipboard action or hold C for copy shortcut
3. Press Backspace while copied text is selected

Expected:
Selection is deleted or unselected upon copy

Actual behaviour:
Github (here through chrome)
After copy the selection remains selected
First backspace deletes character before selection
Second backspace deletes the selection

Messaging apps, pixel bottom search, YouTube search.
If selected with select all or text editor same behavior as above
If selected by touch and hold selection is unselected upon copy

Opinion:
I prefer the selection remaining after copy
It allows me to move cursor to start of selection or end by swiping space

### Keyboard Version

0.1.23.2-playstore

### Text field info

Various behaviours in various fields

**Comment by dean-futo** [comment]
Consolidated into #673
