### ISSUE TITLE
Bottom Offset does nothing

### ISSUE THREAD

**Issue by issacdowling** [futo-org/android-keyboard#565]
### What happened?

When I change the bottom offset, there is no difference at all made to the actual offset of the keyboard. This is only on nightly 0.1.23.2-57-gf795a7228-dirty, and downgrading back to the regular 0.1.23.2 release fixes things.

### Keyboard Version

0.1.23.2-57-gf795a7228-dirty

**Comment by abb128** [comment]
This is fixed as new resize controls have been added
