### ISSUE TITLE
Numbers Interfere with Autocorrect and Predictive Text

### ISSUE THREAD

**Issue by DigitalRubicon** [futo-org/android-keyboard#566]
### What happened?

i've noticed is that while using the LLM based features ,if i type a number into the word by accident it will no longer give valid autocorrect suggestions and it will never autocorrect even with the Autocorrect Threshold set very low.(so that it autocorrects more often)

example 
 
"Dopnt" will autocorrect to doesn't 
"Do9nt" will not autocorrect.

### Keyboard Version

0.01.23.2

**Comment by Mangoes** [comment]
Yes, this is a big problem when swiping, with the numbers row on the top. 

Accidentally getting close to a number in the top row while swiping will never autocorrect. 

Please fix this. Thanks.

**Comment by abb128** [comment]
Numbers should interfere less with autocorrect in nightly
