### ISSUE TITLE
Option to disable hold search button for emoji keyboard

### ISSUE THREAD

**Issue by FilipDonoval** [futo-org/android-keyboard#57]
When holding the search button for some time, the keyboard switches to the emoji keyboard.
![Screenshot1](https://github.com/futo-org/android-keyboard/assets/102729468/975064f0-4abc-428c-9521-4a925a5aaef6)

![Screenshot2](https://github.com/futo-org/android-keyboard/assets/102729468/28d37799-8b56-40df-aac1-b1a35fcba909)

It would be great to have an option to disable that in settings or to have an option for keyboard to always stay in URL search mode that doesn't have an option to hold for emoji keyboard like in this picture.

![Screenshot3](https://github.com/futo-org/android-keyboard/assets/102729468/5b0ab080-9b2d-4a40-ba59-4433b0fc7b12)

**Comment by abb128** [comment]
I don't see a reason for adding a setting here, the enter key gives you shortcuts for certain actions. Unless it's a common issue that people long-press the enter key by accident which I haven't heard of much
