### ISSUE TITLE
Mandatory pseudo-capitalization

### ISSUE THREAD

**Issue by Bekar-T** [futo-org/android-keyboard#571]
### Language

Georgian

### Description

Georgian has more letters than fit in standard QWERTY layout and has no capitalization.

Because of this, usually, the shift key is used to access the letters that don't fit in the "regular" set.

Also, technically, the language has pseudo-capitalized character set, purpose of which is a mystery to me.

So, when trying to access the "extra" letters with shift key, the letters are there but they are unnecessarily pseudo-capitalized.

The shift key press does both, gives access to hidden letters but also pseudo-capitalizes them, with no way to un-pseudo-capitalize them. This produces weird script where some letters are always pseudo-capitalized.

Perfect solution would be for the shift press to only give access to hidden letters, and not have anything to do with capitalization, for Georgian layout.

**Comment by abb128** [comment]
Is this a duplicate of #113 ?

**Comment by Bekar-T** [comment]
Basically yes.

Not of the original issue, which was narrow in scope to just one letter, but with first clarifying comment, yes, this is a duplicate.

Thanks for pointing out.
