### ISSUE TITLE
Jarring Height Change Using Action Bar Items

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#579]
### What happened?

When using actions of the action bar that have their own display, like the clipboard manager or emoji actions for example, the height of the keyboard is reset to ignore the action bar. This is very jarring when using any application. 

The height of the keyboard should not be changing like that. Just include the action bar itself into the height of any sub display.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This will be fixed in the next release
