### ISSUE TITLE
When you type your quotations ("") and then move the cursor to type inside them it creates an unexpected space at the beginning of the quote

### ISSUE THREAD

**Issue by Cris-Edmundson** [futo-org/android-keyboard#582]
### What happened?

Steps to reproduce:

1) Type two quotation marks:
""
2) move the cursor to the middle of the quotation marks with swipe typing (from testing right now, it doesn't seem to have an issue when you move the cursor manually with the touch screen)
3) when I type inside the quotation marks I get:
" text"
The space before "text", inside the quotation marks is unexpected, and shouldn't be added 

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.

**Comment by Cris-Edmundson** [comment]
Thank you so much! I appreciate y'all ❤️
