### ISSUE TITLE
Allow for in-app model downloads similar to standalone voice input app

### ISSUE THREAD

**Issue by radioaddition** [futo-org/android-keyboard#585]
### Use Cases

- Makes initial setup somewhat less tedious
- Especially useful for those who use multiple user profiles, and who will likely need to go through the setup process more than once
- Even more useful for those that use ephemeral/guest profiles, who may regularly go through the setup process throughout their usage of the device

### Proposal

Add an option to download alternative models directly in the app, rather than linking to external downloads and requiring them to be imported. This would work similarly to the way it does on the standalone FUTO Voice app

**Comment by abb128** [comment]
This is not possible at the moment without changing the app to start requiring the internet permission
