### ISSUE TITLE
Tiny Key Spacing Leading to Typing Errors

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#587]
### What happened?

Observable in the images below, the keys are not spaced consistently on all sides. The gap on the sides is much, much smaller than the top and bottom. Aesthetics aside, that gap on the sides is almost non existent, making the keys so close together that using FUTO is very error prone.

Compared to Swiftkey where I can often look away while typing, I get errors with FUTO even when cautiously typing out every character.

![image](https://github.com/user-attachments/assets/82dd6a09-06a9-47bd-bd72-a4016f511e5b)
![image](https://github.com/user-attachments/assets/ff925e98-cd35-420d-bddb-b51ba2f4c932)

### Keyboard Version

nightly

**Comment by abb128** [comment]
The key spacing is purely visual. The key hitboxes expand into the spacing, so such a setting would have no effect on typing. More likely you have to just adjust the size and padding of the keyboard. FUTO Keyboard also doesn't do probabilistic hitbox adjustment at the moment, if SwiftKey does it then that may also be a reason for increased typing errors - #433
