### ISSUE TITLE
Resize Keyboard Number Input Broken

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#588]
### What happened?

On the Resize Keyboard settings page, the Keyboard Height has a number input with percentage values but when you select it to manually change it, it's becomes a decimal value. `100%` becomes` 0.99xxx` or `1` and trying to enter `80` for `80%` becomes `175%` after it's converted to `1.75`.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This is fixed as the setting has been removed in favor of a visual resizer
