### ISSUE TITLE
[Feature Request] Delete whole words when swiping backspace.

### ISSUE THREAD

**Issue by robsdedude** [futo-org/android-keyboard#59]
When swiping the backspace key with Gboard, it selects full words, not just single letters. This makes it much more convenient to delete a lot of text.

This could also be configurable in the settings, depending on how people prefer it to behave.

**Comment by abb128** [comment]
Duplicate of #20

**Comment by robsdedude** [comment]
Thanks and sorry for the noise. I looked through the issues but must have missed this one.
