### ISSUE TITLE
Punctuation Fails With Autocomplete

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#590]
### What happened?

If you use the spacebar to autocomplete a word, a space is generated after the word but if you insert a punctuation afterwards, the space remains. This should not be. The space in such cases should be automatically deleted and reinserted on the other side after using a punctuation.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.
