### ISSUE TITLE
Think it was the cause of my first nothingOS crash. Also it opens for some reason on grayjay while viewing full screen (not sure if related)

### ISSUE THREAD

**Issue by silvaf6** [futo-org/android-keyboard#592]
### What happened?

NothingOS crashed for the first time in my life. installed logfox with sizuku and it was the single crash report it had. I'll post the log bellow from it and check if i there is an option to send logs to debug inside the app.

Also popups up the whole keyboard, sometimes with grayjay on full screen.

All of those apps are even paid. futo keyboard from app store, aswell the voice app. grayjay from fdroid.

If i need to install it from fdroid, please kindly tell me how to export the configs, it is an hassle to get it the way i like. or if i should join the beta program on playstore.

The OS did not update for like a month. Nothing Phone (2). gen 8+

On the first lines i see something about (latin) i have two imported languages. en-US and pt-PT (europe dictorionary or whatever from the given links on futo). haven't touched a setting in-app since (probably since a month ago or two)

### Keyboard Version

0.1.23.2-playstore

### Text field info

`FATAL EXCEPTION: main
Process: org.futo.inputmethod.latin.playstore, PID: 4540
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_UNLOCKED flg=0x50000010 (has extras) } in org.futo.inputmethod.latin.LatinIMELegacy$1@7428ec1
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1833)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.futo.inputmethod.keyboard.KeyboardSwitcher.setKeyboard(SourceFile:20)
	at org.futo.inputmethod.keyboard.internal.KeyboardState.setAlphabetKeyboard(SourceFile:7)
	at org.futo.inputmethod.keyboard.internal.KeyboardState.onLoadKeyboard(SourceFile:66)
	at org.futo.inputmethod.latin.LatinIME.recreateKeyboard(SourceFile:54)
	at okhttp3.Handshake$Companion$handshake$1.invoke(SourceFile:113)
	at okhttp3.Handshake$Companion$handshake$1.invoke(SourceFile:7)
	at org.futo.inputmethod.latin.LatinIMELegacy$1.onReceive(SourceFile:52)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1823)
	... 10 more`

**Comment by silvaf6** [comment]
The report coincides with the time the OS crashed
![Screenshot_20241003-161215](https://github.com/user-attachments/assets/7f613d39-cc0e-4069-9140-53a754d9b06c)

**Comment by silvaf6** [comment]
Well, after taking the time to report an issue, finding an open source app to debug it to improve futo, even supporting it by paying, helping rossman by request for you to learn how i do swype (i don't even swype, for a long time, neither i use voice to text, which I've paid as well).

I've felt a bit off with a lack of a single response.

Anyways, haven't happent since then, I'll close this, even tough it is the same version and none on the team is taking response.

I value my digital privacy, i know how to check for trackers, so all is ok, don't remember, but i believe it does not even have bugsnatch. so this app is the only way to go.

A good keyboard app requires a well dedicated team wich I'm very well appreciated. And this is the only good one, similar to gboard, which i would not even dare install again.

Love it, but won't bother myself again going out of my way to help out the development.

Ross and his boss have a greater mind than mine, but i do hope it is not very hard to upgrade for future OS releases breaking everything, because i do not want the project to go down.

In the future should be considered to ask for a small amount just for android OS major release fixes. Or once it is full fledged (for me it is), make it non-free with full features.

It is how our horrible present works for a project to carry on, with so many spyware apps available for free that nobody cares what they do with your data. It is very sad and makes me mad.

Just make futo apps decently configured by default, so i can install them on the phones of elderly relatives, without having to look for dictionaries and such.

**Comment by abb128** [comment]
I apologize for the lack of response and letting you down, but the information provided just wasn't sufficient to reproduce or confirm whether the OS crash was a one-off or if there's something specific that needs to be fixed. There are nearly 400 issues and I try to read all of them but I'm unable to spend my time responding or investigating all of them without compromising on time spent developing and improving the keyboard. We have been in the process of staffing a dedicated QA person to be more responsive with issues and emails.

**Comment by silvaf6** [comment]
> I apologize for the lack of response and letting you down, but the information provided just wasn't sufficient to reproduce or confirm whether the OS crash was a one-off or if there's something specific that needs to be fixed. There are nearly 400 issues and I try to read all of them but I'm unable to spend my time responding or investigating all of them without compromising on time spent developing and improving the keyboard. We have been in the process of staffing a dedicated QA person to be more responsive with issues and emails.

My awnser counts however you may take it. I have my phone more or less for an year, and this was the first crash ever, with the keyboard bugging out on grayjay, on the same day. but i'm not a full fledged progammer.

80%-90% of all my non-system apps are open source.
