### ISSUE TITLE
Make Action Bar Appear in Emoji Menu

### ISSUE THREAD

**Issue by sajjad000** [futo-org/android-keyboard#594]
When you open the emoji menu, the action bar disappears 

https://github.com/user-attachments/assets/0796f56a-a14c-43f7-8d1c-2a785ed90ac3

To improve the user experience, please make the action bar appear when you open the emoji menu like this:
![Screenshot_20241003_234729](https://github.com/user-attachments/assets/fc07cf49-bc4a-4afd-b81e-04df342c7e38)

This improvement makes me open and close the emoji menu from the action bar and this makes my experience better, especially if I use one hand

**Comment by dean-futo** [comment]
@sajjad000 the user interface is cleaner with the action bar disappearing as it does when selecting the emoji menu, so we're going to leave it how it is.
