### ISSUE TITLE
Spacebar Scroll Slow and Ends Abruptly Despite Holding Down Key

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#595]
### What happened?

When using the spacebar to scroll, despite continuing to hold the key down in a specific direction, the cursor does not move along the text in that direction, forcing you to repeatedly swipe across the spacebar just to fully scroll text. The scroll is also quite slow. This is very bad for scrolling long text, like urls for example. 

In Swiftkey, aside from #581, spacebar scroll is continuous, both in the sense that the speed is maintained or even increases and the cursor continues along the text in the scrolled direction until reaching the end. 

### Keyboard Version

nightly

**Comment by dean-futo** [comment]
Consolidated into #673

**Comment by dean-futo** [comment]
Thanks @issuant. You're right - this is very similar to what is requested in #581. Merging this issue into that one.
