### ISSUE TITLE
Manually Selecting Suggestion Still Inserts Space After Dot in Searchbar

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#596]
### What happened?

This happens in Brave. Manually select a suggestion then type a `.` and it auto inserts a space with the cursor after it. A space should never be auto inserted after a dot in there. This is related to #590.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.

**Comment by abb128** [comment]
Are there any keyboards that do automatically insert a space in that scenario? URL bars and email fields are sensitive when it comes to automatic space insertion
