### ISSUE TITLE
Spacebar Autocomplete Doesn't Work in Search Bars

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#597]
### What happened?

Despite `Auto-correction` being activated, tapping spacebar to complete or correct a word never works in Brave's search bar. You have to manually select a suggestion to use it, which causes its own set of issues (#596).

### Keyboard Version

nightly

**Comment by dean-futo** [comment]
Consolidated into #673

**Comment by andrewbanchich** [comment]
@dean-futo I'm running into this as well. Can you reopen this please?
