### ISSUE TITLE
Capitalized Suggestions in Search Bar When Typing

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#598]
### What happened?

The keyboard regularly makes capitalized suggestions despite the active field being the searchbar (in Brave). This makes no sense. It also likes to make suggestions with a `-` in them but that's a general issue with the keyboard.

### Keyboard Version

nightly

**Comment by thepting** [comment]
It makes all caps suggestions all the time.  Really makes me sound like an angry old boomer

**Comment by dean-futo** [comment]
Consolidated into #674
