### ISSUE TITLE
"Dynamic System" theme doesn't follow OS light/dark mode

### ISSUE THREAD

**Issue by ImranR98** [futo-org/android-keyboard#6]
For some reason, the dynamic system theme is always identical to the dynamic dark theme for me, even when the OS is in light mode.

Pixel 8 Pro, GrapheneOS 14, build 2024050900.

**Comment by ImranR98** [comment]
This was fixed in the latest release. Thanks!

**Comment by Felix14-v2** [comment]
Current version of the keyboard doesn't have the "system" theme at all, can this issue be reopened?

**Comment by Zvonimir-FUTO** [comment]
This'll be tracked in the theme editor repo

**Comment by abb128** [comment]
> Current version of the keyboard doesn't have the "system" theme at all, can this issue be reopened?

It does but the minimum for it to appear is Android 12+ I believe
