### ISSUE TITLE
Noticeable Delay When Long-pressing Delete

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#602]
### What happened?

Coming from Swiftkey and even comparing with Florisboard, there's a very noticeable delay after long-pressing delete for the delete to actually happen. It's even more noticeable when 'Backspace behavior' is set to 'Delete entire words'. It makes no sense for symbol popups to be more responsive than the delete key.

### Keyboard Version

nightly

**Comment by abb128** [comment]
The delays are linked to the long-press setting in the latest nightly
