### ISSUE TITLE
Punctuation Inserts Improperly

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#604]
### What happened?

If you manually select in between some piece of text and insert a punctuation, like a comma, it does not automatically attach to the preceding word but instead leaves a hanging space. `I wanted you know` becomes `I wanted ,you know` instead of `I wanted, you know`. Same issue with other punctuations, like `-` which should insert space both sides.

This is related to but different from #590 and #599.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This is fixed in nightly and the fix will be included in the next release.
