### ISSUE TITLE
Add Swipe Gestures for Editing Functions

### ISSUE THREAD

**Issue by session11** [futo-org/android-keyboard#607]
### Use Cases

Honestly speaking, I am yet to come across a keyboard that is as powerful as Multiling O Keyboard. Unfortunately, the project is dead and I haven't seen updates, and yet the keyboard is too feature rich and powerful given its small size. FUTO by far is the only keyboard that could fulfil the promises of Multiling O Keyboard to some extent. 

Powerful and Sleek Gesture Support: One of the many perks of Multiling O Keyboard is its gesture support that the user could utilize to accomplish anything. We have UP, DOWN, LEFT, RIGHT gestures that could be used anywhere across the keyboard (not just the SPACEBAR) and these gestures could be assigned with editing actions like CUT, COPY, PASTE, SELECT ALL, SELECT WORD.... you just name the editing task and that could be precisely accomplished with a smooth and never failing gesture. Furthermore, these gestures are further divided into SINGLE SWIPE and MULTI SWIPES.... You could imagine, how powerful the keyboard becomes and typing and editing becomes a piece of cake. Futo Keyboard is good and has potential but switching from Multiling O Keyboard keyboard sometimes feel like a lost limb! I hope to see gesture implementation in future FUTO updates as it found in Multiling O Keyboard.

**Comment by dean-futo** [comment]
Thanks for your request, but this would disrupt swipe-typing functionality and add unnecessary complexity for minimal benefit. Basic editing functions can already be accessed through simpler means.

**Comment by session11** [comment]
Sorry to hear that and I totally understand. Although I feel that the problem of "added complexity" could easily be solved with the option of choosing between Gesture Typing or Advanced Editing Gestures. What I mean to say is if implemented, Advanced Editing Gestures could only be used if the user turns off Gesture Typing. So those who don't use Swipe Typing could take the advantage of Advanced Swipe Gestures. I hope this suggestion will be taken into consideration.
