### ISSUE TITLE
Reduce gap from sides of screen during split screen mode

### ISSUE THREAD

**Issue by d-walsh** [futo-org/android-keyboard#608]
### What happened?

When I'm using my foldable phone, there's large gaps between the keyboard buttons in split screen mode versus the edges of the screen and so it's ergonomically hard to type. 
![Screenshot_2024-10-06-13-15-51-00_8218ad734a8157e87572f0f6e2674adf](https://github.com/user-attachments/assets/aee75d1e-ba14-4766-87d4-9d75c4582bb2)

Gboard has resolved this with their layout:
![Screenshot_2024-10-06-13-16-04-54_8218ad734a8157e87572f0f6e2674adf](https://github.com/user-attachments/assets/2f1ceb07-5d6b-4593-a6c7-9d4b81b21961)

### Keyboard Version

0.1.23.2-104-gc6e8336e7-dirty

**Comment by abb128** [comment]
You can customize this in resize options

**Comment by abb128** [comment]
Closing as it's a user-configurable option
