### ISSUE TITLE
Customization of Punctuation Key Long-Press Options

### ISSUE THREAD

**Issue by EdyMarin** [futo-org/android-keyboard#61]
Add a way to customize what simbols are available when holding down the dot key, and in what order. The current selection is not usefully ordered

**Comment by josb** [comment]
And consider adding this for the comma key, please.

**Comment by swishkin** [comment]
For reference:
### FUTO Keyboard:
![Screenshot_20240701-212932_Brave - Beta](https://github.com/futo-org/android-keyboard/assets/19404743/73da352b-428d-4db3-8d0f-857360615da6)
### Lineage AOSP Keyboard:
![Screenshot_20240701-212945_Brave - Beta](https://github.com/futo-org/android-keyboard/assets/19404743/ef86a72e-1a66-48b1-8e0f-b959d86137b4)

Being closer to the AOSP/Gboard layout by default would probably be a good start, as that's likely what most people are moving from, but I definitely wouldn't mind the additional customization options suggested above.

**Comment by abb128** [comment]
In 0.1.23.2 the layout has been updated to match AOSP/Gboard
