### ISSUE TITLE
Can't enter the password after the system reboots.

### ISSUE THREAD

**Issue by aadunin** [futo-org/android-keyboard#612]
### What happened?

Pixel 6 pro, GrapheneOS Alpha channel, OEM unlocking disabled.
The ‘FUTO Keyboard’ application is installed in the operating system
In the system settings, ‘FUTO Keyboard’ has been selected as the default input, and other keyboards are disabled.
After rebooting the device, a system message appears on the password input screen:
The ‘FUTO Keyboard’ application has crashed again.
In fact I can't do anything.
I can't enter the password because there is no input method and the system doesn't prompt me to select the stock keyboard.

### Keyboard Version

0.1.23.2-104-gc6e8336e7-dirty

**Comment by abb128** [comment]
Thanks for reporting. This is an issue in the nightly and it will be investigated and resolved. In the meantime, if you can't switch keyboards or enter your password any other way please try plugging in a physical keyboard with a USB-C OTG adapter and entering your password that way

**Comment by abb128** [comment]
IIRC that is a GrapheneOS-only feature and by default there are no restrictions. GrapheneOS does have an option to enable restrictions for security, but one of the options has a special exemption for BFU probably for this exact case.

![image](https://github.com/user-attachments/assets/b4022d2f-48e5-4a23-832a-d065cfaeaa5b)

If you did manually set the option to disable the port without the BFU exemption, and you set a text password and ran the unstable nightly version of the keyboard, then you may be in a tricky situation indeed. Unfortunately I wouldn't be able to advise on how to unlock your phone in that case.

**Comment by aadunin** [comment]
Everything is exactly as you described; all security features are enabled, including "USB-C Port Charging-only when locked".

**Comment by abb128** [comment]
The new nightly should no longer have this issue. Note that the in-app update checker won't check nightly, you have to download and install nightly.apk again and make sure you're now on v0.1.23.2-120-g5ae3d3ab9

Were you able to unlock your phone by entering safe mode? It should disable third-party apps and allow you to enter your password with the stock keyboard. You can enter it by holding the volume down button when you see the boot animation, or holding one of the power off/reboot UI buttons if your phone is already on. https://support.google.com/pixelphone/answer/2852139#zippy=%2Cif-your-phone-is-off

**Comment by aadunin** [comment]
Thanks for the reply, yes I was able to unlock the device via safe mode.

**Comment by abb128** [comment]
Thanks for confirming, glad you were able to unlock your phone. Closing this as solved now

**Comment by aadunin** [comment]
Thank you for your assistance, attention to detail is the success of the project.
