### ISSUE TITLE
New Resize Feature is Buggy and Unintuitive

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#613]
### What happened?

I'll start with saying it's actually a great feature. It just has a couple bugs and unintuitiveness to it.

There's an `X` button that looks like reset or cancel but it seems to work like a confirm? Broke my keyboard sizing with that while testing the new feature out. The `X` also removes the action bar which makes it impossible to determine what the actual size of the keyboard with the action bar will be after resizing so you end up doing it at least twice. The action bar should be shown while resizing.

There's a 'Reset all size settings' text on the page but it's actually a button that can be pressed. That is surprising, given it looks like plain text, but also confusing with the more obvious `X` button there. 

There's also a bug where if you press the back button on the top left of the page, the 'Resize Keyboard' with the 4 mode buttons on top that was triggered still remain on the 'Keyboard & Typing' settings page, `X` included. They stay there even if you tap into and out of other pages from then on. It only goes away if you use the phone's back button.

Finally, there's the duplicative 'Resize Keyboard' button you need to press to actually bring up the true resizer. I think this button, and the other `<-` that hides the preset modes, is redundant, and the draggable resizer should be activated by default when the keyboard is triggered on the page. This way, you can eliminate both the 'Reset all size settings' text and `X` button since a much more intuitive and clear 'Reset' button exists on the draggable resizer. You also eliminate errors and streamline the process which currently requires exiting the page and returning if you sized it wrong but the keyboard had deactivated, taking the 'Resize keyboard' button you need to press with it.

Bonus: the draggable resizer should start at the top of the keyboard, action bar included if the user has it activated, not over the 4 mode buttons

### Keyboard Version

nightly

**Comment by abb128** [comment]
This should be improved a bit in the latest nightly
