### ISSUE TITLE
'Additional Layouts' in 'Keyboard & Typing' is 'Language & Models' Duplicate

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#614]
### What happened?

The 'Additional Layouts' option in the 'Keyboard & Typing' page goes to the same place as 'Language & Models' in the main menu. Placeholder or mistake?

### Keyboard Version

nightly

**Comment by abb128** [comment]
This is intentional, the shortcut is there to clarify keyboard layouts are configured in the languages menu, otherwise some users could go to the "Keyboard & Typing" page trying to add an extra keyboard layout but never find the option to do so
