### ISSUE TITLE
Italicized, Quoted Words in Suggestion Bar

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#615]
### What happened?

After updating to the latest nightly, I am now getting italicized, double-quoted words in the suggestion bar, consistently in the third position. Something like _`"future"`_. This never happened in the previous nightly.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This isn't a bug, it's shown when tapping space will autocorrect your current word. By tapping the quoted word you can skip autocorrect and enter what you typed verbatim. Previously the rightmost suggestion was always what you typed and served the same purpose but this meant only two suggestions could be shown and it led to confusion

**Comment by abb128** [comment]
> The confusion also adds up because if you are typing out "futu, the keyboard suggests "futu" rather than the clearly weird ""futu"".

This is not expected behavior, quotes are not valid word characters so they should not be included. If you can demonstrate this happening then it would be a bug

**Comment by abb128** [comment]
@issuant 

No, I'm saying the opposite. Quote should not be included in the composing word, as seen below. Is this not the case for you?
![image](https://github.com/user-attachments/assets/f11b2667-bbc0-407d-b874-8013b35dd099)
