### ISSUE TITLE
[Feature Request] Dedicated Numpad

### ISSUE THREAD

**Issue by Nordlicht-13** [futo-org/android-keyboard#617]
### Use Cases

It would be nice to have a Dedicated Numpad for writing e.g. banking account numbers.

### Proposal

Would be nice to longpress the num-button to get a dedicated numpad
like in the Heliboard
![heliboard_numpad](https://github.com/user-attachments/assets/8cf490c1-dedb-40b3-b761-5eabe6b52310)

**Comment by abb128** [comment]
This is already implemented in nightly and will be included in the next release

**Comment by Nordlicht-13** [comment]
Great, than I wait for the next release, hopefully soon.

**Comment by Nordlicht-13** [comment]
Just tried the nightly build.
It would be nice, if a normal tap on the ?123 button, would bring up the normal num-keyboard and a long-press the num-pad. So you don't have to switch with a second button.
