### ISSUE TITLE
Feedback on Dynamic Theme Colors

### ISSUE THREAD

**Issue by Ansarmughal99** [futo-org/android-keyboard#618]
### Use Cases

FUTO does not support Futo UI while all other keyboard working on android 13+ support material UI

### Proposal

Material UI with dyamic theme support which resemble with Wallpaper

### References

Like Gboard and Swiftkey And Florisboard

**Comment by abb128** [comment]
This is already implemented as the dynamic themes, do these not work for you?

![image](https://github.com/user-attachments/assets/1b3b5a00-35bf-424f-916e-df8a73d637ac)

**Comment by Ansarmughal99** [comment]
Dynamic color is dull as compared to gboard and florisboad .
Material ui theme on the gboard is very bright and colourful. While on futo it is mostly white color and others are not clearly visible

**Comment by abb128** [comment]
The colors have been updated in nightly. Old vs new


![image](https://github.com/user-attachments/assets/928c4cba-0057-4107-9a78-8b8d9ecdabc0)
![image](https://github.com/user-attachments/assets/5d0d69dd-e5a2-46db-bcb1-f3442a8d15e7)
