### ISSUE TITLE
App Crashing on Fairphone 5

### ISSUE THREAD

**Issue by victor-rays** [futo-org/android-keyboard#623]
### What happened?

The keyboard crashes immediately when trying to type anything, eventually android os warns about the app repeatedly crashing and asks to turn it off.

Im using a Fairphone 5 on Android 14

Edit: trying to switch back after turning FUTO off as input method did not fix the issue

### Keyboard Version

0.1.23.2

### Text field info

Happens everywhere

**Comment by abb128** [comment]
Would you be able to confirm if it still happens in nightly? https://keyboard.futo.org/nightly.apk

**Comment by victor-rays** [comment]
It does not happen in the nightly dev build :) 

The keyboard is working again in this version

**Comment by abb128** [comment]
Just to confirm, if you clear the app data for the non-nightly FUTO Keyboard, does it keep crashing still or does it start working again? Just trying to narrow down whether the app itself was at fault or if something in the app data is the cause.

**Comment by victor-rays** [comment]
The non-nightly version worked since July until about a week ago. Clearing app data and cache made the non-nightly version work again

**Comment by victor-rays** [comment]
Since the app is working again I will close this issue :)
