### ISSUE TITLE
Settings Font Size Incorrect in Nightly

### ISSUE THREAD

**Issue by Octoton** [futo-org/android-keyboard#624]
### What happened?

Just installed the last nigthly version to try out new fonction (since last tagged build is from july), and settings seems more cramped compare to before, seems like font sizes was changed but not the margin.
This doesn't not only reduce the quality feel of the app, but also the ease of use of the settings (difficult to find stuff) 

Android 14, pixel 4a

Before : 
![Screenshot_20241012-103906_Photos](https://github.com/user-attachments/assets/5e4c19bc-84a4-43ec-9932-579da06aed54)

After : 
![Screenshot_20241012-103910_Photos](https://github.com/user-attachments/assets/ae5bbb81-dd96-42f2-ac10-02227d9687f8)

### Keyboard Version

0.1.23.2-144-gcb511c7bf-dirty

**Comment by dean-futo** [comment]
The font has been resized in nightly akin to the original you pointed out.
