### ISSUE TITLE
Hide Special Characters Layout After Pressing Spacebar

### ISSUE THREAD

**Issue by Octoton** [futo-org/android-keyboard#626]
### Use Cases

I manly use special character layout for adding one comma or something and then i continue typing word, on my previous keyboard typing the spacebar would automatically switch the layout onto the qwerty one. 
Not sure if this should be the default behaviour or an option but it would be great for my use case

### Proposal

When in a special character layout, if i pressed the spacebar, i should be redirected to the qwerty layout

**Comment by abb128** [comment]
This was a regression from stable and it will be fixed in the next nightly
