### ISSUE TITLE
[Feature request] Please add the Bulgarian phonetic keyboard :)

### ISSUE THREAD

**Issue by Pankrias-real** [futo-org/android-keyboard#63]

**Comment by abb128** [comment]
I'm assuming you mean this layout? It looks like the layout was already there, but it was excluded as an option by mistake. It will be included in the next version.
![image](https://github.com/user-attachments/assets/a2a63877-5c42-4c07-afa0-f3aea6360fda)

**Comment by Pankrias-real** [comment]
Yes, that's the layout. Thank you!
