### ISSUE TITLE
[BUG] Cursor automatically jumps to the end of a word when tapping any letter

### ISSUE THREAD

**Issue by Beethoven-n** [futo-org/android-keyboard#632]
### What happened?

When you try to tap any letter of a word after typing one after it, the cursor immediately jumps to the end of the word.

https://github.com/user-attachments/assets/fa514ccc-c6a3-497d-8481-4cb3374819fa

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
This is already fixed in nightly and the fix will be included in the next release.
