### ISSUE TITLE
App Breaks When Switching Apps with 'Try Typing Here' Active

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#636]
### What happened?

If you trigger the 'Try typing here...' box, showing the keyboard, and switch apps using Android's recent apps button, the app breaks. Trying to switch back using the recents button becomes impossible. Only the box and the keyboard show.

The recents button here refers to tapping the first button in the navigation [in this video](https://github.com/futo-org/android-keyboard/issues/632). I don't know about the new gesture navigation Android has.

### Keyboard Version

nightly

**Comment by abb128** [comment]
This will be fixed in the next nightly
