### ISSUE TITLE
Double-tap Arrow Key to Jump to Word Edge

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#637]
### Use Cases

Usability improvement and quicker navigation while editing text.

### Proposal

Tapping twice on the left and right arrow keys should cause the cursor to jump to the left and right edges of the 'active' word. Potentially, tapping thrice should cause it to jump to the respective ends of the line the cursor is on. 

### References

- #632 This feature turns that bug into a better-designed feature that users can control and properly use

**Comment by YellowRoseCx** [comment]
If tapping twice on the arrow key jumped to the end of a word, how could you use the arrow key to navigate to a specific letter inside the word?

**Comment by abb128** [comment]
This doesn't appear to be a standard feature so it would be unexpected for users, and it'd conflict with the act of rapid tapping to move to a specific letter unless you carefully timed your cursor moves to be slower. You can use the arrows on the Text Editor action along with the word-jump button if you're doing some text editing that requires rapid jumping between words.

**Comment by abb128** [comment]
The settings menu is bloated as-is and needs some reworking. I'm not convinced that this feature would be usable in any real way, so it will not be added for now
