### ISSUE TITLE
Feature request: Add the option to use a Numpad Keyboard layout

### ISSUE THREAD

**Issue by CyberCimmerian** [futo-org/android-keyboard#64]
Hi there.

I want to request an option to change the Number row to a PC-like Numpad when you click on the "?123" button, so you can have it like this:

789
456
123
0

Thank you.

**Comment by Alex9001** [comment]
Yeah this is pretty much a must. Unusable without it, when one must enter numbers. Too much attention is necessary to click the right button. Going back to florisboard until you can get this implemented. Here is how it should work:

https://github.com/futo-org/android-keyboard/assets/2770710/d0cafe4b-c382-403c-a836-51786a470ba5

**Comment by thenicnet** [comment]
I too would like to add my vote for this feature.

**Comment by TCNOco** [comment]
This. This is what's pulling me back to Swiftkey, sadly.
Having the numpad row option is great and all, but a numpad option is what would make it for me.
[Swiftkey's implementation is simple](https://support.microsoft.com/en-us/topic/how-do-i-turn-the-number-row-on-off-in-microsoft-swiftkey-keyboard-b9fc7e22-69f2-4560-8adc-36435a73cd91), and something I've grown to need
![image](https://github.com/user-attachments/assets/d6113c7f-6fd9-4758-aa89-40129035fe50)

**Comment by dschibster** [comment]
I can only concur. I would be delighted to use something else but it comes up far too often for me that I have to enter numbers that a normal row just doesn't cut it.

**Comment by marbv1** [comment]
Same for me. I'm an engineer and I need to enter big numbers and numerical sentences too often.
I use to use AnySolftKeyboard where I get the numpad quickly by pressing "?123", then "=\<", and then "123". Its just 3 taps in the same place.
![Screenshot_20240722_180615_Mull](https://github.com/user-attachments/assets/9f93b0f7-f534-47cd-b732-c713b089a89d)

**Comment by Localhorst86** [comment]
I have tried man keyboards in an attempt to get rid of Swiftkey. Unfortunately, the convenience of its Numpad view (with most important special characters available) is unmatched, something I cant see myself going without.

**Comment by skj-skj** [comment]
Just adding Gboard Numpad layout for reference:

![Gboard-Numpad-Layout](https://github.com/user-attachments/assets/c5b04fa3-6128-47c8-b23b-01b9e2a028ff)

**Comment by itsordinaryperson** [comment]
Add my vote too. [HeliBoard](https://github.com/Helium314/HeliBoard) gives numpad by long press symbols key(i.e. ?123 below shift).

**Comment by abb128** [comment]
This has been added in nightly, it can be activated by the new 1234 button in symbols mode

![image](https://github.com/user-attachments/assets/e7d52ae8-463f-4605-8c61-af64cd94d158)

**Comment by kineticmeasure** [comment]
> This has been added in nightly, it can be activated by the new 1234 button in symbols mode
> 
> ![image](https://private-user-images.githubusercontent.com/65567823/369687059-e7d52ae8-463f-4605-8c61-af64cd94d158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODQwNDUsIm5iZiI6MTcyNzE4Mzc0NSwicGF0aCI6Ii82NTU2NzgyMy8zNjk2ODcwNTktZTdkNTJhZTgtNDYzZi00NjA1LThjNjEtYWY2NGNkOTRkMTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEzMTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhN2RmMmFlMjYyYmU4ODg1ZGUxZDQ0NTEwZTBhMDM1NDBhYjA5MWY0NDk0NjkyZDc3N2M2ODY3N2VjZjY3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aNWZPdqxxt0cQAvl2BEhrtIi48VcsEhJU3y9w3cdyLQ)

Not sure what you mean with "nightly".
I have the  app updated, but still don't see the 1234 button you mentioned...

**Comment by Localhorst86** [comment]
> Not sure what you mean with "nightly". I have the app updated, but still don't see the 1234 button you mentioned...

"nightly" are builds based on the bleeding edge source code. While I don't know where nightlies can be downloaded, the github releases has the latest build built in july.

You'll either have to find the place to download nightlies or wait for a new github release.
