### ISSUE TITLE
Add Bulgarian Keyboard Layout

### ISSUE THREAD

**Issue by bladyle** [futo-org/android-keyboard#641]
### Language

Bulgarian

### Description

Please add Bulgarian Phonetic and Phonetic Traditional layouts. 
Two most used layouts in Bulgaria. Without them the app can't be used here.

**Comment by abb128** [comment]
The topmost layout has already been added in nightly, if you're referring to a different layout please clarify
![image](https://github.com/user-attachments/assets/96f45c60-0a34-480d-86c7-92a460fb50f0)
