### ISSUE TITLE
Emoji Search Causes Keyboard Crash in Nightly

### ISSUE THREAD

**Issue by Erron-26** [futo-org/android-keyboard#642]
### What happened?

In the latest nightly version, the keyboard crashes whenever I try to search for an emoji in the search bar 
![Screenshot_20241014_160330_FUTO Keyboard](https://github.com/user-attachments/assets/ac49a202-677f-4dd2-9901-87cd3e23c427)

### Keyboard Version

0.1.23.2-157-g3e29edca4-dirty

**Comment by abb128** [comment]
Fixed in 0.1.23.2-173-g6cca2b249
