### ISSUE TITLE
Georgian Keyboard Auto-Shift Key Offering Unwanted Symbols

### ISSUE THREAD

**Issue by Bekar-T** [futo-org/android-keyboard#647]
### What happened?

Just recently the [Issue #113](https://github.com/futo-org/android-keyboard/issues/113) got resolved, it was about unnecessary capitalization in Georgian language.

Well, there's a leftover issue from that.

So, there is no capitalization, but the Shift key is supposed to offer alternate symbols on some keys. It now behaves as it should, except for the fact that it offers alternate symbols at times when it would normally switch to capital letters, like in the beginning of sentences.

This is unnecessary and unwanted, because you never expect the alternate symbols unless you specifically switched to them.

It should never auto-shift-key with Georgian basically.

### Keyboard Version

Nightly

**Comment by abb128** [comment]
This should be fixed in 0.1.23.2-179-g6ec43bae8
