### ISSUE TITLE
Option for number pad in a dailer style

### ISSUE THREAD

**Issue by rayn000** [futo-org/android-keyboard#649]
### Use Cases

Number pad in horizontal format is difficult to type when there is a text with mostly numbers.

### Proposal

Keeping the number pad in a dailer style will be helpful in typing faster. The image is the reference from Swiftkey.

![Screenshot 2024-10-16 174600](https://github.com/user-attachments/assets/f8d82e4b-c0b5-400a-88d0-cdf0938f92df)

**Comment by abb128** [comment]
This layout is already implemented in nightly and it'll be available in the next release
![Screenshot From 2024-10-16 19-15-22](https://github.com/user-attachments/assets/6129e43f-877d-467f-bde5-04efa347aaa0)

**Comment by jmbreuer** [comment]
Is this already released?

If so, how do I enable it?

If not, what's the roadmap?

**Comment by abb128** [comment]
Yes tap the 1234 button left of spacebar in symbols mode

**Comment by jmbreuer** [comment]
> Yes tap the 1234 button left of spacebar in symbols mode

Thanks! Did not (immediately) see that.

**Comment by jmbreuer** [comment]
Is there a way for the number pad view to always open first when switching from the alphabetic keyboard (and the thing with the number row at the top requiring one more tap)?

**Comment by Zvonimir-FUTO** [comment]
> Is there a way for the number pad view to always open first when switching from the alphabetic keyboard (and the thing with the number row at the top requiring one more tap)?

No there is currently no way to change that.
