### ISSUE TITLE
Gestures for Non-Swipe Typing Mode

### ISSUE THREAD

**Issue by danielb2** [futo-org/android-keyboard#65]
1. swipe right for adding space
2. swipe left for deleting word to the left

**Comment by AQDuck97** [comment]
> 1. swipe right for adding space
> 2. swipe left for deleting word to the left

Actually I just found that it *does* have "swipe left to delete word" when swipe-typing is disabled, you swipe from the backspace and it will do the whole word.

Definitely would like gestures for switching keyboard types, languages, etc. though.

**Comment by danielb2** [comment]
> Actually I just found that it _does_ have "swipe left to delete word" when swipe-typing is disabled, you swipe from the backspace and it will do the whole word.

doesn't work for me. Just moves the cursor position.

**Comment by AQDuck97** [comment]
> > Actually I just found that it _does_ have "swipe left to delete word" when swipe-typing is disabled, you swipe from the backspace and it will do the whole word.
> 
> doesn't work for me. Just moves the cursor position.

If you do it slowly it will move the cursor (should also show a highlight to indicate what will be removed)
Swiping on the space bar moves the cursor

**Comment by danielb2** [comment]
> > > Actually I just found that it _does_ have "swipe left to delete word" when swipe-typing is disabled, you swipe from the backspace and it will do the whole word.
> > 
> > 
> > doesn't work for me. Just moves the cursor position.
> 
> If you do it slowly it will move the cursor (should also show a highlight to indicate what will be removed) Swiping on the space bar moves the cursor

I tried.  it was a no-go for me

**Comment by dean-futo** [comment]
> > > > Actually I just found that it _does_ have "swipe left to delete word" when swipe-typing is disabled, you swipe from the backspace and it will do the whole word.
> > > 
> > > 
> > > doesn't work for me. Just moves the cursor position.
> > 
> > 
> > If you do it slowly it will move the cursor (should also show a highlight to indicate what will be removed) Swiping on the space bar moves the cursor
> 
> I tried. it was a no-go for me

I can confirm that this works. Please make sure you're updated to the latest release, 0.1.24.

**Comment by danielb2** [comment]
@dean-futo how about right to add a space?

**Comment by dean-futo** [comment]
@danielb2 swiping right on the spacebar to add a space?

**Comment by danielb2** [comment]
> @danielb2 swiping right on the spacebar to add a space?

The ask is to swipe left or right anywhere on the keyboard in no flow mode, not just on spacebar
