### ISSUE TITLE
Highlighting Gets Stuck in Text Fields

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#651]
### What happened?

If some or all the text in a text field that is, primarily, not a search field is highlighted, automatically when focusing in on the field or manually, and you try to remove the highlight by tapping on the left or right arrow keys, it breaks. This happens in https://old.reddit.com subreddit sidebar search fields, https://xcancel.com/settings?referer=%2F link replacement fields, and many others. 

If only some of the starting characters or all the text is highlighted, the left arrow keys 'erases' the highlight one letter per tap.

If only some of the starting characters of the text is highlighted, the right arrow key drags the highlight across with it one letter per tap. The key becomes useless if all the text is highlighted.

The correct behavior, erasing the entire highlight with the first tap and placing the cursor at the respective end, is only seen if the highlight is in the middle of the text or does not cover the first character of the text.

The underline bug portion of #621 might be relevant.

### Keyboard Version

nightly-unstable

**Comment by abb128** [comment]
Is your keyboard shifted when this occurs? When the keyboard is shifted it sends Shift + Left Arrow and Shift + Right Arrow which drags the selection in some apps, though this isn't very consistent across apps so it might be less confusing to remove it

**Comment by abb128** [comment]
The behavior was changed in latest nightly and shift should no longer affect it
