### ISSUE TITLE
Add 'Next Sentence' Button to Swiping Data Collection Page to Correct Mistakes

### ISSUE THREAD

**Issue by LeonelRFF** [futo-org/android-keyboard#655]
### Use Cases

When typing on the Keyboard Swiping Data Collection page, I often find myself misspelling the last word of a sentence. To correct it, I have to swiftly hit the delete key.

### Proposal

Consider adding a 'Next Sentence' button instead of automatically switching, as I've sometimes made mistakes and didn't have time to press the button to correct the word.

### References

https://swipe.futo.org/keyboard

**Comment by abb128** [comment]
You should be able to backspace at any time to revisit previous sentences, does that not work for you?
