### ISSUE TITLE
Voice Input Causes Keyboard to Collapse with Swipe Malfunction

### ISSUE THREAD

**Issue by mad1mystic** [futo-org/android-keyboard#656]
### What happened?

When spoken from voice input nothing happens the keyboard collapses,  this problem starts when I install some root apps and give root Permission,  uninstalling the app doesn't help, even after reinstall the problem persist!  I had to format my phone for voice input to work again.  Surprisingly voice input works on work Profile. This bug or problem has been on latest stable release as well the nightly build and even on Dev build.  Swipes don't get registered sometimes I know it's alpha but still letting know
[18_10-21-39-15_439.log](https://github.com/user-attachments/files/17438288/18_10-21-39-15_439.log)
[FUTO Keyboard [Dev Build] log 83a2bc758635.txt](https://github.com/user-attachments/files/17438292/FUTO.Keyboard.Dev.Build.log.83a2bc758635.txt)
[Futo log 1.log](https://github.com/user-attachments/files/17438293/Futo.log.1.log)
[New file.txt](https://github.com/user-attachments/files/17438295/New.file.txt)
[Futo log 2.log](https://github.com/user-attachments/files/17438296/Futo.log.2.log)

### Keyboard Version

0.1.23.2 Dev and stable build

### Text field info

Happens in all apps

**Comment by dean-futo** [comment]
Consolidated into #664
