### ISSUE TITLE
Issue with “Try Typing Here” Pop-Up After App Switching

### ISSUE THREAD

**Issue by fanno** [futo-org/android-keyboard#66]
When i first installed the app and pressed it opened the "try typing here" popup.

i pressed it and would not work because i did not have a danish installed if i pressed back. it would go back to "main screen"

if i try to reopen the app it would go backto the white "try typing here" popup.

i had to "force" close the app and then reppen the app and install danish language pack for it to not do this.

0.1.22-playstore
VC 10804

not sure if you need more info

**Comment by GM-Script-Writer-62850** [comment]
I think i found a easy way to reproduce this

1. open typing here popup
2. switch apps
3. switch back
  1. main window is gone, only the popup remains
  2. closing popup switches out of the app
  3. app remains open
  4. repeat 2 and 3 till you close it from app switcher

**Comment by fanno** [comment]
I can confirm, i can recreate it that way as well.

So it has nothing to do directly when the danish language missing, but it was a side effect of it.

**Comment by dean-futo** [comment]
@fanno will you provide a video of this issue?

**Comment by GM-Script-Writer-62850** [comment]
thought my instructions were very clear...

here is a recording of triggering this bug:
https://github.com/user-attachments/assets/f0758a27-9655-42f4-a628-dd7aea402910

**Comment by abb128** [comment]
This should be fixed in the upcoming 0.1.24 release
