### ISSUE TITLE
Swipe Misrecognizes Finnish 'Minä' but Detects 'Mina' Instead

### ISSUE THREAD

**Issue by Jonta** [futo-org/android-keyboard#661]
### What happened?

Keyboard layout: Nordic (å, ö, ä-cluster to the right)
"a" is on the left, "ä" is on the right of the keyboard

Case Alpha
1. Swipe "Minä"
2. Suggested words "Mum" (only suggested word)
3. Should've been suggested: "Minä"

Case Bravo
1. Swipe "Mina"
2. Suggested words: "Minna", "minä", "miina"
3. Should've been suggested: "Minna", "miina", other

Notes:
- I don't speak Finnish
- I think Case Alpha is worse than Case Bravo
- I don't know what Finnish speakers expect or think of Case Bravo
- This also happens with Norwegian using an æøå-cluster. «Håret» is detected when swiping «Haret»

Dictionary: The Suomi-dictionary suggested by FUTO keyboard

### Keyboard Version

v0.1.23.s-playstore

**Comment by dean-futo** [comment]
Consolidated into #665

**Comment by dean-futo** [comment]
Similar to #560 - merging this issue into that one. See #560 for details.
