### ISSUE TITLE
Consolidated Meta-Issue: Inconsistent Auto-Capitalization and Voice Input Capitalization

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#663]
### What happened?

There are inconsistencies in the use of auto-capitalization not only across different modes of input (swipe typing, voice input and typing), but also in different contexts such as after a full stop or when typing in between a sentence, swearwords or sending an emoji. A common pattern amongst users is that even when auto-cap is turned off, they encounter the problem of incorrect capitalization of such words as names as well as words used after punctuation or voice texting. Furthermore, there are swiping users who cannot turn all caps off when it should be off when it is turned on or have trouble with capitalization when it is turned on. These inconsistencies cross different devices when coming in to use for the same application further adding on to the disruption of user experience.

Consolidated Tickets:
- #150: Many users have reported that even though the auto-capitalization feature is disabled the first word in a voice input is incorrectly capitalized.
- #154: Many users have reported that even if they turn the feature off all words are in caps in the output and the feature does not toggle.
- #252: Auto capitalization is observed to persist even after the first sentence for users who employ the all-lower-case mode, ignoring the set-off mode.
- #286: Caps lock unexpectedly turns on when returning to apps like WhatsApp, disrupting regular typing.
- #284: Auto-correct encourages the use of capitalization even if the auto-cap setting is off for contraction and proper nouns.
- #270: Behavior of auto-capitalization is inconsistent and depends greatly on the application used or the text field in question.
- #294: Auto-capitalization appears to not function after a number of punctuation marks or emojis where normally a capital would be expected.
- #304: After switching apps, the keyboard often continues typing in uppercase, even when it should be in lowercase.
- #388: Even with auto-capitalization disabled, auto-correct still capitalizes words, especially contractions or proper nouns.
- #469: Fix mid-sentence capitalization issue when resuming dictation: When you resume voice dictation in the middle of a sentence, the first word is incorrectly capitalized.
- #520: When using voice-to-text, words are capitalized even if auto-cap is off, particularly when continuing a sentence mid-phrase.
- #547: Autocorrect still capitalizes words like "that's" even when auto-cap is turned off, especially at the beginning of sentences.
- #552: Auto-capitalization happens unpredictably even when it's turned off, particularly with common words like "why."
- #601: Auto-capitalization behaves inconsistently across various apps and punctuation, often failing after periods or during mid-sentence edits.

Users encounter inconsistent auto-capitalization behavior across different input methods and contexts. Auto-capitalization continues even after voice input is turned off. When using swipe typing, all letters appear in caps despite the auto-cap feature being disabled. The auto-capitalization often acts unpredictably after punctuation marks, emojis, and when switching between apps. If dictation is resumed mid-sentence, the first word is incorrectly capitalized, which can be frustrating, especially for those who prefer typing in lowercase. Additionally, caps lock can be unexpectedly activated when switching apps, forcing users to delete all text before they can type normally again. This issue occurs across various devices, operating systems, and app environments, including standard typing, swipe input, and voice-to-text.

Proposed Fixes:
- Ensure that disabling auto-capitalization applies universally across all input methods and contexts, including swipe typing, voice input, and regular typing.
- Investigate inconsistencies that arise after punctuation marks, emojis, and during app switching to ensure proper lowercase or uppercase behavior.
- Fix mid-sentence dictation issues where capitalization occurs unnecessarily, especially when resuming from a pause.
- Address the unexpected caps lock activation when switching apps, ensuring that the keyboard defaults to the proper case setting based on the user's input preferences.
- Improve the auto-correct behavior so that it respects the capitalization settings, particularly for contractions and proper nouns.

### Keyboard Version

Various

**Comment by Hitu1197** [comment]
When you type a word in full caps like 'TEST' then the suggestion bar shows suggestions in full caps but if you hit space and then backspace then suggestions switch to non capitalized version of the same word.
 Eg. TEST shows "TESTS TEST TESTING" as suggestions but if I hit space and backspace then it switches to "tests test testing" in suggestion bar

**Comment by dean-futo** [comment]
Thank you for all of your input. I further consolidated this meta-issue into more specific segments, so closing this one. Breakdown:
- #150 and #469 is now merged with #520
- #286 is now merged with #154
- https://github.com/futo-org/android-keyboard/issues/252, https://github.com/futo-org/android-keyboard/issues/388, and https://github.com/futo-org/android-keyboard/issues/552 are now merged with #520
- https://github.com/futo-org/android-keyboard/issues/270, https://github.com/futo-org/android-keyboard/issues/294, and https://github.com/futo-org/android-keyboard/issues/304 are now merged with #601

The others are standalone. Please provide any further input on those specific segmented issues.
