### ISSUE TITLE
Voice Input Crashing and Swipe Malfunction Across Languages and Devices

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#664]
### What happened?

The keyboard often crashes or closes unexpectedly during or after voice input on different devices and languages, particularly in multilingual and root-enabled setups. This problem usually occurs after stopping voice input or while processing speech-to-text, with frequent reports on GrapheneOS and in non-English languages such as Hebrew. Reinstalling the keyboard or uninstalling root apps does not fix the issue, which also interferes with swipe typing.

Consolidated Tickets:
- #656: When using voice input, the keyboard crashes, particularly after installing root apps. There are intermittent failures in swipe typing registration.
- #467: The keyboard crashes and restarts after voice input is ended, especially noted on GrapheneOS and various devices.
- #444: The internal voice input crashes the keyboard when used in a browser, forcing users to rely on external voice input.
- #352: The keyboard crashes after processing voice input, working correctly only in the work profile. This issue continues even after reinstallation.
- #144: The keyboard crashes when using voice input with Hebrew or other non-English language packs in multilingual settings.

### Keyboard Version

Various

**Comment by dean-futo** [comment]
@abb128 I'm not able to reproduce this on the stable or nightly build in any browser, including etc Chrome, Firefox, Brave, Edge, etc (without root apps or GrapheneOS installed), so I suspect that the crashing issue is not a problem with the keyboard itself, but rather it's compatibility with alternative operating systems like GrapheneOS, ColorOS, etc.

**Comment by abb128** [comment]
From further investigation this happens when the personal dictionary has an extensive number of words (hundreds or thousands), it's been fixed in nightly
