### ISSUE TITLE
'Auto-correct' Implementation Is Wrong

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#675]
### What happened?

FUTOBoard, like Swiftkey, has an autocorrect toggle that, when activated, makes the keyboard correct mistyped words or complete incomplete words to the middle word in their respective suggestion bars. 

Swiftkey does this perfectly 100% of the time after tapping spacebar or typing a punctuation but FUTOBoard only does this if the middle word is **bolded** even if the middle suggestion already has the word you want. Tapping spacebar or typing a punctuation here in FUTOBoard is useless if the middle word is not bolded. This is extremely frustrating because many times, despite the middle suggestion already having what you want, you are forced to type out more characters than needed just to get it to '**bold**', or worse, give up on it because if you type too many characters or delete some, the middle suggestion never gets bolded again for that 'round' of suggestions.

This boldening and its requirement, which was only added in a recent nightly, should be removed and fixed together with #615 (which was prematurely closed but still not fixed). They serve no purpose when autocorrect is meant to settle for the middle one anyways and only add unnecessary confusion, and also steal precious space in an already cramped area. If emphasis is the point, simply make the middle word white and the secondaries gray.

### Keyboard Version

nightly-unstable

**Comment by abb128** [comment]
Autocorrect is only meant to trigger when the algorithms are confident enough that your word is definitely a misspelling of the top predicted word. There's a slider in Predictive Text > Advanced Parameters for autocorrect threshold, which you can set to 0.0 if you want it to always autocorrect (note it only takes effect for English with Transformer LM enabled). The default value was chosen to maximize accurate corrections and minimize miscorrections (replacing an intended word into something else)

**Comment by abb128** [comment]
Everything described here is standard in all mobile keyboards (granted, the quotation marks specifically aren't common on Android, only iOS) so I don't understand your confusion.
