### ISSUE TITLE
Fix Incorrect Backspace Keydown Event on Web

### ISSUE THREAD

**Issue by shresthabijay** [futo-org/android-keyboard#679]
### What happened?

Futo keyboard triggers keydown event with "unidentified" key on pressing backspace on the web input. Other android keyboards like gboard, swift keyboard etc trigger correct keydown event with "backspace" key. This bug makes Futo difficult to use for web based outliners and note-taking apps.

### Keyboard Version

0.1.23.2

**Comment by dean-futo** [comment]
@shresthabijay will you include a video please?

**Comment by abb128** [comment]
This should be improved in the next minor update
