### ISSUE TITLE
Add Toggle for Auto-Correction of Last Word on Send

### ISSUE THREAD

**Issue by machinaeZER0** [futo-org/android-keyboard#689]
### Use Cases

I'd love to hit send on a text message without needing to add a space or punctuation mark to have Futo autocorrect the last word, in the event that it was a typo. I'm sure in some cases this would cause unintended autocorrects, hence the idea to make it a dedicated/separate toggle from the current setting.

Not a dealbreaker on my end since most (all?) software keyboards I use do not function this way, but would be pretty cool to see implemented if at all possible :)

**Comment by machinaeZER0** [comment]
Lol. Great talk dude ✌

**Comment by dean-futo** [comment]
@machinaeZER0 thanks for your request but having an autocorrect trigger on send would be unreliable because the keyboard may not consistently recognize send actions across various apps, which could lead to inconsistency and a whole slew of new bugs and unnecessary frustration.

**Comment by machinaeZER0** [comment]
Makes sense, appreciate the explanation!
