### ISSUE TITLE
Toggle to Remove Fake Quotes in Suggestions

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#691]
### What happened?

Some nightly introduced quotes in suggestions shown (#615) but if you select the quoted suggestion, no quotes actually appear in the output. I do not know what makes this misleading visual artifact worth having but there should be a toggle to turn it off.

### Keyboard Version

nightly-unstable

**Comment by dean-futo** [comment]
@issuant it's a UI element that helps signal to users that they are typing in a custom word that's not being suggested to them.

**Comment by dean-futo** [comment]
@abb128 what are your thoughts on this?
