### ISSUE TITLE
Add Haptic Feedback for Cursor Movement Using Spacebar and Backspace

### ISSUE THREAD

**Issue by machinaeZER0** [futo-org/android-keyboard#693]
### Use Cases

One thing I appreciate from other keyboards is that when I move the cursor around (usually by holding+swiping on the space bar or backspace key), I get a vibration per character i pass through. This is super helpful (literal) feedback for not accidentally moving too far/selecting too much, and in some cases means i could even look away and be pretty sure where I've ended up :)

If it's possible to implement something similar in Futo, that would be amazing - and sincere apologies if it's an option already that I somehow missed!

**Comment by dean-futo** [comment]
Closing as duplicate of #747

**Comment by KaKi87** [comment]
Why is the older one considered as the duplicate ?

**Comment by Zvonimir-FUTO** [comment]
> Why is the older one considered as the duplicate ?

It doesn't really matter. We just need one of these to not forget about it. Which one is older doesn't play any role if we are going to work on it or not.
