### ISSUE TITLE
One-Handed/Floating Keyboard Modes

### ISSUE THREAD

**Issue by ritvikbanakar** [futo-org/android-keyboard#695]
### Use Cases

I switched from Gboard/Samsung Keyboard and currently use a large Samsung Ultra phone. I am desperately missing the one-handed usability from my prior keyboards. Adding it on both the application as well as https://swipe.futo.org/ would greatly aid ease of use.  

### Proposal

Uploaded images of Samsung Keyboard implementation of One-handed and Floating modes.
![onehanded](https://github.com/user-attachments/assets/a5a97eb4-b506-4513-ab01-27544f9fb4bb)
![floating](https://github.com/user-attachments/assets/1cc768cd-e296-471e-9c54-d479a75509d0)

**Comment by abb128** [comment]
Already part of the upcoming release: https://github.com/futo-org/android-keyboard/releases/tag/0.1.24-rc1
