### ISSUE TITLE
Feature Request: Clipboard UI

### ISSUE THREAD

**Issue by ImranR98** [futo-org/android-keyboard#7]
It would be great to be able to access (and modify) the system clipboard instead of only the most recently copied item.

**Comment by FireNinja7365** [comment]
I'm just going to add to this lol, please make it work the same way as openboard's clipboard

**Comment by P-a-d-r-a-i-g** [comment]
Yes, clipboard would be great.

**Comment by abb128** [comment]
Closing as a clipboard history is already implemented
