### ISSUE TITLE
[Feature request] Swipe space to change language

### ISSUE THREAD

**Issue by ukrolelo** [futo-org/android-keyboard#70]
Pleeeaasee i have 4 languages that i need to change between <3. P.S.I was using samsung keyboard and when i  typed with mistakes i thought it is me. But with this keyboard my keypress is exactly what i want to press, how the F you created better typing experience than Samsung???? <3

**Comment by ukrolelo** [comment]
Duplicate :-X sorry
https://github.com/futo-org/android-keyboard/issues/52

**Comment by abb128** [comment]
Closing as duplicate of #52
