### ISSUE TITLE
Backspace Swipe No Longer Works for RTL Languages

### ISSUE THREAD

**Issue by FaridZelli** [futo-org/android-keyboard#701]
### What happened?

Fixing the inverted spacebar cursor movement for RTL languages has caused the backspace swipe to stop working.

### Keyboard Version

0.1.24-rc1-playstore

**Comment by FaridZelli** [comment]
@dean-futo Please, kindly consider changing the label to high or very high priority. This is a major regression that breaks a basic feature, I don't see how it's any less important than autocorrect or haptic feedback related bugs with that label.

**Comment by abb128** [comment]
This will be fixed for the full release of 0.1.24
