### ISSUE TITLE
Hold to Paste Directly from Clipboard Manager

### ISSUE THREAD

**Issue by BabyOilJohnson** [futo-org/android-keyboard#714]
### Use Cases

When I have to paste anything I have to go through the clipboard manager.

### Proposal

By hold press the clipboard manager to get pasted.

### References

#447

**Comment by BabyOilJohnson** [comment]
Close this if you think this is a duplicate of #447 .

**Comment by dean-futo** [comment]
Indeed very similar to #447 - merging this request into that one.
