### ISSUE TITLE
The Word "Gay" Is Marked as Offensive

### ISSUE THREAD

**Issue by pionaiki** [futo-org/android-keyboard#716]
### What happened?

When I use the "block offensive words" option in the autosuggestion blocklist, the word "gay" is autocorrected to "happy" using "English v1". This is not what should happen as the word gay is not offensive and treating it as such is problematic.

This doesn't appear to be an issue with my phone's dictionary as other keyboard apps using it do not have this problem.

![signal-2024-10-26-22-02-43-469-2](https://github.com/user-attachments/assets/01eeb435-a8e1-4703-b998-fbc7ce5e3e9d)
![signal-2024-10-26-22-02-43-469-1](https://github.com/user-attachments/assets/742ae391-0cc0-4d82-b3d8-a70723b51a08)
![signal-2024-10-26-22-02-43-469](https://github.com/user-attachments/assets/71c69023-eca3-4a13-b703-ab86b2e80434)

### Keyboard Version

0.1.23.2-playstore

**Comment by dean-futo** [comment]
@pionaiki are you able to reproduce this? I'm not.

**Comment by abb128** [comment]
This is already fixed in the release candidate
