### ISSUE TITLE
Password input Number Row Hight is innaccurate

### ISSUE THREAD

**Issue by haldi4803** [futo-org/android-keyboard#718]
### What happened?

The new feature to add number Row in Password fields is awesome! Love it!
But the size of the Keys changes if the Number Row shows up! That should not be. It disrupts your normal typing habbit.
IMHO the number Row should simply go on top.

![Screenshot_2024-10-28-05-47-38-62_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/1bd1059f-3355-41d3-ac5d-6d2231d4ae96)
![Screenshot_2024-10-28-05-47-46-94_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/3533bef4-3fe3-4eab-b074-4aadf420a299)

### Keyboard Version

0.1.24-rc1-15-g6278a5cdf-unstable

### Text field info

Any password Field.

**Comment by abb128** [comment]
You raise a good point, it will be updated to keep the height of existing keys the same if number row is triggered by the input field
