### ISSUE TITLE
Keyboard Crashed While Using FOSS Telegram

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#730]
### What happened?

A user was creating a very large block of text using FOSS Telegram, using multiple instances of recording back to back without having sent the block of text yet.

### Keyboard Version

Unspecified

**Comment by David-Prock** [comment]
The version was the latest, I keep up to date with F-Droid

**Comment by abb128** [comment]
@David-Prock If this continues to occur on the stable 0.1.24 release please open a new issue
