### ISSUE TITLE
[Feature Request] Multiple languages at same time

### ISSUE THREAD

**Issue by PhilJbt** [futo-org/android-keyboard#74]
I continually alternate between French and English writing. GBoard allows me to predict both languages, and this feature helps me a lot. Especially as many of my French sentences contain English words because of their technical aspect.

**Comment by CreaGab** [comment]
I also hope that this will be implemented because I write in German, French and English almost on a daily basis.

**Comment by abb128** [comment]
Seems to be duplicate of #38
