### ISSUE TITLE
Enhanced Language Switching and Cursor Control

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#744]
### Use Cases

A user would like to propose some features to enhance the UX of the keyboard:

**Spacebar Language Switching**
Implement a feature that allows users to switch between languages by swiping the spacebar left or right. This intuitive gesture would make multilingual typing more seamless and efficient.

**Advanced Cursor Control**
Introduce a new cursor control method by allowing users to press and hold the spacebar, then swipe in different directions:
Swipe up: Move cursor to the previous line
Swipe down: Move cursor to the next line
Swipe left: Move cursor left
Swipe right: Move cursor right

This feature would provide precise cursor placement without the need to lift fingers from the keyboard area.
By implementing these suggestions, the Futo keyboard would offer a more versatile and user-friendly typing experience, particularly for multilingual users and those who require efficient text editing capabilities.

**Comment by abb128** [comment]
This is already an option (2nd one) in long-press key settings, though up and down is currently unimplemented
![image](https://github.com/user-attachments/assets/31dd610c-d7cd-4ae6-b446-3ebbfd687995)
