### ISSUE TITLE
"Old Action Bar" is Higher Than it Should Be

### ISSUE THREAD

**Issue by vmkxyz** [futo-org/android-keyboard#756]
### What happened?

When enabling the old action bar option, the bar's hight is the same as the new bar when expanded, so it takes up more space than it needs to.

![image](https://github.com/user-attachments/assets/690df780-396a-4aa1-8ec7-2b5d28a40dd8)

### Keyboard Version

0.1.24

**Comment by Leopold702** [comment]
I'm sorry for being off-topic, but how did you enable old action bar?

**Comment by vmkxyz** [comment]
@Leopold702 go into help & feedback, click a few times on the build number to enable developer settings, go there and you'll se the option

**Comment by abb128** [comment]
This will be fixed in the next minor update
