### ISSUE TITLE
Issues in Termux After Latest Update

### ISSUE THREAD

**Issue by arbitrary-dev** [futo-org/android-keyboard#757]
### What happened?

1. Spaces not added
2. Backspace swipe moves the cursor instead
3. Sometimes keyboard seems to be unresponsive (pressing *Shift* does nothing to the layout, yet suggestions strip updates correctly)

Everything works fine in browser though.

### Keyboard Version

0.1.24

### Text field info

https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View

Debug info:
![Screenshot_2024-11-03-14-17-08-99](https://github.com/user-attachments/assets/5ff2713f-0cac-4084-8203-be5ddeaf42c3)
![Screenshot_2024-11-03-14-17-22-21](https://github.com/user-attachments/assets/d413d9f6-510a-4d7c-9d69-1180c6dbb14e)
![Screenshot_2024-11-03-14-17-38-53](https://github.com/user-attachments/assets/bb5a504a-a590-4333-b837-2b775c0e5fa8)

**Comment by abb128** [comment]
Should be fixed in nightly
