### ISSUE TITLE
Number Key Buttons Not Appearing & Number-Row Long-Press Not Working

### ISSUE THREAD

**Issue by trekshcool** [futo-org/android-keyboard#763]
### What happened?

After the update the number key seems to have lost its buttons and now just has a row of numbers with no contrast. 
![WhatsApp Image 2024-11-04 at 14 51 43_14ba2b20](https://github.com/user-attachments/assets/5806dc3b-d9eb-4016-affc-8ab58d83624d)

### Keyboard Version

0.1.24-playstore

**Comment by trekshcool** [comment]
I also just noticed that long press no longer works on the number row.

**Comment by dean-futo** [comment]
@trekshcool @AT181903 which phones and operating systems are you using?

**Comment by trekshcool** [comment]
I am using Oppo F19

**Comment by abb128** [comment]
This is a design change, and you can access the subscripts/superscripts still by switching to the symbols mode. #627 requests this to be revertible
