### ISSUE TITLE
Some English Words Starting with Capital Letters

### ISSUE THREAD

**Issue by merlinuwe** [futo-org/android-keyboard#764]
### What happened?

Settings: On the space button there is Deutsch selected. I usw Herman language. 

When I type, often some english words have their first letter capitalized. What can I do to change this behaviour? Do I have to ARD english language and/or keyboard? 

### Keyboard Version

0.1.24

### Text field info

This is an example sentence.

**Comment by dean-futo** [comment]
Will you upload a video please? Obviously some English words that are nouns are automatically capitalized, however, there have been some auto-capitalization bug reports so something could be going on with that too.

**Comment by PhilC813** [comment]
I think this points out to the same as many issues like #698

**Comment by BurntVoxel** [comment]
Huh, yeah, looks like the same bug. Guess it's multilingual.

**Comment by dean-futo** [comment]
Closing as duplicate of #698
