### ISSUE TITLE
Color Mismatch in Language Change Pop-Up

### ISSUE THREAD

**Issue by BabyOilJohnson** [futo-org/android-keyboard#767]
### Use Cases

When I tried to change language, I saw that in AMOLED dark purple and dark mode themes(I only tried some themes only like AOSP material dark and FUTO VI theme has no problem) there is color mismatch in keyboard layout(QWERTY etc..) when it is selected.
Here is the proof
<details><summary>Screenshot</summary>
<p>

![Screenshot_20241105-110045](https://github.com/user-attachments/assets/f7670bc4-3fc6-4776-8769-a0d4279f8740)

</p>
</details> 

### Proposal

It should match with the selected theme.

**Comment by abb128** [comment]
This will be fixed in the next release
