### ISSUE TITLE
Keyboard doesn't respect flag for no personalized learning

### ISSUE THREAD

**Issue by tschlunk** [futo-org/android-keyboard#78]
See documentation for this flag [here](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING).

Apps such as browsers, messaging apps, shopping apps, and games may set this flag to tell the soft keyboard to not learn from what the user is typing, either for privacy reasons or because the expected input is not valid words.

It would be great if FUTO Keyboard could check this flag and respect it by not adding words to the user history when it is set. Additionally, a visual indicator of this flag to the user would be a nice touch.

**Comment by abb128** [comment]
This will be fixed in the upcoming release

**Comment by Philippe-Choquette** [comment]
Wondering if this been fixed?

When I make a search using private navigation in the Opera web browser, there's no visual cue on the keyboard to reflect the flag.

@abb128

**Comment by abb128** [comment]
@Philippe-Choquette There is no visual cue currently but the flag is respected.

**Comment by itsordinaryperson** [comment]
I think adding visual cue is essential. Apart from automatic detection the user can turn it on/off when needed. Most of the keyboards have this functionality.
