### ISSUE TITLE
Wrong Belarusian Layout

### ISSUE THREAD

**Issue by PlagaMedicum** [futo-org/android-keyboard#787]
### Language

Belarusian

### Description

Last update broke my Belarusian layout. For some unknown reason Belarusian " і " was changed by Russian " и ". Some strange layout "студенческий" ("student's", if translated) was added, named in Russian. I don't understand how can I use this russified layout. + all this time I have issues with the " ’ " symbol, wich I need to replace by english " ' " from additional symbols menue wich is inconvenient and formally incorrect.

If you don't trust me, check Wikipedia and other keyboards.

**Comment by abb128** [comment]
Additional layouts were added to increase choice but there was a bug that replaced и, this will be corrected in the next release. I'm not sure what you mean about the ’ symbol, could you explain more?

**Comment by PlagaMedicum** [comment]
there is additional apostrophe used in belarusian words but technically it should be other utf sybol (2019, not 0027). E.g. бур’ян, р’яны, п’яны, з’ява and more.

UTF codes are also included in corresponding wikipedia article: https://en.wikipedia.org/wiki/Belarusian_alphabet. In Belarusian Wikipedia it is mandatory to use the " ’ " symbol in belarusian words, not english apostrophe " ' ".
