### ISSUE TITLE
F-Droid Repo Marks Old Version as Suggested

### ISSUE THREAD

**Issue by lucasmz-dev** [futo-org/android-keyboard#788]
### What happened?

0.1.24 was launched, however while the F-Droid repo got the update, it isn't the release marked as suggested, and needs to either be updated manually or beta updates has to be enabled for apps.

I can't tell if this is intentional... usually it'd be, but GitHub doesn't tag it as a pre-release or anything, it seems like a proper release.

### Keyboard Version

0.1.23.2

**Comment by abb128** [comment]
Will be fixed
