### ISSUE TITLE
feature reuqest: language switch button

### ISSUE THREAD

**Issue by aly-k** [futo-org/android-keyboard#8]
Instead of having a separate keyboard for each language, adding a language switch button would improve the user experience

example from gboard:
![image](https://github.com/futo-org/android-keyboard/assets/92282568/83946d65-64b8-4b63-be21-fdf4bfff085d)

**Comment by Divinelink** [comment]
This indeed would be very helpful.

**Comment by Business-Wizard** [comment]
Is this not already a supported usecase by long-pressing the spacebar? 
Essentially, each language is a separate keyboard layout, therefore switching layouts switches languages.

**Comment by FraYoshi** [comment]
> Is this not already a supported usecase by long-pressing the spacebar? 
> Essentially, each language is a separate keyboard layout, therefore switching layouts switches languages. 

yes, but for us, constantly writing in multiple languages, a rapid layout/lang switcher is important.. I like the approach of some keyboards, where you do not have a button, but a slider.. so slide left and you go to the previous in lone language, go right and you go to the next ^^

**Comment by Progaros** [comment]
would such customizatability help you?
https://github.com/futo-org/android-keyboard/issues/33#issuecomment-2181648113
the "language switch" button would be one of the hideable utilities

**Comment by WofWca** [comment]
> the "language switch" button would be one of the hideable utilities

I personally wouldn't need it. I want to switch the language with just one tap.

**Comment by abb128** [comment]
The ability to change the emoji key to a language switch key will be included in the next update
