### ISSUE TITLE
Keyboard key view long-press.

### ISSUE THREAD

**Issue by Kargchristopher** [futo-org/android-keyboard#80]
Like on gboard show the first long press key option for each key in superscript.

**Comment by martyfmelb** [comment]
This feature is already present in Settings → Theme → Show symbol hints.

That said, I didn't find it to be the most intuitive place to put the setting! If "Theme" was broken down into "Theme" and "Appearance", I think it would improve discoverability.

**Comment by anseltaft** [comment]
@martyfmelb thank you! I never would have found it there... I wish it would be move to the main settings area as it's the first thing I looked to enable, couldn't find it, and came here to submit a request.

**Comment by kj4ezj** [comment]
Duplicated by [issue 309](https://github.com/futo-org/android-keyboard/issues/309).

**Comment by kj4ezj** [comment]
We should close this issue, as the feature does exist.

Moving the setting in the settings menu is a different request, and deserves its own issue.

**Comment by abb128** [comment]
Closing as this option is already in Themes. It'll be moved to a more clear spot in the next update
