### ISSUE TITLE
Adjustable Key Pop-Up Size Slider

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#811]
### Use Cases

A user requests that we add a slider that allow you to adjust the size of key popups while typing, similar to the haptic adjustment slider.

### References

Email ticket #7404

**Comment by abb128** [comment]
The original email complained it was too big, the size was decreased in 0.1.24 to match key size more closely, so I will close this as the user's original issue should be fixed

**Comment by ItsProfessional** [comment]
> The original email complained it was too big, the size was decreased in 0.1.24 to match key size more closely, so I will close this as the user's original issue should be fixed

Despite the size being reduced in the update, some people (including me) prefer the older large size, so I think the issue should be reopened.
