### ISSUE TITLE
Spanish layout; ,? instead of ?

### ISSUE THREAD

**Issue by illyaro** [futo-org/android-keyboard#814]
### Language

Spanish

### Description

![,? instead of ?](https://github.com/user-attachments/assets/12883e31-d6f0-4652-951c-4124e23180e1)

In Spanish layout (Language Spanish (Spain), Layout QWERTY+) the only available in version v0.1.23.2 that is currently available in FDroid.

When you long press "." (right from the spacebar) to quickly access symbols, instead of simple "?" there we have available this weird combination ",?".

",?" should be changed back to "?" as it was 2-3 months ago
Thanks

### Complexity

Trivial

**Comment by abb128** [comment]
This is already fixed in 0.1.24, make sure to update
