### ISSUE TITLE
Voice Input Microphone Activity Indicator On Main Keyboard

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#822]
### Use Cases

A user requests that we incorporate a microphone activity indicator in the voice input corner icon (like in SwiftKey and Gboard). This will allow users to monitor the voice input status while still having quick access to the main keyboard for typing.

### References

Email ticket #7215

**Comment by abb128** [comment]
Simultaneously dictating and typing is not supported at the moment
