### ISSUE TITLE
Backspace/Delete Issue in MySudo App

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#846]
### What happened?

A user reported that the backspace/delete button on the keyboard doesn't work in the "To:" or "Cc/Bcc:" fields of the MySudo app. The issue occurs in versions downloaded from both the Play Store and GitHub via Obtanium. Other keyboards function properly, however, many keyboards from F-Droid have similar issues, with the exception of Simple Keyboard, which works correctly.

Here is a list of other keyboards I have tested that worked to delete the items and ones that didn't:
Fossify Keyboard via F-Droid (didn't work),
Simple Keyboard via F-Droid (didn't work),
HeliBoard via F-Droid (didn't work),
aaaaa via F-Droid (didn't work),
Swiftkey via PlayStore (DID work),
Simple Keyboard via F-Droid ( DID work),
Gboard via PlayStore (DID work).

https://github.com/user-attachments/assets/4162a8b0-7095-4987-a8bb-2dbcac3d56d9

### Keyboard Version

0.1.24

### Text field info

Email ticket #8569

**Comment by abb128** [comment]
This should probably be fixed in the next release as part of fixing #282
