### ISSUE TITLE
Add a language switch button

### ISSUE THREAD

**Issue by vtomilin** [futo-org/android-keyboard#85]
Right now there seems no option to have a dedicated language switch button on the main layout.  

To switch the language now one has to either long-press space, or expand the top row and tap language switcher button there.

On some keyboards one can switch languages with a swipe on the space key — just a thought.

Thak you!

**Comment by I-Dude** [comment]
Maybe a dedicated language switch button?, I dont use emojis, so having a button to switch languages in its place would be awesome.

**Comment by vgf89** [comment]
GBoard adds entries to the input method switcher for every language/layout you have selected, so doing the same thing might be good.

**Comment by I-Dude** [comment]
I use the spacebar for swiping the cursor. Maybe add a toggle so that a long press on the keyboard cycles between your language options instead of bringing upa menu that you then have to selcete the language from.

**Comment by xiyori** [comment]
There is actually a button in the menu at the top, but an additional configurable button instead of emoji would be nice.

**Comment by WofWca** [comment]
Duplicate of #8 i think

**Comment by NagBoard** [comment]
> There is actually a button in the expandable menu at the top, but that's still 2 clicks. An additional configurable button instead of emoji would be nice.

Or better yet — an option to alternate between emoji and language button

**Comment by abb128** [comment]
An option to replace the emoji key with a language switch key will be included in the next release.
