### ISSUE TITLE
Continuous Keyboard Resizing on Foldable Phones

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#851]
### What happened?

Users with foldable devices like the Galaxy Fold have reported that while the keyboard can be resized, their adjustments don't remain when switching between folded (external display) and unfolded (internal display) modes. This means users have to manually resize the keyboard each time the device changes states. One user has suggested adding a feature that allows for pre-saved keyboard sizes for each mode, so the keyboard can automatically adjust to the appropriate dimensions based on whether the device is folded or unfolded.
![Screenshot_20241121_123301_Firefox](https://github.com/user-attachments/assets/4504835a-14b3-4d57-a5a8-4a9472ecd5a0)
![Screenshot_20241121_123250_Firefox](https://github.com/user-attachments/assets/4e4e3219-ebdf-4583-bd96-61b6ae541a67)

### Keyboard Version

0.1.24

### Text field info

Email tickets #6439 and #6443

**Comment by abb128** [comment]
This should already be implemented in 0.1.24, I will follow up with them to get details on whether this is a bug
