### ISSUE TITLE
Forward Slash Showing Up on Keyboard in Browser Search When It Shouldn't

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#857]
### What happened?

The forward slash key, which has been removed from the main keyboard screen in the latest release, is showing up on the keyboard when searching in browsers. This is the case in Chrome, Firefox, Brave, DuckDuckGo, Edge, and presumably the rest.

### Keyboard Version

0.1.24

### Text field info

Email ticket #8593

**Comment by dean-futo** [comment]
#855 is a duplicate - merged that issue into this one.

**Comment by abb128** [comment]
Duplicate of #786

**Comment by dean-futo** [comment]
@abb128 merged
