### ISSUE TITLE
[Feature Request] Add Quick Action Toolbar

### ISSUE THREAD

**Issue by issuant** [futo-org/android-keyboard#86]
The current design requires you to tap the '>', scroll to the very end, and then tap the clipboard icon again just to see your clipboard. That's really unpleasant UX. 

A collapsible, quick action toolbar at the top (above the predicted words) like in Swiftkey where you can place your most used functions (clipboard, voice input, language, etc) is ideal. Reference: https://youtu.be/J7WwdpmUkB0?t=27

**Comment by abb128** [comment]
Closing in favor of #244
