### ISSUE TITLE
Haptic Feedback While Moving Cursor with Spacebar (for Every Character Moved)

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#862]
### Use Cases

A user requests that we allow the ability for haptic feedback for every character moved while moving the cursor with the spacebar.

### References

Email ticket #6386

**Comment by sustmi** [comment]
I think these are duplicate issues:
- https://github.com/futo-org/android-keyboard/issues/747
- https://github.com/futo-org/android-keyboard/issues/693

The following issue also mentions haptic feedback but the main point is vertical cursor movement by swiping space: https://github.com/futo-org/android-keyboard/issues/260 .

**Comment by dean-futo** [comment]
Closing as duplicate of #747
