### ISSUE TITLE
Keyboard freezes / lags when pressing space while typing fast with caps lock enabled

### ISSUE THREAD

**Issue by AntsyBoi** [futo-org/android-keyboard#873]
### What happened?

When pressing space while typing fast with caps lock enabled, the keyboard still receives all input but freezes temporarily. Once it is no longer frozen it types out everything as pressed whole frozen. 

### Keyboard Version

0.1.24

### Text field info

![Screenshot_20241125-153446](https://github.com/user-attachments/assets/eb475794-dd41-4516-b36f-778bfd65149e)

**Comment by abb128** [comment]
This will be fixed in the next update
