### ISSUE TITLE
Customize Expiration Time for Unpinned Clipboard Entries

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#881]
### Use Cases

A user requests that add the ability to customize the expiration times for unpinned clipboard entries, allowing you to set how long recent entries are kept before they are automatically deleted.

### References

Email ticket #6494

**Comment by abb128** [comment]
Duplicate of #119, #225 (they should probably be consolidated)

**Comment by dean-futo** [comment]
@abb128 merged them into #225.
