### ISSUE TITLE
More Efficient Keyboard Shortcuts for Select All/Copy/Cut/Paste

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#884]
### Use Cases

A user requests a more efficient way to use keyboard shortcuts for "Select All," "Copy," "Cut," and "Paste", as he finds the current text selection methods to be inefficient.

### Proposal

Either:
- Modify the predictive text area to show these commands when the text field is empty or when the user is not actively typing.
- Implement swiping gestures that allow you to swipe from the spacebar to specific keys like "a," "c," "x," or "v" for their respective functions.

### References

Email ticket #6402

**Comment by abb128** [comment]
You can already long-press letters like a, x, c, v for these shortcuts

**Comment by dean-futo** [comment]
@abb128 right, probably best to keep it simple with long-press rather than adding an unusual swiping version of these shortcuts.
