### ISSUE TITLE
Automatically Complete a Set of Brackets When Typing Opening Bracket

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#885]
### Use Cases

A user requests that the keyboard automatically completes a set of brackets when you type an opening bracket, such as (, {, or [. For example, if you type (, the keyboard will instantly add the closing ) and position the cursor inside the brackets, allowing you to type your content right away.

### References

Email ticket #6375

**Comment by abb128** [comment]
I don't believe there is any keyboard that implements this so it would be unexpected for users. A lot of code editors already implement this themselves so it would potentially conflict

**Comment by dean-futo** [comment]
@abb128 right on.
