### ISSUE TITLE
[question] How good is futos compatibility with custom roms?

### ISSUE THREAD

**Issue by Fuoxden** [futo-org/android-keyboard#89]
I have been wanting to try out a custom rom on my next phone, i was planing on seeing if futo had good enough compatibility to use it as my main keyboard.

**Comment by I-Dude** [comment]
Using Futo keyboard with Graphene OS. Seems to work fine as far as I can tell.

**Comment by abb128** [comment]
There's no dependency on google play services or anything, so everything should work without issues. I use a custom ROM myself. If you do experience any specific issues, feel free to open an issue
