### ISSUE TITLE
Feature Request: Dvorak keyboard layout

### ISSUE THREAD

**Issue by Business-Wizard** [futo-org/android-keyboard#9]
My one critical feature usecase to migrate to this key card provider is Dvorak keyboard layouts. I love what Futo is developing and look forward to this being supported.

If it helps with "why":
- match my daily keyboard layout, desktop and mobile
- enable touch typing (don't have to stare an the phone's keyboard)
- improved use of both thumbs; reduced risk of pain from typing

Priorities in my case: US English, Spanish, German.

**Comment by FraYoshi** [comment]
I agree, Dvorak use Dvorak e.where.. would love to have it also on the FUTO keyboard..
my priorities are English and Italian.
An alternative, would be to let us build our layout ;)

**Comment by Business-Wizard** [comment]
Is there a contributors process? I have experience, and could likely get up to speed if shown some basic direction. ☺️

**Comment by abb128** [comment]
In 0.1.20 there's more keyboard layout options, although Spanish and German currently lack other options

**Comment by abb128** [comment]
Expanded layout options for other latin-based languages in 0.1.21
