### ISSUE TITLE
Lagged Typing When Caps Lock Enabled

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#905]
### What happened?

A user reports that when caps lock is enabled and you start typing fast, the keyboard starts lagging.

### Keyboard Version

0.1.24

**Comment by MrLion28** [comment]
This has been happening to me as well ever since the last "big" update. I remember users having lag some months ago but on my phone it was smooth (galaxy A22). Now whenever I type with caps it lags

**Comment by abb128** [comment]
Duplicate of #873
