### ISSUE TITLE
Long press fails on bottom edge of key

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/android-keyboard#906]
### What happened?

Long pressing the bottom edge of a key will sometimes not output anything

https://github.com/user-attachments/assets/62d33069-5b4e-4e33-b1cd-0ecb71850b2e

### Keyboard Version

0.1.24-3-g42dc6ae84-unstable

**Comment by FireNinja7365** [comment]
The issue is still present in v0.1.24-26-gf9507b005-unstable

**Comment by abb128** [comment]
Should no longer happen on 0.1.24-35 nightly

**Comment by FireNinja7365** [comment]
Just tried it again and it still happens on version 0.1.24-40-g8c05b8082-unstable
