### ISSUE TITLE
Auto-spacing after '.' Should not triggered typing links

### ISSUE THREAD

**Issue by BrancuAlexandru** [futo-org/android-keyboard#907]
### What happened?

Currently it triggers when typing domains with subdomains. 

### Keyboard Version

0.1.24

### Text field info

What's app chat

**Comment by abb128** [comment]
If you type `https://` or `www.` it should avoid putting a space, otherwise there isn't really a way for the keyboard to know if you're typing a subdomain or ending a sentence. You can adjust the automatic space settings if it bothers you

**Comment by BrancuAlexandru** [comment]
I did type https:// and it does not work. It will capitalise and auto-dot. Try it:
https://dulces-erga-omnes.web.app
(This is a website I'm working on)

**Comment by abb128** [comment]
I see it's a bug with dashes, it will be fixed
