### ISSUE TITLE
[Feature Request] Long-press characters visualisation

### ISSUE THREAD

**Issue by AsenG60** [futo-org/android-keyboard#91]
Good day FUTO team. I recently installed the FUTO keyboard and I find it almost identical to Gboard (which is excellent), but there is one small feature missing that I use every day. I don't really like switching the keyboard pages to access the simple special characters and I usually use long-press to get to them. In reality, this feature is already implemented on your keyboard, but there is no option to display in small font the secondary characters and I don't really want to learn where each character is. Could you please add this feature?

Thank you for the great work!

**Comment by abb128** [comment]
Enable "Show symbol hints" in theme settings
