### ISSUE TITLE
Transcription keeps getting cut off

### ISSUE THREAD

**Issue by danielrosehill** [futo-org/android-keyboard#910]
### What happened?

Perhaps this is related to the limitations of chunking or whatever but here's what I've been experiencing.

Device: Samsung Galaxy A23 5G.

OS: Android 1.4 / One UI 6.1

App: Perplexity

Behavior: using Futo voice typing, it cuts off after about 20 seconds of dictating

### Keyboard Version

v0.1.24-playstore

**Comment by abb128** [comment]
If you mean that it auto stops after 30 seconds, this is a duplicate of #719. There is a toggle to remove this limit now, see my response in that issue
