### ISSUE TITLE
Ability to make keyboard height 175% was removed.

### ISSUE THREAD

**Issue by defiling9046** [futo-org/android-keyboard#911]
### What happened?

Moving to v0.1.24 the ability to make the keyboard height 175% was removed since it got changed from being a slider which allowed 175% to a new way of adjusting the keyboard height which does not allow 175% as the way you adjust the keyboard in the new version of the app has a max height limit which looks to be quite a bit less than 175%.

### Keyboard Version

0.1.24

**Comment by abb128** [comment]
Can you describe a use case for having such a tall keyboard? This would be more than half the screen usually

**Comment by defiling9046** [comment]
> Can you describe a use case for having such a tall keyboard? This would be more than half the screen usually

I find it more comfortable to type with the keys being taller with fat fingers and have gotten used to it after using 175% for about a year now. 

Even if the option for to make it 175% was in the developer options I'd really appreciate it as this is one of the best keyboard apps I've tried.

**Comment by abb128** [comment]
The max height will be higher in the next update

**Comment by defiling9046** [comment]
Thanks. Much appreciated.
