### ISSUE TITLE
Suggestion Bar Issue When Typing Comment on Instagram 

### ISSUE THREAD

**Issue by bruceschaff** [futo-org/android-keyboard#920]
### What happened?

While trying to type a comment on instagram, instead of the suggestions i have the password manager bar (sorry i don't know the correct terms) showing up.

### Keyboard Version

0.1.24-playstore

### Text field info

Instagram comments

**Comment by dean-futo** [comment]
@bruceschaff will you please include a video of the issue?

**Comment by bruceschaff** [comment]
@dean-futo was not able to reproduce. I see there's another issue #956 opened with the same problem on another site. I think this ticket cn be closed.
