### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by xdesniy** [futo-org/android-keyboard#933]
### Use Cases

Hello FUTOkeyboard team, I would like to thank you for this beautiful keyboard and I would like to suggest some additions that would facilitate my experience and I hope to find them one day in this keyboard. First, I wish the number row was in English only because Arabic is my mother tongue, but we use English numbers. Second, the icons in the suggestions bar would be better if they were in the middle because I switch the phone between my hands sometimes. Third, regarding the language change button, why is there no way to make it next to the space bar like most keyboards because its presence in the suggestions bar is a bit confusing. Also, when you paste from the clipboard, you cannot delete a letter or part of the word, but what happens is that it is completely deleted.

**Comment by dean-futo** [comment]
@xdesniy, glad you're liking the keyboard. You can place the language button next to the spacebar by going to Edit Actions and dragging the Language Switch Key to Edit Actions. Key-by-key layout customization is on our radar to implement; see #835. We're going to leave the icons where they are, as most users prefer the current interface.
