### ISSUE TITLE
[feature request] always show keys in sub menus with "always show number row" on

### ISSUE THREAD

**Issue by ccn0** [futo-org/android-keyboard#95]
when you open the symbols 2nd page with "always show number row", it hides the number row. theres still empty space for where it was, but the number row is hidden.
this is also the case with the top symbols row, which could show in the empty space but doesn't.

**Comment by abb128** [comment]
Not sure I understand correctly. If this is regarding the empty symbols row when number row is active, it will be filled in with symbols in the next update
