### ISSUE TITLE
Add German layout with umlauted vowels

### ISSUE THREAD

**Issue by Varg-sec** [futo-org/android-keyboard#96]
Please add the possibility to select a QWERTZ layout with umlauted vowels (ä, ö, ü).

**Comment by Px7-941** [comment]
As a workaround try swiss german

**Comment by Varg-sec** [comment]
Thanks. It is funny, since I played around this morning and found this layout as well. Anyhow, it would be very cool to have this for German too.

**Comment by Dav-Git** [comment]
This is pretty relevant for good German language support as virtually all german keyboards follow the QWERTZ + Umlaut (ÄÖÜ) Keys scheme

**Comment by Zugschlus** [comment]
+1. Please add this.
