### ISSUE TITLE
UK English £ symbol

### ISSUE THREAD

**Issue by EroticPlum** [futo-org/android-keyboard#973]
### Language

English (UK)

### Description

1234567890@#$_%&-+()*"':;!?
$ should be £ default as it is UK keyboard

### Complexity

nope, just swap the symbols

**Comment by Solar-Simon** [comment]
Nice, i just wanted to open the same issue, but for € Euro.

So maybe it would be nice to have the Option to choose your currency? And have one default for each Language?

**Comment by dean-futo** [comment]
Closing as duplicate of #766
