### ISSUE TITLE
One click change language (fast change language) 

### ISSUE THREAD

**Issue by Today20092** [futo-org/android-keyboard#979]
### Use Cases

The problem is it takes a long time and it's not easy to switch between languages quickly.

It is too much finger movement away from the keyboard and takes too long that interrupts the flow if you're switching between languages.

### Proposal

Proposal is to have an option that changes the long press on the spacebar to, instead of opening a menu, it'll just cycle through the languages in order.

Or another feature that may be implemented is when holding on a space bar, you can then choose the language just like you do with special characters.

Example of the hold space bar feature
![Screenshot_20241224_101209_Brave](https://github.com/user-attachments/assets/e912a7f2-07a2-4176-9a45-362a64f023fb)

Instead of the &, | it could be Spanish, English, German, etc. Or you can put a custom letter to put there. 

This would make it a click and drag then release which would be much faster.

The cycling option would be great for those with only two languages. Hold to switch.

**Comment by vanaigr** [comment]
`Keyboard & Typing` > `Edit Actions`.

You can put the `Language switch Key` into `Action Keys` or `Pinned Action(s)`.

Does that cover your usecase?

**Comment by dean-futo** [comment]
Closing this as you can already do what @vanaigr mentioned. There are two ways you can switch languages. The first is by pressing the globe icon in the Action Bar, located near the top left of the keyboard. The second is by either long-pressing or swiping the spacebar; you can customize your spacebar language-switching behavior by going to Settings -> Keyboard & Typing -> Long-Press Keys & Spacebar -> Spacebar Behavior.
