### ISSUE TITLE
option to disable goto end of word on word focus

### ISSUE THREAD

**Issue by deathblade666** [futo-org/android-keyboard#98]
Provide an option to enable/disable either place the cursor exactly where pressed within a word or goto end of selected word (current behaviour).

**Comment by swishkin** [comment]
I'm not sure if I'm misunderstanding or not, but my experience is that I'm able to place the cursor in the middle of a word without on first try, and it doesn't place the cursor at the end of a word that I know of.

Could you provide a screen recording to show what you're seeing?

**Comment by kjkrum** [comment]
I haven't found a way to intentionally reproduce it, but it does randomly move the cursor to the end of a word when the cursor is placed at the beginning or in the middle of the word. It happens so often that it's become the #2 reason I'm switching back to GBoard for now.

**Comment by deathblade666** [comment]
Seems im also unable to intentionally reproduce. I know it happens but not sure under what circumstances. I'll try to pay better attention to things and see if i can figure out when it occurs

**Comment by deathblade666** [comment]
Ok i was able to find a possible scenario, when you focus on a text field for the first time (during that apps session), if you type in a few strings and click on one of them (i tested with 3 and selecting the middle of the second one) it should jump to the end of that string. I'll see if i can upload a video later today showing this.

**Comment by abb128** [comment]
This will be fixed in the next release
